### PR TITLE
Fix heroku deploy by adding bower to deps

### PR DESCRIPTION
**Pull request by mtc2013**
Pulling this in to clear blocking issue.

### CODE REVIEW

**Comment by diraulo** [comment]
@mtc2013 deploy of review app failed with this:

```shell
Sprockets::FileNotFound: couldn't find file 'nprogress' with type 'application/javascript'
```

**Comment by mtc2013** [comment]
@diraulo thanks.  i think it has to do with buildpacks not being set right and in the right order on the opened pr instances, ie develop-pr-1279.  I did this to the main develop server:

heroku buildpacks:clear
heroku buildpacks:set heroku/nodejs
heroku buildpacks:add heroku/ruby --index 2

I think this will get it past that error because it will run nodejs buildpack first.

**Comment by mtc2013** [comment]
Perhaps this can best be integrated into the app.json somehow.

**Comment by mtc2013** [comment]
@diraulo just pushed a change to app.json.  Hope that will clear things up.

**Comment by mtc2013** [comment]
pushed another change that is probably more sensible.  preinstall hook to put in bower.

**Comment by mtc2013** [comment]
@diraulo @tansaku successfully deployed. yah!  had to ultimately add bower to our own dependencies.

**Pull request merged**
