### PR TITLE
Make event drop down show only active projects

### LINKED ISSUE #1811: only show active projects in project dropdown on volunteers page
at the moment we are seeing every project that ever existed in the volunteers page dropdown:

screenshot 2017-09-06 12 14 01

we could make make this easier to navigate if we made it only active projects like we've done on the main project page ...

### PR DESCRIPTION
**Pull request by aonomike**
fixes #1811 

Make project dropdown only show active projects on volunteers page
#### Description

Filter only active projects to be displayed on the projects dropdown
#### Motivation and Context

To reduce the number of projects displaved on the dropdown
#### How Has This Been Tested?

I havent writen acceptance tests yet, but I have tested manually on the UI
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Fixes #1811

### CODE REVIEW

**Comment by mattwr18** [comment]
Failing the build with this error:
```
When I filter "projects" for "hello world" # features/step_definitions/user_steps.rb:496
      Unable to find visible option "hello world" within #<Capybara::Node::Element tag="select" path="//HTML[1]/BODY[1]/DIV[1]/DIV[2]/DIV[1]/DIV[1]/DIV[1]/DIV[2]/FORM[1]/DIV[1]/DIV[1]/SELECT[1]"> (Capybara::ElementNotFound)
      ./features/step_definitions/user_steps.rb:513:in `/^I select "(.*?)" from the "(.*?)" list$/'
      ./features/step_definitions/user_steps.rb:497:in `/^I filter "(.*?)" for "(.*?)"$/'
      features/users/user_list.feature:49:in `When I filter "projects" for "hello world"'
```
Was this failing locally as well @aonomike?

**Comment by aonomike** [comment]
Currently looks good @mattwr18

**Comment by tansaku** [comment]
@mattwr18 @aonomike I wonder if we should just merge this in and create a testing ticket for it - or do we want to get the tests in with the PR?

**Comment by aonomike** [comment]
I think we should add the tests in with the PR and label it as a WIP
@tansaku

**Comment by tansaku** [comment]
great work @aonomike !

**Pull request merged**
