### PR TITLE
Bump ruby version

### PR DESCRIPTION
**Pull request by yggie**
Updates the Ruby version from `2.2.2` to `2.3.0`

### CODE REVIEW

**Comment by diraulo** [comment]
Yo @yggie. When you get a chance please have a look at the merge conflicts. I'd like to merge this PR before any new one comes in 😉

**Comment by tansaku** [comment]
looks like the only conflict is this:

```
Given(/^that there are (\d+) past scrums$/) do |number|
<<<<<<< HEAD
  FactoryGirl.create_list(:event_instance, number.to_i, category: 'Scrum', created_at: rand(1.months.seconds.to_i).seconds.ago, project_id: nil)
=======
  FactoryGirl.create_list(:event_instance, number.to_i, category: 'Scrum', created_at: rand(1.months).seconds.ago, project_id: nil)
>>>>>>> develop
end
```

wish that kind of stuff was shown in the github interface - I did put in a feature request for that

**Comment by tansaku** [comment]
@yggie I can fix this and push to your repo (if I have permissions), or I could create a new branch on the main repo and merge a PR from there.

That's one of the reasons the core team is encouraged to open PRs from branches on the main repo as it gives the ability to do a more fine grained collaboration on individual PRs without requiring permissions on developer's own repos ...

**Comment by yggie** [comment]
oh let me do it, I didn’t realize there was still conflicts! @tansaku I will keep that in mind for the next PR ;)

**Comment by tansaku** [comment]
thanks @yggie - I'll leave it with you :-)

**Pull request merged**
