### PR TITLE
commit counts on profile page

### PR DESCRIPTION
**Pull request by tansaku**
Recreating this from my personal repo since CI didn't trigger on pull request from main repo branch ...

### CODE REVIEW

**Comment by diraulo** [comment]
Tests failing because of missing github `auth_token` in settings for `test` or `development` env
```yaml
github:
  auth_token: <%= ENV["GITHUB_AUTH_TOKEN"]
```

**Comment by tansaku** [comment]
thanks @diraulo - I've added that in and synced to upstream - has fixed up some tests, but I get the following spec failing locally:

```
1) ApplicationController global user messages should set @@message_status to false at application load
     Failure/Error: expect(
       
       expected: false
            got: true
       
       (compared using ==)
     # ./spec/controllers/application_controller_spec.rb:45:in `block (3 levels) in <top (required)>'
```

and these failing cucumbers:

```
(::) failed steps (::)

expected to find css "h4" with text "Support our fundraising campaign on Pledgie.org" but there were no matches (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/basic_steps.rb:373:in `block (2 levels) in <top (required)>'
./features/step_definitions/basic_steps.rb:369:in `/^I should( not)? see a flash with "([^"]*)"$/'
features/basic_layout.feature:13:in `Then I should see a flash with "Support our fundraising campaign on Pledgie.org"'

expected to find text "WebsiteOne - 388" in "Log in Sign up About Projects Members Articles Events Upcoming events Past scrums Past events Getting started Bryan Yap Member for less than a minute yggie About Skills Projects Activity About me Magnam et aperiam sed et saepe nihil culpa. Skills & Technologies ullam minus omnis optio Project Involvement WebsiteOne Contributions WebsiteOne - 394 commits Bryan Yap has no publicly viewable Youtube videos. × Contact Bryan Yap Close ×Close Set status Ready to pair Doing code review Plz, do not disturb Waiting for next scrum... Sleeping at my keyboard Close Learn More About Us Getting Started Dashboard Social Facebook Twitter Our Sponsors Makers Academy AirPair Becoming a sponsor AgileVentures - Crowdsourced Learning Contact us Send a traditional email to info@agileventures.org." (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/basic_steps.rb:167:in `/^I should( not)? see "([^"]*)"$/'
features/users/github_commit_count.feature:22:in `And I should see "WebsiteOne - 388"'

Failing Scenarios:
cucumber features/basic_layout.feature:12 # Scenario: Fundraising flash is displayed once
cucumber features/users/github_commit_count.feature:19 # Scenario: Displays commit counts on user profile page
```

**Comment by tansaku** [comment]
this pull request seems to include a few bits and pieces related to a fund raising campaign and message flash stuff.  Looks like the tests and some code components have been removed and then re-added here, maybe ...

**Comment by tansaku** [comment]
looks like they are commits from @tochman from a while back - wonder if those individual commits can just be deleted ...

**Comment by tansaku** [comment]
and funny thing is that it looks like the CI ran: https://semaphoreci.com/agileventures/websiteone/branches/pull-request-795/builds/2 but didn't get inserted into the pull request ...

**Comment by tansaku** [comment]
have replaced this with #800 which cherry picks just the needed components

**Pull request closed without merging**
