### PR TITLE
fix for failing hoa_button in test env

### LINKED ISSUE #751: some local cucumber failures
was checking @alejandrobabio 's rm ytube branch locally and I get these failures in cucumber:

```
(::) failed steps (::)

Unable to find css "#liveHOA-placeholder iframe" (Capybara::ElementNotFound)
./features/step_definitions/hangout_steps.rb:2:in `/^I should see hangout button$/'
features/hangout.feature:27:in `Then I should see hangout button'

Unable to find css "#liveHOA-placeholder iframe" (Capybara::ElementNotFound)
./features/step_definitions/hangout_steps.rb:2:in `/^I should see hangout button$/'
features/hangout.feature:103:in `Then I should see hangout button'

expected to find text "00:00 15/04" in "Anders Persson My account Log out About Projects Members Articles Events Upcoming events Past scrums Past events Getting started Current Projects hello world hello mars Supporters Become a supporter Projects hello world hello world greetings earthlings Start Live Hangout × Info You should join this project before you can start the hangouts Close Project status: ACTIVE Created less than a minute ago by Tester Person Join Project Connected on not linked to GitHub not linked to PivotalTracker Members (0) No members in project hello world × The hello world team About Documents (0) Videos (3) Activity (0) Project content missing :( A compelling pitch can make your project more appealing to potential collaborators. Please edit project details to add pitch content. No documents can be found for project hello world PP on hello world - feature: 2 Latest Project videos Video Host Published PP on hello world - feature: 2 John Doe 00:02 14/04 PP on hello world - feature: 1 John Doe 00:01 14/04 PP on hello world - feature: 0 John Doe 00:00 14/04 No PivotalTracker Stories can be found for project hello world Learn More About Us Getting Started Dashboard Social Facebook Twitter Our Sponsors Makers Academy AirPair Becoming a sponsor AgileVentures - Crowdsourced Learning Contact us Send a traditional email to info@agileventures.org." (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/basic_steps.rb:161:in `block (2 levels) in <top (required)>'
./features/step_definitions/basic_steps.rb:160:in `each'
./features/step_definitions/basic_steps.rb:160:in `/^I should( not)? see:$/'
features/project_videos.feature:24:in `And I should see:'

Failing Scenarios:
cucumber features/hangout.feature:25 # Scenario: Create a hangout for a scrum event
cucumber features/hangout.feature:100 # Scenario: Display hangout button on a project's page
cucumber features/project_videos.feature:16 # Scenario: Project show page renders a list of videos
```

CI is fine - so assume I am missing something on my local system ...

### LINKED ISSUE #777: tests failing locally for me on OSX Yosemite
```
(::) failed steps (::)

Unable to find css "#liveHOA-placeholder iframe" (Capybara::ElementNotFound)
./features/step_definitions/hangout_steps.rb:2:in `/^I should see hangout button$/'
features/hangout.feature:27:in `Then I should see hangout button'

Unable to find css "#liveHOA-placeholder iframe" (Capybara::ElementNotFound)
./features/step_definitions/hangout_steps.rb:2:in `/^I should see hangout button$/'
features/hangout.feature:103:in `Then I should see hangout button'

Failing Scenarios:
cucumber features/hangout.feature:25 # Scenario: Create a hangout for a scrum event
cucumber features/hangout.feature:100 # Scenario: Display hangout button on a project's page
```

### PR DESCRIPTION
**Pull request by tochman**
* Fixes problem with failing cucumber steps that involve HOA button (works locally at my machine)
* Build upon @mtc2013 's old PR #710 
* Fixes #751, fixes #777

### CODE REVIEW

**Comment by sampritipanda** [comment]
Will this fix the failures caused by Mercury tests?

**Comment by tochman** [comment]
Not sure. What we are introducing is a slightly more 'forgiving' way to us Poltergeist.

**Comment by tansaku** [comment]
@diraulo this is working locally for me so I'm going to go ahead and merge and see how we go

**Comment by tansaku** [comment]
rats - I should have tested the entire suite before merging.  It fixes the failing hangout stuff, but I get a new error that comes as a result of the ssl change:

```
 Scenario: Editing Pitch content with Mercury Editor                                                    # features/projects.feature:182
    Given I am logged in                                                                                 # features/step_definitions/user_steps.rb:19
    And I am on the "Show" page for project "hello mars"                                                 # features/step_definitions/basic_steps.rb:236
    And I click the "Join Project" button                                                                # features/step_definitions/basic_steps.rb:77
    And I am using the Mercury Editor to edit project "hello mars"                                       # features/step_definitions/mercury_steps.rb:27
    When I fill in the editable field "Pitch" for "project" with "This is my exciting marketing content" # features/step_definitions/mercury_steps.rb:9
    And I click "Save" within Mercury Editor toolbar                                                     # features/step_definitions/mercury_steps.rb:1
    Then I should see a flash "The project has been successfully updated."                               # features/step_definitions/basic_steps.rb:173
      expected to find css ".alert" with text "The project has been successfully updated." but there were no matches (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:175:in `/^I should( not)? see a flash "([^"]*)"$/'
      features/projects.feature:189:in `Then I should see a flash "The project has been successfully updated."'
    Then I should be on the "Show" page for project "hello mars"                                         # features/step_definitions/basic_steps.rb:232
    And I should see "This is my exciting marketing content"                                             # features/step_definitions/basic_steps.rb:165
    HTML screenshot: /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/tmp/capybara/screenshot_2016-02-12-09-54-30.864.html
    Image screenshot: /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/tmp/capybara/screenshot_2016-02-12-09-54-30.864.png

Failing Scenarios:
cucumber features/projects.feature:182 # Scenario: Editing Pitch content with Mercury Editor
```

**Comment by tochman** [comment]
So weird, I do not get that when I run the entire test suite. And it Passes on Semaphore...

**Comment by tansaku** [comment]
I've been debugging with poltergeist ... the inspector doesn't show the flash message either with or without the ssl setting:

using the inspector

what OSX are you on @tochman ?  I recently upgraded to Qt5 as well ...

**Comment by tansaku** [comment]
btw, this is the links the inspector shows during debugging:

inspector options

**Comment by tochman** [comment]
I'm on Yosemite 10.10.5

**Comment by tansaku** [comment]
I am also on yosemite 10.10.5

**Comment by tochman** [comment]
We had issues with testing Mercury before...
It passed just now (single scenario run)
```
 @javascript
  Scenario: Editing Pitch content with Mercury Editor                                                    # features/projects.feature:182
    Given I am logged in                                                                                 # features/step_definitions/user_steps.rb:19
    And I am on the "Show" page for project "hello mars"                                                 # features/step_definitions/basic_steps.rb:240
    And I click the "Join Project" button                                                                # features/step_definitions/basic_steps.rb:77
    And I am using the Mercury Editor to edit project "hello mars"                                       # features/step_definitions/mercury_steps.rb:27
    When I fill in the editable field "Pitch" for "project" with "This is my exciting marketing content" # features/step_definitions/mercury_steps.rb:9
    And I click "Save" within Mercury Editor toolbar                                                     # features/step_definitions/mercury_steps.rb:1
    Then I should see a flash "The project has been successfully updated."                               # features/step_definitions/basic_steps.rb:177
    Then I should be on the "Show" page for project "hello mars"                                         # features/step_definitions/basic_steps.rb:236
    And I should see "This is my exciting marketing content"                                             # features/step_definitions/basic_steps.rb:169

1 scenario (1 passed)
11 steps (11 passed)
0m9.620s
```

**Comment by tansaku** [comment]
when I have it set to ignore ssl errors the inspector takes me to a completely different page, i.e. 

inspector output from ssl errors ignored

It makes me think that ignoring the ssl errors allows the mercury engine to fully load or something else weird ...

**Comment by tansaku** [comment]
no wait - I guess what I'm see here is that on my system, with ignoring ssl errors, that the page is just stuck on the mercury editor in edit mode and that it hasn't successfully saved, which is what it needs to do to go back to the normal page and have the flash appear ....

**Comment by tochman** [comment]
@tansaku I would do a roll-back if you can't get this to work. I've run the entire suite a few times and it fails for me occasionally. Don't have time to spend on it atm.

**Comment by tansaku** [comment]
thanks @tochman, btw what version of phantomjs are you on? I was on 1.9.8 and just upgraded to 2.1.1, but now getting an error similar to @freeranger related to requiring phantomjs 1.8.1

**Comment by tochman** [comment]
1.9.8

**Comment by tansaku** [comment]
@tochman: @sampritipanda and I may have fixed it ... seems like a phantomjs requirement that we need to document ...

**Comment by tansaku** [comment]
I have just downgraded to 1.8.2 ...

**Comment by tochman** [comment]
+1

**Comment by tansaku** [comment]
of course now the hangout tests fail when running in batch locally, but pass individually ... arg!

**Comment by tansaku** [comment]
I have confirmed that the mercury test fails with phantomjs 1.9.8 while the hangout test fails on 1.8.1 and they each pass on the other versions ...

**Pull request merged**
