### PR TITLE
draw borders around project sidebar groups

### PR DESCRIPTION
**Pull request by ZmagoD**
* added project-sidebar-group class to add borders
 * added to _highlight_box project-sidebar-group class
 * added to _connections to project-sidebar-group class
 * added to _members_list to project-sidebar-group class

### CODE REVIEW

**Comment by bill-auger** [comment]
may close this story --> https://www.pivotaltracker.com/story/show/85684660

**Comment by diraulo** [comment]
@ZmagoD @bill-auger get changes from `upstream` and update the pull-request.

**Comment by bill-auger** [comment]
the OP seems unresponsive - PR #723 has been issued as a replacement - this PR may be closed as a duplicate

PR #723 is the same commit as the head of this PR but rebased onto the current develop branch

@ZmagoD - you will need to git pull -f to get re-sync

**Comment by diraulo** [comment]
Closing this one. I just merged #723

**Pull request closed without merging**
