### PR TITLE
Test driven fix of the timezone issue on the events list page

### LINKED ISSUE #953: events index is showing me a combination of GMT and BST timezones
this is a timezone issue

### PR DESCRIPTION
**Pull request by tansaku**
fixes #953

We've been trying to test this, but it relies on being able to set the timezone for the capybara javascript driver, which we can't yet work out how to do - have opened a ticket with capybara: https://github.com/jnicklas/capybara/issues/1685

### CODE REVIEW

**Comment by tansaku** [comment]
We worked out how to test - thanks @dalupus - it involves switching timezones on and off - yay!

**Comment by tansaku** [comment]
@diraulo @dalupus argh - the great fix for testing timezones from @dalupus worked on my machine and @mtc2013's machine but is failing on CI for some reason ...

**Comment by diraulo** [comment]
@tansaku @mtc2013 this is also failing for me locally.

**Comment by tansaku** [comment]
@diraulo is that on ubuntu/C9?  what's your platform?

**Comment by diraulo** [comment]
@tansaku osx

**Comment by tansaku** [comment]
hmm, weird - you on el capitan, yosemite? @diraulo can you paste your error message in here?

**Comment by diraulo** [comment]
@tansaku El Capitan.

hmmm... weird. I just tried to run that feature alone and it passed 🤔
But when running the entire suite, I get a failure.

**Comment by tansaku** [comment]
@diraulo - want to paste that error in here? anyway, let's look at it together in the kick off

**Comment by diraulo** [comment]
```shell
  @javascript
  Scenario: Show correct timezone                                  # features/events/list_repeating_events.feature:17
    Given the date is "2016/05/01 09:15:00 UTC"                    # features/step_definitions/event_steps.rb:100
    And the browser is in "Europe/London" and the server is in UTC # features/step_definitions/event_steps.rb:124
    And I am on events index page                                  # features/step_definitions/event_steps.rb:15
    Then I should see "Standup"                                    # features/step_definitions/basic_steps.rb:193
    And I should see "08:00-10:30 (BST)"                           # features/step_definitions/basic_steps.rb:193
      expected to find text "08:00-10:30 (BST)" in "Log in Sign up ABOUT PROJECTS MEMBERS ARTICLES EVENTS GETTING STARTED AgileVentures Events We are hosting several events a day using Google Hangouts. Feel free to join in if you want to get involved or if you a curious about Pair Programming and Agile. Each event will have a link to an online Hangout prior to start time. Standup Mon, May 02, 2016 07:00-09:30 (UTC) Daily standup meeting PP Session Mon, May 02, 2016 10:00-10:15 (UTC) Pair programming on WSO Standup Tue, May 03, 2016 07:00-09:30 (UTC) Daily standup meeting PP Session Tue, May 03, 2016 10:00-10:15 (UTC) Pair programming on WSO Standup Wed, May 04, 2016 07:00-09:30 (UTC) Daily standup meeting PP Session Wed, May 04, 2016 10:00-10:15 (UTC) Pair programming on WSO Standup Thu, May 05, 2016 07:00-09:30 (UTC) Daily standup meeting PP Session Thu, May 05, 2016 10:00-10:15 (UTC) Pair programming on WSO Standup Mon, May 09, 2016 07:00-09:30 (UTC) Daily standup meeting PP Session Mon, May 09, 2016 10:00-10:15 (UTC) Pair programming on WSO Standup Tue, May 10, 2016 07:00-09:30 (UTC) Daily standup meeting PP Session Tue, May 10, 2016 10:00-10:15 (UTC) Pair programming on WSO Standup Wed, May 11, 2016 07:00-09:30 (UTC) Daily standup meeting Learn More About Us Getting Started Dashboard Social Facebook Twitter Our Sponsors Craft Academy AirPair Becoming a sponsor AgileVentures - Crowdsourced Learning Contact us Send a traditional email to info@agileventures.org." (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:195:in `/^I should( not)? see "([^"]*)"$/'
      features/events/list_repeating_events.feature:22:in `And I should see "08:00-10:30 (BST)"'
```

**Comment by tansaku** [comment]
thanks @diraulo - that's the same failure we get on CI - that it passes individually on yours suggests the fix will involve a timing issue - I have a feeling we might need something that just ensures that the JS has all finished running - we need a "ready" function for capybara/poltergeist ... or just something that ensures all JS has finished running on the homepage ...

but then again ...

**Comment by tansaku** [comment]
@dalupus updated with your latest and greatest testing strategy :-)

**Comment by diraulo** [comment]
@tansaku @mtc2013 have a look at conflicts here and update PRs 😉

**Comment by tansaku** [comment]
thanks @diraulo - would be nice if the github interface gave some indication of complexity of merge conflicts ... this one was kind of trivial ...

**Pull request merged**
