### PR TITLE
tries 10 secs as wait time

### LINKED ISSUE #806: intermittent js failure?
```
 Scenario: Insert media model rejects badly formatted youtube links                                      # features/documents.feature:170
    Given I am logged in                                                                                  # features/step_definitions/user_steps.rb:19
    And I am using the Mercury Editor to edit document "Guides"                                           # features/step_definitions/mercury_steps.rb:27
    And I am focused on the "document body" within the Mercury Editor                                     # features/step_definitions/contained_search_steps.rb:33
    And I click on the "Insert Media" button within the Mercury Toolbar                                   # features/step_definitions/contained_search_steps.rb:33
    And I fill in "YouTube URL" with "https://www.youtube.io/watch?v=foo" within the Mercury Editor Modal # features/step_definitions/contained_search_steps.rb:33
    And I click "Insert Media" within the Mercury Editor Modal                                            # features/step_definitions/contained_search_steps.rb:33
    Then I should see "is invalid" within the Mercury Modal                                               # features/step_definitions/contained_search_steps.rb:33
      expected to find text "is invalid" in "Insert Media (images and videos)× Images URL Videos YouTube URL Vimeo URL Options Alignment Float Width Height" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:167:in `/^I should( not)? see "([^"]*)"$/'
      ./features/step_definitions/contained_search_steps.rb:41:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/contained_search_steps.rb:41:in `/^(.*) within the (.*)$/'
      features/documents.feature:177:in `Then I should see "is invalid" within the Mercury Modal'
    And the Mercury Editor modal window should be visible                                                 # features/step_definitions/mercury_steps.rb:61
```
Failing Scenarios:
cucumber features/documents.feature:170 # Scenario: Insert media model rejects badly formatted youtube links

### PR DESCRIPTION
**Pull request by tansaku**
fixes #806

### CODE REVIEW

**Comment by tansaku** [comment]
okay, so we got a failure:

```
    Then I should see an image with source "/assets/mercury/missing-image.png" within the Mercury Editor # features/step_definitions/contained_search_steps.rb:33
      expected to find css "img[src*=\"/assets/mercury/missing-image.png\"]" but there were no matches (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:348:in `/^I should see an image with source "([^"]*)"$/'
      ./features/step_definitions/contained_search_steps.rb:38:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/contained_search_steps.rb:38:in `/^(.*) within the (.*)$/'
      features/documents.feature:155:in `Then I should see an image with source "/assets/mercury/missing-image.png" within the Mercury Editor'
```

I wonder if part of the issue here is that the tests are not sandboxed, i.e. some of the tests hit network connections that might be slow sometimes ... do we need some [puffing_billy](https://github.com/oesmith/puffing-billy) for the features like we have on LocalSupport???

Although perhaps a closer look at the tests is called for, but it would be good to get PuffingBilly set up and properly sandbox the client side of the tests ...

**Comment by tansaku** [comment]
hmm, so maybe we should try with a default 20sec timeout for a while ...

**Comment by diraulo** [comment]
@tansaku 
I was able to re-run this build.
- The first build failed at first try on `cucumber features/scrums.feature:19`. The second try was all good
- The second build passed at first try

**Comment by tansaku** [comment]
thanks @diraulo - sounds like it's not a solid fix ...

**Pull request closed without merging**
