### PR TITLE
Temporarily disable sign up

### PR DESCRIPTION
**Pull request by diraulo**

### CODE REVIEW

**Comment by tansaku** [comment]
thanks @diraulo - might it be a good idea to remove the form itself so that real users are not confused?  anyway, we've had at least 10 more sign ups over night, so we need to get something in place ...

**Comment by diraulo** [comment]
@tansaku with this change they'll be redirected to the home page with a flash message saying registration is currently disabled. If it's all good and CI passes i'll merge it and push to production.

**Comment by tansaku** [comment]
right, and github signup will still work @diraulo ?

**Comment by diraulo** [comment]
@tansaku github and g+ signups should still work. I just disabled the email form for now.

**Pull request merged**
