### PR TITLE
[WIP] Improve UX for User Profile Card Details

### LINKED ISSUE #3008: Fix UX for user profile card details button
Currently, we have a link to edit your profile, then a update card details button, followed by another link to set status
This is not a good UX experience
## Expected Behavior

Have the button, either before or after the links, not sandwiched by them, also should the button design be the same as the profile upgrade to premium* button

screenshot at 2019-01-18 12 46 58

### PR DESCRIPTION
**Pull request by clementkng**
- Moved the `Update Card Button` to below the `Edit Status` button
- Added spacing above member status to better differentiate the buttons

Any feedback (especially design) would be appreciated.

#### Issue addressed

fixes #3008 

#### Screenshots (if appropriate):

image

### CODE REVIEW

**Comment by clementkng** [comment]
@mattwr18 @tansaku do you have any feedback for this proposed change?

**Comment by aonomike** [comment]
Thanks for working on this @clementkng. Maybe we can write some cucumber tests to check that the links appear before the button? Tell me what you think and we can find time to pair on it.

**Comment by clementkng** [comment]
Hi @aonomike I'd like to try a few hours to write the cucumber tests myself for a bit just to learn the ecosystem better. If I can't figure it out, I'll try to schedule w/ you. How does that sound?

**Comment by aonomike** [comment]
> just

Sounds great @clementkng

**Comment by mattwr18** [comment]
I would actually encourage maybe not writing end-to-end cucumber tests for checking the position of the link since they are quite expensive.

I really like @clementkng that you added a screenshot showing what it looks like, and that would be enough for me, but maybe others have opposing opinions?

**Pull request merged**
