### PR TITLE
Integrate grape api

### LINKED ISSUE #2893: Integrate grape api
It's supposed to be really cool

### PR DESCRIPTION
**Pull request by mattwr18**
#### Issue addressed

fixes #2893

### CODE REVIEW

**Comment by mattwr18** [comment]
@tansaku, this is currently failing the build on this error:
```
Failure/Error:
  describe Api::SubscriptionsController, type: :request do
    describe "GET /subscriptions" do
      let(:user) { FactoryBot.create(:user, email: "kitty@cat.com") }
      let(:start_time) { DateTime.new(2001, 2, 3, 4, 5, 6) }
      let(:end_time) { DateTime.new(2002, 2, 3, 4, 5, 6) }
      let(:start_date) { '2001-02-03' }
      let(:end_date) { '2002-02-03' }
      let(:plan) { FactoryBot.create(:plan, name: 'Premium') }
      let!(:subscription) { FactoryBot.create(:subscription, user: user, sponsor: user, plan: plan, started_at: start_time, ended_at: end_time) }
      let!(:payment_source) { FactoryBot.create(:paypal, subscription: subscription) }

LoadError:
  Unable to autoload constant Api, expected /home/runner/WebsiteOne/app/api/events/api.rb to define it
```
We need to move the subscriptions api apparently... I'm assuming the endpoint is only visited by you?

**Comment by mattwr18** [comment]
endpoint for events api
`/api/v1/events/upcoming`

**Comment by tansaku** [comment]
@mattwr18 I haven't looked at the issue here, but @mtc2013 is the specialist on the api authentication methods and tests

**Comment by tansaku** [comment]
so just taking a quick look, at the moment the changes in `config/application.rb` appear to be causing the `uninitialized constant UserPresenter` error

**Comment by tansaku** [comment]
reverting the changes in config/application.rb I can get through to the api_subscriptions failures, e.g.

```
be rspec ./spec/requests/api_subscriptions_spec.rb:23
Run options: include {:locations=>{"./spec/requests/api_subscriptions_spec.rb"=>[23]}}

Randomized with seed 28858
F

Failures:

  1) Subscriptions::API GET /api/v1/subscriptions with proper token succeeds
     Failure/Error: expect(response).to be_successful
       expected `#<ActionDispatch::TestResponse:0x00007ffd7c07fa90 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::..., @method=nil, @request_method=nil, @remote_ip=nil, @original_fullpath=nil, @fullpath=nil, @ip=nil>>.successful?` to return true, got false
     # ./spec/requests/api_subscriptions_spec.rb:25:in `block (4 levels) in <top (required)>'

Finished in 1.12 seconds (files took 5.23 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/requests/api_subscriptions_spec.rb:23 # Subscriptions::API GET /api/v1/subscriptions with proper token succeeds
```

**Comment by tansaku** [comment]
inserting binding.pry it looks like the api_subscriptions_path is "/" which seems odd:

```
    20:       }
    21:     end
    22:     context 'with proper token' do
    23:       it "succeeds", :show_in_doc do
    24:         binding.pry
 => 25:         get subscriptions_api_path, params: {}, headers: headers
    26:         expect(response).to be_successful
    27:         expect(JSON.parse(response.body)).to include(a_hash_including("payment_source" => "PaymentSource::PayPal", "plan_name" => plan.name, "email" => "kitty@cat.com", "sponsor_email" => "kitty@cat.com", "started_on" => start_date, "ended_on" => end_date))
    28:       end
    29: 
    30:       context 'with nil ended_on' do

[1] pry(#<RSpec::ExampleGroups::SubscriptionsAPI::GETApiV1Subscriptions::WithProperToken>)> subscriptions_api_path
=> "/"
```

**Comment by tansaku** [comment]
although that's what rake routes gives:

```
                               events_api             /                                                                                        Events::API
                        subscriptions_api             /                                                                                        Subscriptions::API
                                users_api             /                                                                                        Users::API
                             projects_api             /                                                                                        Projects::API
```

**Comment by tansaku** [comment]
if I hit the `http://localhost:3000/api/v1/subscriptions` endpoint locally I get this error:

```
undefined method 'authenticate_or_request_with_http_token'
```

**Comment by tansaku** [comment]
alternatively we could maintain the two apis in separate namespaces to avoid having to implement token based authentication in grape in the short term ...

**Comment by mattwr18** [comment]
> alternatively we could maintain the two apis in separate namespaces to avoid having to implement token based authentication in grape in the short term ...

this is what I originally tried, which gave the above error that it was trying to be autoloaded `LoadError:
  Unable to autoload constant Api, expected /home/runner/WebsiteOne/app/api/events/api.rb to define it`

> if I hit the `http://localhost:3000/api/v1/subscriptions` endpoint locally I get this error:
> 
> ```
> undefined method 'authenticate_or_request_with_http_token'
> ```
> and the problem is that this is a rails controller method that Grape doesn't know anything about, so we either try to expose this method from rails to Grape, or we find something specifically for authentication tokens that works with Grape ...
> 
> this looks like it might be a good way to go:
> 
> https://github.com/mcordell/grape_token_auth

I was able to get passed this by rewriting the `authenticate_token` method like so
```rb
def authenticate_token
  Settings.api.premium_subscriptions_token
end
```
this allowed me to visit the endpoint `api/v1/subscriptions` and get this `error | "401 Unauthorized"`, but the tests still fail in the same way as above  ^^^

I have been able to get a successful response in the tests now, but it seems it is redirecting to the homepage, also, it is returning html

**Comment by mattwr18** [comment]
Closing this as it was addressed with this PR https://github.com/AgileVentures/WebsiteOne/pull/2899

**Pull request closed without merging**
