### PR TITLE
Youtube URL is posted on Slack but not Hangout URL when Youtube URL is editted

### PR DESCRIPTION
**Pull request by lokeshh**
Fixes the bug that **both Youtube and Hangout URL are posted when Youtube URL is edited**.

Discussed in https://www.youtube.com/watch?v=IKtO9cn4Rbc

### CODE REVIEW

**Comment by tansaku** [comment]
```  1) EventInstancesController#update slack notification calls the SlackService to post yt_link on successful update
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       Exactly one instance should have received the following message(s) but didn't: yt_video_id?
```
@lokeshh we get the above error in CI - do you get it locally?

**Comment by tansaku** [comment]
@lokeshh can you have a look at this failure? thanks :-)

**Comment by tansaku** [comment]
@lokeshh the full error trace is:

```

  1) EventInstancesController#update slack notification calls the SlackService to post yt_link on successful update
     Failure/Error: DEFAULT_FAILURE_NOTIFIER = lambda { |failure, _opts| raise failure }
       Exactly one instance should have received the following message(s) but didn't: yt_video_id?
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.6.0/lib/rspec/support.rb:87:in `block in <module:Support>'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-support-3.6.0/lib/rspec/support.rb:96:in `notify_failure'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.6.0/lib/rspec/mocks/error_generator.rb:327:in `notify'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.6.0/lib/rspec/mocks/error_generator.rb:311:in `__raise'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.6.0/lib/rspec/mocks/any_instance/error_generator.rb:7:in `raise_second_instance_received_message_error'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.6.0/lib/rspec/mocks/any_instance/recorder.rb:95:in `verify'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.6.0/lib/rspec/mocks/space.rb:75:in `block in verify_all'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.6.0/lib/rspec/mocks/space.rb:75:in `each_value'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.6.0/lib/rspec/mocks/space.rb:75:in `verify_all'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-mocks-3.6.0/lib/rspec/mocks.rb:45:in `verify'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/mocking_adapters/rspec.rb:23:in `verify_mocks_for_rspec'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:514:in `verify_mocks'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:508:in `run_after_example'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:273:in `block in run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `block in run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:604:in `block in run_around_example_hooks_for'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:342:in `call'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-rails-3.6.0/lib/rspec/rails/example/controller_example_group.rb:191:in `block (2 levels) in <module:ControllerExampleGroup>'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:375:in `execute_with'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:342:in `call'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-rails-3.6.0/lib/rspec/rails/adapters.rb:127:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:447:in `instance_exec'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:375:in `execute_with'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:606:in `block (2 levels) in run_around_example_hooks_for'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:342:in `call'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:607:in `run_around_example_hooks_for'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/hooks.rb:464:in `run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example.rb:251:in `run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:627:in `block in run_examples'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `map'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:623:in `run_examples'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:589:in `run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `block in run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `map'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/example_group.rb:590:in `run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `map'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1894:in `with_suite_hooks'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:113:in `block in run_specs'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/reporter.rb:79:in `report'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:112:in `run_specs'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:87:in `run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 1 minute 8.39 seconds (files took 7.66 seconds to load)
932 examples, 1 failure, 1 pending

Failed examples:

rspec ./spec/controllers/event_instances_controller_spec.rb:74 # EventInstancesController#update slack notification calls the SlackService to post yt_link on successful update
```

**Comment by tansaku** [comment]
the key here might be that the way we are using the controller has changed and so the spec has to be updated, but it needs careful review

**Comment by lokeshh** [comment]
@tansaku Done. This can be merged now.

**Pull request merged**
