### PR TITLE
Add Press-Kit link to footer

### LINKED ISSUE #1738: make a press-kit link in the footer
that would link to https://www.agileventures.org/press-kit

### PR DESCRIPTION
**Pull request by Xiaohong-Deng**
closes #1738 

Added a press-kit link to the footer. Also added a rspec test to `application.html.erb_spec.rb` in

```ruby

  context 'within the site footer' do
  ...
  end

```

to test there is a such link called "Press Kit"

### CODE REVIEW

**Comment by tansaku** [comment]
hi @Xiaohong-Deng - thanks for this great work

we've been tending away from view specs and preferring cucumber tests that explicitly state the high level intention - any interest in trying to create a cuke for this?

**Comment by Xiaohong-Deng** [comment]
@tansaku I'd like to. Is there a `.feature` somewhere suitable for me to add a line or I need to create a new one? If it's the latter, how large the ground should I cover? The footer?

**Comment by tansaku** [comment]
there's one here: https://github.com/AgileVentures/WebsiteOne/blob/develop/features/basic_layout.feature#L34 although it's getting rather unstory like - we should probably break into multiple features in separate files - indicating the business case for each, but you don't have to worry about that unless you're interested - simply creating or extending a cuke is a great start ...

**Comment by Xiaohong-Deng** [comment]
@tansaku OK. I moved the rspec test to the cuke. That passed the auto checks including semaphore ci. but after I merge develop to my branch, semaphore ci fails. Not on me.

**Comment by tansaku** [comment]
@Xiaohong-Deng no worries - that's one of our annoying intermittent fails - I've restarted the build

**Comment by tansaku** [comment]
and I'm just merging in benny's change ...

**Pull request merged**
