### PR TITLE
1960 Add sponsor relationship

### LINKED ISSUE #1960: Add sponsor-sponsee relationship
Add change to model to accommodate accurate representation of when a user sponsors another.

### PR DESCRIPTION
**Pull request by marianmosley**
- Add sponsor_id column to subscriptions table
- Set sponsor to current user in the subscriptions controller

fixes #1960

### CODE REVIEW

**Comment by mtc2013** [comment]
@tansaku if sponsoring user is not signed-in, which they are not currently required to be, then we have no way to properly record who they are in an automated fashion.  We could assume in this case that the user is being sponsored?  Or should we start requiring them to be logged-in first?

**Comment by tansaku** [comment]
@mtc2013 I think it's time to require being logged in - please feel free to add that

**Comment by tansaku** [comment]
code climate says:

**Comment by mtc2013** [comment]
@tansaku after our discussion, is this ready to go?

**Pull request merged**
