### PR TITLE
Better dev part two

### PR DESCRIPTION
**Pull request by mtc2013**
This will make it so that the developer does not need to rebuild the image just because of an edit to basic source code.  However, changing dependencies, like gems, may still require a rebuild.

### CODE REVIEW

**Comment by mtc2013** [comment]
@tansaku please start reviewing

**Comment by diraulo** [comment]
I tried this setup and seems to be working fine. Made a few changes to views and didn't need to rebuild the image. Looks good IMO @mtc2013 but looks like you might need to update your branch with upstream?

**Comment by tansaku** [comment]
@mattwr18 and friends seem very excited about this - will merge in

**Comment by tansaku** [comment]
many thanks @mtc2013 :-)

**Pull request merged**
