### PR TITLE
Unvendoring the JavaScript

### LINKED ISSUE #1080: Move the new javascript files to an automated management system and out of vendor files
Possibly npm, bower, or grunt/gulp.

### PR DESCRIPTION
**Pull request by tansaku**
fixes #1080

### CODE REVIEW

**Comment by tansaku** [comment]
hmm did we lose automated deploys since I moved develop to my personal heroku account ...

**Comment by mtc2013** [comment]
@diraulo let me commit and close this after you sign off so i can be credited on the commit in master.

**Comment by mtc2013** [comment]
@tansaku apparently this didn't deploy successfully to heroku develop.

**Comment by diraulo** [comment]
@tansaku you need to add `thomas[at]makersacademy[dot]se` as a collaborator to WSO instance on Heroku. We're using his API key to deploy to Heroku. Unless we update that and use someone else.

**Comment by tansaku** [comment]
thanks @diraulo - have added him - we'll want to get that moved to something else - maybe technical@agileventures.org

**Comment by diraulo** [comment]
@mtc2013 Heroku is now seeing our app as a Nodejs app not rails.

```shell
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
  ...
```

**Pull request merged**
