### PR TITLE
WIP: trying to merge ruby 2.3 into cleanroom

### LINKED ISSUE #806: intermittent js failure?
```
 Scenario: Insert media model rejects badly formatted youtube links                                      # features/documents.feature:170
    Given I am logged in                                                                                  # features/step_definitions/user_steps.rb:19
    And I am using the Mercury Editor to edit document "Guides"                                           # features/step_definitions/mercury_steps.rb:27
    And I am focused on the "document body" within the Mercury Editor                                     # features/step_definitions/contained_search_steps.rb:33
    And I click on the "Insert Media" button within the Mercury Toolbar                                   # features/step_definitions/contained_search_steps.rb:33
    And I fill in "YouTube URL" with "https://www.youtube.io/watch?v=foo" within the Mercury Editor Modal # features/step_definitions/contained_search_steps.rb:33
    And I click "Insert Media" within the Mercury Editor Modal                                            # features/step_definitions/contained_search_steps.rb:33
    Then I should see "is invalid" within the Mercury Modal                                               # features/step_definitions/contained_search_steps.rb:33
      expected to find text "is invalid" in "Insert Media (images and videos)× Images URL Videos YouTube URL Vimeo URL Options Alignment Float Width Height" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:167:in `/^I should( not)? see "([^"]*)"$/'
      ./features/step_definitions/contained_search_steps.rb:41:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/contained_search_steps.rb:41:in `/^(.*) within the (.*)$/'
      features/documents.feature:177:in `Then I should see "is invalid" within the Mercury Modal'
    And the Mercury Editor modal window should be visible                                                 # features/step_definitions/mercury_steps.rb:61
```
Failing Scenarios:
cucumber features/documents.feature:170 # Scenario: Insert media model rejects badly formatted youtube links

### PR DESCRIPTION
**Pull request by tansaku**
fixes #806

### CODE REVIEW

**Comment by tansaku** [comment]
@yggie what setting did you update in semaphore to make an individual PR run against ruby 2.3?

**Comment by yggie** [comment]
@tansaku the Ruby version in the project settings I believe, had to change it project wide and rerun the tests…

**Comment by tansaku** [comment]
@yggie - ah, project wide and then you changed it back?

**Comment by yggie** [comment]
@tansaku yes I had to change it back so it doesn’t affect the other builds :grinning:

**Comment by tansaku** [comment]
makes sense ... frustrating that there isn't a .semaphore that can specify this like .travis does - but really - why don't they all just rely on the Gemfile as the canonical place to get the ruby version from ...?

**Comment by yggie** [comment]
that would make all our lives much easier :smile:

**Comment by tansaku** [comment]
@yggie I posted an issue to travis: https://github.com/travis-ci/travis-ci/issues/5890 although maybe that's a non-issue for them - I also posted to semaphore by their page chat:

> I was just thinking, rather than setting the ruby version in the project settings through the website interface, wouldn't it be much more convenient if the ruby version could just be taken from where it is specified in the Gemfile?

I note that those in-page chat support things are pretty cool - really lowers the bar to giving feedback on the system - is that a customer.io feature I wonder ...

**Comment by yggie** [comment]
@tansaku in-page support is cool, I believe there are other third-party providers for these kinds of services, I have used https://usabilla.com/ at work, not sure what their arrangements would be for charitable organisations though…

**Pull request closed without merging**
