### PR TITLE
Instructions to solve signup issues

### PR DESCRIPTION
**Pull request by nitishmadhukar**
Doc contains instructions to solve various signup issues
Currently has solutions for github public email

### CODE REVIEW

**Comment by tansaku** [comment]
thanks @nitishmadhukar - good idea - we should also link this into docs homepage so that it can be discovered by navigation

**Comment by nitishmadhukar** [comment]
@tansaku: My thought is once this doc is up in the master branch, we can link any user to this page when they are displayed with the Public Email error message after signup

**Comment by tansaku** [comment]
@nitishmadhukar yes, that's a great idea - I was just thinking that we should also link to it from this page:

https://github.com/AgileVentures/WebsiteOne/blob/develop/docs/README.md

Which is an overview of what documentation is available, and you could include an update to that in this pull request ...

**Comment by nitishmadhukar** [comment]
@tansaku updated README.md

**Pull request merged**
