### PR TITLE
1076 investigate test coverage

### LINKED ISSUE #1076: Investigate test coverage
is our test coverage relying entirely on rspecs, or are they connected to the features?

I think it might be more practical if feature coverage was included ... 

We should at least be clear what our test coverage is set up for

### PR DESCRIPTION
**Pull request by diraulo**
#### Description

Update test coverage configuration to merge results from both RSpec and Cucumber.
#### Motivation and Context

The previous setup only takes into account the coverage generated by Rspec. These changes will now combine them to Cucumber's coverage report. The goal here is to improve the overall coverage report given that some aspect might be covered by our acceptance tests and not by unit tests.

This PR introduce a new rake task (`rake ci:tests`) that runs both `rspec`, `cucumber` then pushes merged results to coveralls.

The build configuration on semaphore will have to be modified to make use of this new rake task.

Fixes #1076 
#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
#### Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tansaku** [comment]
great to see you working on this @diraulo !

**Comment by tansaku** [comment]
@diraulo how's this going?  should we close and throw back to the backlog to allow someone else to continue? could we break it up?  let's work out a way forward.

BTW, happy new year!

**Comment by diraulo** [comment]
@tansaku Will push the lastest I have on this today

**Comment by diraulo** [comment]
@tansaku Once this is merged, The build config on semaphore should change from 2 parallel builds to a single one.

1. Delete **Cucumber** job
2. Update **RSpect + JasmineCI** to execute the following commands (Rename job to **All Tests**)

```
COVERALLS_REPO_TOKEN=vdG0Rhky8q0JTYXIsQZd7Xdb1ObAN1CkW bundle exec rake ci:tests
bundle exec rake jasmine:ci
cat cucumber_report.json
```

**Comment by tansaku** [comment]
@diraulo looks like this needs rebuilding - what's the temporary change we need on semaphore to make this pass?

**Comment by diraulo** [comment]
@tansaku I just restarted the build with the right settings

**Comment by tansaku** [comment]
@diraulo thanks - looks like we need update branch - maybe share those settings?

**Comment by diraulo** [comment]
@tansaku I just do the steps I described in my previous comment. I apply the **new** configs start the tests and revert back to previous configs while it builds my PR.

I'll update the PR and run the build again.. Takes me less time to do so, since I'm used to it now 😉

**Comment by tansaku** [comment]
thanks @diraulo :-)

**Comment by tansaku** [comment]
I'm going to merge before you have to do it again :-)

**Pull request merged**
