### PR TITLE
[WIP][docker]gems version checking and updating

### PR DESCRIPTION
**Pull request by dkuku**
Currently to update the Gemfile we need to rebuild the whole docker image
#### Description

Implement separate image for gems using this [tutorial](https://medium.com/@jfroom/docker-compose-3-bundler-caching-in-dev-9ca1e49ac441)

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dkuku** [comment]
If someone could test it - works at my machine (linux)
Thats the output when added overcommit to Gemfile

```
 ✘ kuku@dku-xps  ~/Projects/WebsiteOne   2718_improve_our_seed_file ●  ./docker/start.sh
Removing websiteone_web_1 ... done
Removing websiteone_db_1  ... done
Removing network websiteone_default
Creating network "websiteone_default" with the default driver
Creating websiteone_db_1 ... done
Creating websiteone_web_1 ... done
Attaching to websiteone_db_1, websiteone_web_1
db_1   | 2018-10-18 02:14:32.957 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2018-10-18 02:14:32.957 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2018-10-18 02:14:32.975 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2018-10-18 02:14:33.038 UTC [24] LOG:  database system was interrupted; last known up at 2018-10-18 02:13:55 UTC
db_1   | 2018-10-18 02:14:33.593 UTC [24] LOG:  database system was not properly shut down; automatic recovery in progress
db_1   | 2018-10-18 02:14:33.600 UTC [24] LOG:  redo starts at 0/469ED60
db_1   | 2018-10-18 02:14:33.600 UTC [24] LOG:  invalid record length at 0/46A0790: wanted 24, got 0
db_1   | 2018-10-18 02:14:33.600 UTC [24] LOG:  redo done at 0/46A0768
db_1   | 2018-10-18 02:14:33.600 UTC [24] LOG:  last completed transaction was at log time 2018-10-18 02:14:11.521792+00
db_1   | 2018-10-18 02:14:33.675 UTC [1] LOG:  database system is ready to accept connections
web_1  | Bundler can't satisfy your Gemfile's dependencies.
web_1  | Install missing gems with `bundle install`.
web_1  | Fetching gem metadata from https://rubygems.org/............
web_1  | Fetching gem metadata from https://rubygems.org/..
web_1  | Resolving dependencies.........
web_1  | Using rake 12.3.1
web_1  | Using concurrent-ruby 1.0.5
web_1  | Using i18n 1.1.0
web_1  | Using minitest 5.11.3
web_1  | Using thread_safe 0.3.6
web_1  | Using tzinfo 1.2.5
web_1  | Using activesupport 5.1.6
web_1  | Using builder 3.2.3
web_1  | Using erubi 1.7.1
web_1  | Using mini_portile2 2.3.0
web_1  | Using nokogiri 1.8.4
web_1  | Using rails-dom-testing 2.0.3
web_1  | Using crass 1.0.4
web_1  | Using loofah 2.2.2
web_1  | Using rails-html-sanitizer 1.0.4
web_1  | Using actionview 5.1.6
web_1  | Using rack 2.0.5
web_1  | Using rack-test 1.1.0
web_1  | Using actionpack 5.1.6
web_1  | Using nio4r 2.3.1
web_1  | Using websocket-extensions 0.1.3
web_1  | Using websocket-driver 0.6.5
web_1  | Using actioncable 5.1.6
web_1  | Using globalid 0.4.1
web_1  | Using activejob 5.1.6
web_1  | Using mini_mime 1.0.0
web_1  | Using mail 2.7.0
web_1  | Using actionmailer 5.1.6
web_1  | Using activemodel 5.1.6
web_1  | Using arel 8.0.0
web_1  | Using activerecord 5.1.6
web_1  | Using acts-as-taggable-on 6.0.0
web_1  | Using acts_as_follower 0.2.1 from https://github.com/AgileVentures/acts_as_follower.git (at master@894b444)
web_1  | Using acts_as_tree 2.8.0
web_1  | Using acts_as_votable 0.11.1
web_1  | Using public_suffix 3.0.3
web_1  | Using addressable 2.5.2
web_1  | Using airbrake-ruby 2.11.0
web_1  | Using airbrake 7.3.5
web_1  | Using andand 1.3.3
web_1  | Using bundler 1.16.6
web_1  | Using method_source 0.9.0
web_1  | Using thor 0.20.0
web_1  | Using railties 5.1.6
web_1  | Using sprockets 3.7.2
web_1  | Using sprockets-rails 3.2.1
web_1  | Using rails 5.1.6
web_1  | Using apipie-rails 0.5.10
web_1  | Using ast 2.4.0
web_1  | Using execjs 2.7.0
web_1  | Using autoprefixer-rails 8.1.0
web_1  | Using awesome_print 1.8.0
web_1  | Using bcrypt 3.1.12
web_1  | Using coderay 1.1.2
web_1  | Using better_errors 2.5.0
web_1  | Using debug_inspector 0.0.3
web_1  | Using binding_of_caller 0.8.0
web_1  | Using sass 3.4.25
web_1  | Using bootstrap-sass 3.3.7
web_1  | Using brakeman 4.3.1
web_1  | Using uniform_notifier 1.11.0
web_1  | Using bullet 5.7.6
web_1  | Using bundler-audit 0.6.0
web_1  | Using business_time 0.9.3
web_1  | Using byebug 10.0.0
web_1  | Using xpath 3.0.0
web_1  | Using capybara 2.18.0
web_1  | Using launchy 2.4.3
web_1  | Using capybara-screenshot 1.0.21
web_1  | Using ffi 1.9.25
web_1  | Using childprocess 0.9.0
web_1  | Using rubyzip 1.2.2
web_1  | Using selenium-webdriver 3.14.0
web_1  | Using capybara-selenium 0.0.6
web_1  | Using chronic 0.10.2
web_1  | Using chunky_png 1.3.10
web_1  | Using cliver 0.3.2
web_1  | Using cocoon 1.2.11
web_1  | Using multi_xml 0.6.0
web_1  | Using httparty 0.16.0
web_1  | Using code_climate_badges 0.0.0 from https://github.com/AgileVentures/codeclimate_badges (at master@88f15df)
web_1  | Using coffee-script-source 1.12.2
web_1  | Using coffee-script 2.4.1
web_1  | Using coffee-rails 4.2.2
web_1  | Using colored 1.2
web_1  | Using multi_json 1.13.1
web_1  | Using compass-core 1.0.3
web_1  | Using compass-import-once 1.0.5
web_1  | Using rb-fsevent 0.10.3
web_1  | Using rb-inotify 0.9.10
web_1  | Using compass 1.0.3
web_1  | Using tilt 2.0.8
web_1  | Using sass-rails 5.0.7
web_1  | Using compass-rails 3.1.0
web_1  | Using deep_merge 1.2.1
web_1  | Using dry-configurable 0.7.0
web_1  | Using dry-core 0.4.4
web_1  | Using dry-equalizer 0.2.0
web_1  | Using dry-container 0.6.0
web_1  | Using dry-logic 0.4.2
web_1  | Using inflecto 0.0.2
web_1  | Using dry-types 0.12.2
web_1  | Using dry-validation 0.11.1
web_1  | Using config 1.7.0
web_1  | Using constant-redefinition 1.1.0
web_1  | Using cookiejar 0.3.3
web_1  | Using safe_yaml 1.0.4
web_1  | Using crack 0.4.3
web_1  | Using gherkin 4.1.3
web_1  | Using cucumber-core 1.5.0
web_1  | Using cucumber-wire 0.0.1
web_1  | Using diff-lcs 1.3
web_1  | Using multi_test 0.1.2
web_1  | Using cucumber 2.99.0
web_1  | Using mime-types 2.99.3
web_1  | Using cucumber-rails 1.5.0
web_1  | Using dante 0.2.0
web_1  | Using database_cleaner 1.7.0
web_1  | Using delorean 2.1.0
web_1  | Using orm_adapter 0.5.0
web_1  | Using responders 2.4.0
web_1  | Using warden 1.2.7
web_1  | Using devise 4.5.0
web_1  | Using docile 1.3.0
web_1  | Using unf_ext 0.0.7.5
web_1  | Using unf 0.1.4
web_1  | Using domain_name 0.5.20170404
web_1  | Using dotenv 2.5.0
web_1  | Using dotenv-rails 2.5.0
web_1  | Using eventmachine 1.0.9.1
web_1  | Using em-socksify 0.3.2
web_1  | Using http_parser.rb 0.6.0
web_1  | Using em-http-request 1.1.5
web_1  | Using em-synchrony 1.0.6
web_1  | Using em-websocket 0.5.1
web_1  | Using eventmachine_httpserver 0.2.1
web_1  | Using exception_notification 4.2.2
web_1  | Using factory_bot 4.11.1
web_1  | Using factory_bot_rails 4.11.1
web_1  | Using faker 1.9.1
web_1  | Using multipart-post 2.0.0
web_1  | Using faraday 0.12.2
web_1  | Using faraday_middleware 0.12.2
web_1  | Using font-awesome-rails 4.7.0.4
web_1  | Using formatador 0.2.5
web_1  | Using friendly_id 5.2.4
web_1  | Using geocoder 1.5.0
web_1  | Using gli 2.18.0
web_1  | Using ruby_dep 1.5.0
web_1  | Using listen 3.1.5
web_1  | Using lumberjack 1.0.12
web_1  | Using nenv 0.3.0
web_1  | Using shellany 0.0.1
web_1  | Using notiffany 0.1.1
web_1  | Using pry 0.11.3
web_1  | Using guard 2.14.2
web_1  | Using guard-compat 1.2.1
web_1  | Using guard-cucumber 2.1.2
web_1  | Using guard-livereload 2.5.2
web_1  | Using rspec-support 3.8.0
web_1  | Using rspec-core 3.8.0
web_1  | Using rspec-expectations 3.8.0
web_1  | Using rspec-mocks 3.8.0
web_1  | Using rspec 3.8.0
web_1  | Using guard-rspec 4.7.3
web_1  | Using hashdiff 0.3.7
web_1  | Using hashie 3.5.7
web_1  | Using hirb 0.7.3
web_1  | Using http-cookie 1.0.3
web_1  | Using ice_cube 0.16.3
web_1  | Fetching iniparse 1.4.4
web_1  | Installing iniparse 1.4.4
web_1  | Using jaro_winkler 1.5.1
web_1  | Using jasmine-core 3.2.0
web_1  | Using phantomjs 2.1.1.0
web_1  | Using jasmine 3.2.0
web_1  | Using jasmine-jquery-rails 2.0.3
web_1  | Using jbuilder 2.7.0
web_1  | Using jquery-rails 4.3.3
web_1  | Using turbolinks-source 5.2.0
web_1  | Using turbolinks 5.2.0
web_1  | Using jquery-turbolinks 2.1.0
web_1  | Using json 1.8.6
web_1  | Using jvectormap-rails 2.0.0
web_1  | Using jwt 1.5.6
web_1  | Using kaminari-core 1.1.1
web_1  | Using kaminari-actionview 1.1.1
web_1  | Using kaminari-activerecord 1.1.1
web_1  | Using kaminari 1.1.1
web_1  | Using kdtree 0.4
web_1  | Using kramdown 1.17.0
web_1  | Using letter_opener 1.6.0
web_1  | Using libv8 3.16.14.19 (x86_64-linux)
web_1  | Using local_time 2.1.0
web_1  | Using mercury-rails 0.9.0 from https://github.com/AgileVentures/mercury.git (at master@9d7d7f1)
web_1  | Using require_all 1.5.0
web_1  | Using nearest_time_zone 0.0.4
web_1  | Using netrc 0.11.0
web_1  | Using newrelic_rpm 5.4.0.347
web_1  | Using oauth2 1.4.0
web_1  | Using sawyer 0.8.1
web_1  | Using octokit 4.12.0
web_1  | Using omniauth 1.8.1
web_1  | Using omniauth-oauth2 1.3.1
web_1  | Using omniauth-github 1.1.2
web_1  | Using omniauth-google-oauth2 0.5.2
web_1  | Fetching overcommit 0.46.0
web_1  | Installing overcommit 0.46.0
web_1  | Using request_store 1.4.1
web_1  | Using paper_trail 10.0.1
web_1  | Using parallel 1.12.1
web_1  | Using paranoia 2.4.1
web_1  | Using parser 2.5.1.2
web_1  | Using pg 1.1.3
web_1  | Using rest-client 1.8.0
web_1  | Using pivotal-tracker-api 1.0.3 from https://github.com/atljeremy/pivotal-tracker-api.git (at master@163a4de)
web_1  | Using poltergeist 1.18.1
web_1  | Using polyamorous 1.3.3
web_1  | Using powerpack 0.1.2
web_1  | Using pry-byebug 3.6.0
web_1  | Using pry-rails 0.3.6
web_1  | Using public_activity 1.6.2
web_1  | Using puffing-billy 1.1.2
web_1  | Using puma 3.12.0
web_1  | Using rack-cache 1.8.0
web_1  | Using rack-timeout 0.5.1
web_1  | Using railroady 1.5.3
web_1  | Using rails-controller-testing 1.0.2
web_1  | Using rails_serve_static_assets 0.0.5
web_1  | Using rails_stdout_logging 0.0.5
web_1  | Using rails_12factor 0.0.3
web_1  | Using rails_autolink 1.1.6
web_1  | Using rainbow 3.0.0
web_1  | Using recaptcha 4.12.0
web_1  | Using redcarpet 3.4.0
web_1  | Using ref 2.0.0
web_1  | Using rspec-activemodel-mocks 1.1.0
web_1  | Using rspec-html-matchers 0.9.1
web_1  | Using rspec-rails 3.8.0
web_1  | Using ruby-progressbar 1.10.0
web_1  | Using unicode-display_width 1.4.0
web_1  | Using rubocop 0.58.2
web_1  | Using rubocop-rspec 1.29.1
web_1  | Using ruby-gitter 0.1.0
web_1  | Using shoulda-matchers 3.1.2
web_1  | Using simple_form 4.0.1
web_1  | Using simplecov-html 0.10.2
web_1  | Using simplecov 0.16.1
web_1  | Using slack-ruby-client 0.13.1
web_1  | Using stripe 3.28.0
web_1  | Using stripe-ruby-mock 2.5.5
web_1  | Using sucker_punch 2.1.1
web_1  | Using therubyracer 0.12.3
web_1  | Using uglifier 4.1.19
web_1  | Using utf8-cleaner 0.2.5
web_1  | Using vanity 2.2.10
web_1  | Using vcr 4.0.0
web_1  | Using verbs 2.1.4
web_1  | Using webmock 3.4.2
web_1  | Using webrat 0.7.3
web_1  | Using will_paginate 3.1.6
web_1  | Using will_paginate-bootstrap 1.0.1
web_1  | Using youtube_rails 1.2.2
web_1  | Using yt-support 0.1.3
web_1  | Using yt 0.32.2
web_1  | Using yui-compressor 0.12.0
web_1  | Using zeus 0.15.14
web_1  | Bundle complete! 116 Gemfile dependencies, 265 gems now installed.
web_1  | Bundled gems are installed into `/bundle`
web_1  | Post-install message from overcommit:
web_1  | Install hooks by running `overcommit --install` in your Git repository
web_1  | => Booting Puma
web_1  | => Rails 5.1.6 application starting in development
web_1  | => Run `rails server -h` for more startup options
web_1  | [1] Puma starting in cluster mode...
web_1  | [1] * Version 3.12.0 (ruby 2.5.1-p57), codename: Llamas in Pajamas
web_1  | [1] * Min threads: 1, max threads: 16
web_1  | [1] * Environment: development
web_1  | [1] * Process workers: 3
web_1  | [1] * Preloading application
web_1  | [1] * Listening on tcp://0.0.0.0:3000
web_1  | [1] Use Ctrl-C to stop
web_1  | W, [2018-10-18T02:15:06.804885 #1]  WARN -- : No default alternative specified; choosing text_trail as default.
web_1  |   Vanity::Adapters::ActiveRecordAdapter::VanityExperiment Load (0.7ms)  SELECT  "vanity_experiments".* FROM "vanity_experiments" WHERE "vanity_experiments"."experiment_id" = $1 LIMIT $2  [["experiment_id", "landing_page_options"]
```

**Comment by tansaku** [comment]
this sounds great @dkuku - I'm not using docker, so maybe @mattwr18 can review this

**Comment by mattwr18** [comment]
@dkuku Really cool!!! This is such a cool feature that makes developing locally using docker much more enjoyable... have you seen this @roschaefer?

**Comment by tansaku** [comment]
@mattwr18 if you think this is ready to merge, let's get it in :-)

**Comment by roschaefer** [comment]
@dkuku nice! What is the equivalent for `yarn` or `npm`?

**Pull request merged**
