### PR TITLE
[WIP] Update to rails 5

### LINKED ISSUE #1737: Update to Rails 5
Update to latest Rails5, currently 5.1.2: http://weblog.rubyonrails.org/2017/6/26/Rails-5-1-2-has-been-released/.

### PR DESCRIPTION
**Pull request by mattlindsey**
fixes #1737

### CODE REVIEW

**Comment by tansaku** [comment]
might want to stick to ruby 2.3.1 to play well with CI ...

**Comment by tansaku** [comment]
@mattlindsey I just started playing with this and getting into longer and longer dependency chains like 

```
bundle update rails activemodel active_model-errors_details devise mercury-rails public_activity sass-rails

Warning: the running version of Bundler (1.14.6) is older than the version that created the lockfile (1.15.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching https://github.com/jejacks0n/mercury.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    mercury-rails was resolved to 0.9.0, which depends on
      coffee-rails (>= 3.2.2) was resolved to 4.2.2, which depends on
        railties (>= 4.0.0)

    cucumber-rails was resolved to 1.4.5, which depends on
      railties (< 5.1, >= 3)

    devise was resolved to 4.3.0, which depends on
      railties (< 5.2, >= 4.1.0)

    font-awesome-rails was resolved to 4.7.0.2, which depends on
      railties (< 5.2, >= 3.2)

    jquery-rails was resolved to 4.3.1, which depends on
      railties (>= 4.2.0)

    mercury-rails was resolved to 0.9.0, which depends on
      railties (>= 3.0)

    public_activity was resolved to 1.5.0, which depends on
      railties (>= 3.0.0)

    public_activity was resolved to 1.5.0, which depends on
      railties (>= 3.0.0)

    rails (= 5.1.2) was resolved to 5.1.2, which depends on
      railties (= 5.1.2)

    devise was resolved to 4.3.0, which depends on
      responders was resolved to 2.4.0, which depends on
        railties (< 5.3, >= 4.2.0)

    sass-rails was resolved to 5.0.6, which depends on
      railties (< 6, >= 4.0.0)
```

**Comment by tansaku** [comment]
even deleting Gemfile.lock I get:

```
[tansaku@Samuels-MBP:~/Documents/Github/AgileVentures/WebsiteOne (1737_rails_5)]$ 
→ rm Gemfile.lock 
[tansaku@Samuels-MBP:~/Documents/Github/AgileVentures/WebsiteOne (1737_rails_5)]$ 
→ bundle
Fetching https://github.com/AgileVentures/codeclimate_badges
Fetching https://github.com/jejacks0n/mercury.git
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.......
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    mercury-rails was resolved to 0.9.0, which depends on
      coffee-rails (>= 3.2.2) was resolved to 4.2.2, which depends on
        railties (>= 4.0.0)

    cucumber-rails was resolved to 1.5.0, which depends on
      railties (< 5.2, >= 4)

    devise was resolved to 4.3.0, which depends on
      railties (< 5.2, >= 4.1.0)

    factory_girl_rails (= 4.5.0) was resolved to 4.5.0, which depends on
      railties (>= 3.0.0)

    factory_girl_rails (= 4.5.0) was resolved to 4.5.0, which depends on
      railties (>= 3.0.0)

    jquery-rails was resolved to 4.3.1, which depends on
      railties (>= 4.2.0)

    jquery-turbolinks (= 2.0.2) was resolved to 2.0.2, which depends on
      railties (>= 3.1.0)

    jvectormap-rails (= 1.0.1) was resolved to 1.0.1, which depends on
      railties (< 5.0, >= 3.1)

    mercury-rails was resolved to 0.9.0, which depends on
      railties (>= 3.0)

    mercury-rails was resolved to 0.9.0, which depends on
      railties (>= 3.0)

    rails (= 5.1.2) was resolved to 5.1.2, which depends on
      railties (= 5.1.2)

    sass-rails was resolved to 5.0.6, which depends on
      railties (< 6, >= 4.0.0)

```

**Comment by tansaku** [comment]
looks like `jvectormap-rails` is the block - if we can remove that and replace with something we could move forward maybe ...

**Comment by tansaku** [comment]
looks like jvectormap-rails is our world map of AV members - it's an asset pipeline gem bundle for http://jvectormap.com/

**Comment by tansaku** [comment]
can maybe pull in directly or possible switch to https://github.com/acrogenesis/jqvmap-rails

**Comment by mattlindsey** [comment]
@tansaku Reverted back to ruby 2.3.1 and replaced jqvmap-rails gem with jvectormap-rails gem. 
Looking better.

Problem now seems to be mostly with active_model-errors_details:
```
In Gemfile:
    active_model-errors_details was resolved to 1.0.0, which depends on
      activemodel (< 5.0.0.alpha, >= 4.0)
```

**Comment by mattlindsey** [comment]
@tansaku Bundle install now working by removing mercury and active_model-errors_details gems.

So i think now we can proceed to looking at where the tests are failing and try to fix.

**Comment by tansaku** [comment]
@mattlindsey - my experiments suggested we could keep mercury if we just dropped vector rails - and maybe we should start with 5.0.0 rather than 5.1.2 ...

**Comment by mattlindsey** [comment]
@tansaku I added back mercury, and indeed bundle install still works.
Can you explain how going back to Rails 5.0.0 might help?

**Comment by tansaku** [comment]
@mattlindsey as we discussed in scrum I thought rails 5.0.0 might be easier, but seems not :-/

**Pull request closed without merging**
