### PR TITLE
749 rspec junk

### LINKED ISSUE #749: junk in the rspec log
Would like to get this all cleaned out:

```
$ bundle exec rspec -fp

Randomized with seed 43332
..................................................................................................-- add_column(:events, :start_time, :time)
   -> 0.0253s
-- add_column(:events, :event_date, :date)
   -> 0.0008s
-- add_column(:events, :end_time, :time)
   -> 0.0019s
-- remove_column(:events, :start_datetime, :datetime)
   -> 0.0053s
-- remove_column(:events, :duration, :integer)
   -> 0.0003s
.-- add_column(:events, :start_time, :time)
   -> 0.0005s
-- add_column(:events, :event_date, :date)
   -> 0.0003s
-- add_column(:events, :end_time, :time)
   -> 0.0003s
-- remove_column(:events, :start_datetime, :datetime)
   -> 0.0004s
-- remove_column(:events, :duration, :integer)
   -> 0.0003s
-- add_column(:events, :start_datetime, :datetime)
   -> 0.0005s
-- add_index(:events, :start_datetime)
   -> 0.0202s
-- add_column(:events, :duration, :integer)
   -> 0.0008s
-- remove_column(:events, :start_time, :time)
   -> 0.0004s
-- remove_column(:events, :event_date, :date)
   -> 0.0003s
-- remove_column(:events, :end_time, :time)
   -> 0.0003s
............................................................................................../Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:24: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/app/models/newsletter.rb:15: warning: previous definition of CHUNK_SIZE was here
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:25: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/app/models/newsletter.rb:14: warning: previous definition of SEND_AS was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:24: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:24: warning: previous definition of CHUNK_SIZE was here
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:25: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:25: warning: previous definition of SEND_AS was here
..../Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:25: warning: previous definition of SEND_AS was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: previous definition of SEND_AS was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: previous definition of SEND_AS was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:46: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:24: warning: previous definition of CHUNK_SIZE was here
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:47: warning: already initialized constant Newsletter::SEND_AS
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:42: warning: previous definition of SEND_AS was here
........*.....................................................................................The user session path is /users/sign_in
.The user session path is /users/sign_in
.The user session path is /users/sign_in
.The user session path is /users/sign_in
.The user session path is /users/sign_in
...............................................................................Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Andres Grimes stats are okay
Tommie Terry stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Tommie Terry stats are okay
Andres Grimes stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Domenick Feest stats are okay
Mohamed Toy stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Mohamed Toy stats are okay
Domenick Feest stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Alene Ankunding stats are okay
Liam Kassulke stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Liam Kassulke stats are okay
Alene Ankunding stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Charles Tillman stats are okay
Jocelyn Huel stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Jocelyn Huel stats are okay
Charles Tillman stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Emiliano Leannon stats are okay
Chandler Corkery stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Chandler Corkery stats are okay
Emiliano Leannon stats are okay
.Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Jeanette Hills stats are okay
Adalberto Daniel stats are okay
Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Adalberto Daniel stats are okay
Jeanette Hills stats are okay
................................................................................................................................../Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/models/newsletter_spec.rb:46: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
./Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:14: warning: already initialized constant Newsletter::CHUNK_SIZE
/Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/jobs/send_newsletter_spec.rb:7: warning: previous definition of CHUNK_SIZE was here
...............................invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
...............................................................................................................................................................................An expectation of :includes was set on nil. Called from /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/controllers/projects_controller_spec.rb:46:in `block (3 levels) in <top (required)>'. Use allow_message_expectations_on_nil to disable warnings.
................................................................................................................

Pending: (Failures listed here are expected and do not affect your suite's status)

  1) events/new user is not signed in should redirect to sign in and render a flash error
     # Temporarily skipped with xit
     # ./spec/views/events/new.html.erb_spec.rb:18


Deprecation Warnings:

Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/routing/newsletters_routing_spec.rb:22:in `block (3 levels) in <top (required)>'.

Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/spec/views/static_page/show.html.erb_spec.rb:24:in `block (2 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.

2 deprecation warnings total

Finished in 1 minute 28.77 seconds (files took 10.27 seconds to load)
836 examples, 0 failures, 1 pending

```

### PR DESCRIPTION
**Pull request by freeranger**
Closes #749

### CODE REVIEW

**Comment by freeranger** [comment]
@tansaku - can you take a look at this: https://semaphoreci.com/freeranger/websiteone/branches/749_rspec_junk/builds/6, at the "bundle exec rake spec" output 
Apart from the two deprecation warnings:

`Using `should_not` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /home/runner/WebsiteOne/spec/requests/assets_spec.rb:7:in `block (2 levels) in <top (required)>'.

Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` instead. Called from /home/runner/WebsiteOne/spec/controllers/authentications_controller_spec.rb:64:in `block (3 levels) in <top (required)>'.
`

is there anything else left that you want to get rid of?

**Comment by tansaku** [comment]
@freeranger - the way to see the things we need to clean out is anything that appears when you run like this:

```
bundle exec rspec -fp
```

that formats the output so none of the spec descriptions come out, just a dot for each test.  Then pretty much any text that gets displayed is junk that can be confusing and get in the way.

I tend to run my tests like this all the time, as I think that they run slightly faster like that, and it's not practical to read all that text anyway.  I have the following aliases set up to help me with that:

```
alias be="bundle exec"
alias ber="bundle exec rspec -fp"
alias bec="bundle exec cucumber --format progress"
```

**Comment by freeranger** [comment]
@tansaku I changed my build to do ```bundle exec rspec -fp``` but it didn't seem to make a difference to the output semaphore captures:
https://semaphoreci.com/freeranger/websiteone/branches/749_rspec_junk/builds/7
Thanks for the handy shortcuts though!

**Comment by tansaku** [comment]
Yeah that will have no impact on semaphore, but that's not so much the point - we're not particularly trying to affect the semaphore output, as clean up any stray output, whether that's on developers machines or in semaphore.

You don't particularly need to be referring to semaphore to see what to clean up.  Just run `bundle exec rspec -fp` locally and see what's there that shouldn't be.

If I were doing this task I don't think I'd be referring to the semaphore logs at all

**Comment by freeranger** [comment]
The only reason I was updating the semaphore build was to show you what was left! :-)
Locally I am doing the -fp thing anyway.

I can't see a way to get rid of things like messages like this:
```Randomized with seed 15094```
or 
```Coverage report generated for RSpec to /home/runner/WebsiteOne/coverage. 1445 / 1548 LOC (93.35%) covered.```
which are part of the rspec output.
Do they matter?

**Comment by tansaku** [comment]
the semaphore build updates automatically - sorry - it's just difficult for me to see the changes there - no need to point me to it.  It's easier for me to see the changes if I pull down your branch and run ber locally - those other two messages you mention are rspec and coveralls and there's no need to suppress them.  They're standard output from other gems (rspec and coveralls).

We just want to clean up anything that's output from our code (and deprecation warnings etc.).  I can review this on my own machine later, but if that's all you've got left on an fp run then you're doing great!

**Comment by freeranger** [comment]
Hold your horses there sonny - that's not *all* I've got left - I'm still working through a boat load of conversion from foo.should to expect(foo).to but I think that's the final task if the remaining output is ok.
I'll report back when I think I'm done and then you can pull down and review - I'd hoped the semaphore output would be a shortcut to seeing what's left but it's too smart for it's own good :}

**Comment by tansaku** [comment]
:-)

One note on all this is that if there are many many issues the PR could get unwieldy - you might want to split them out into separate issues, each with their own PR to fix individual issue, so they can be reviewed (and deployed) separately.

That reduces the chance of getting overwhelmed by interaction effects ...

**Comment by freeranger** [comment]
Ok I think I have a couple of local commits to check in for more small changes - why don't I check them in and then the one big commit would be for converting should to expect.to, which I will create a separate issue for?  Someone still has to review the beast though...unless you want a gazillion issues, one per .rb file I change?

**Comment by tansaku** [comment]
sure thing - although that separate expect to issue could also be broken down into sub issues where different sets of tests might be reviewed.

I'm also thinking we should delete all view specs and controller specs that have significant stubbing in them ...

**Comment by freeranger** [comment]
The danger of the former is that it takes more time to create a boat load of stories and integrate all the PR's than it would take for the code review, which will be pretty simple checks that should is now expect and the tests still pass...

The latter is scope creep and should definitely be a different issue and you need to define "significant" :)
Also, "significant" stubbing could be a code smell that the code under test should be reviewed and refactored - just removing the tests will hide that...

**Comment by tansaku** [comment]
> it takes more time to create a boat load of stories and integrate all the PR's than it would take for the code review, which will be pretty simple checks that should is now expect and the tests still pass...

not sure I agree, but feel free to use your best judgement

The latter is not scope creep to the extent that if we are about to delete a lot of files it doesn't make sense to burn lots of time refactoring them.  It's scope creep only if you roll it into the same ticket - not it you make other tickets and prioritise them.

The point about excessive stubbing on views and controller specs is that it makes more sense to have acceptance tests exercising that functionality.  In several years on this and related projects I have seen extraordinarily little benefit from excessively stubbed view and controller tests; and huge downsides in terms of maintenance and drag on feature development.   Models and services is a different story.

Either way we of course should avoid getting things rolled into one ticket.  There should be a separate ticket for pruning the specs that might get actioned before a "should --> expect" conversion that might make that latter task considerably less onerous.

**Comment by freeranger** [comment]
Absolutely - I'm a big fan of acceptance tests.  I have no problem writing unit tests to test the components I am writing, then write acceptance tests and whip away some or all of the unit tests which helped me to get there.
It's a much bigger job to review that stuff and ensure there is sufficient coverage (maybe even writing more acceptance tests along the way), which I think you would have to do in separate issues to keep it manageable - whether on per feature or per controller basis
The should ->expect conversion is just nobrainer drudgery for the most part, but I have already done quite a bit of it and am happy to finish it off tbh

**Comment by tansaku** [comment]
well don't let me stop you from finishing the drudgery if you're happy to do it - I just hate to see wasted work - I'm perfectly happy for it to be left and other tickets created that have higher priority, even if you don't happen to work on them personally, but use your best judgement and many thanks for your hard work on all this

**Comment by freeranger** [comment]
@tansaku - Ok I've created https://github.com/AgileVentures/WebsiteOne/issues/855 for the should->expect conversion.
This PR is ready for review and hopefully merge...

**Comment by tansaku** [comment]
thanks @freeranger - I've pulled down your code locally for checks - have you reviewed the site manually as well?

**Comment by tansaku** [comment]
rspec output looks super clean now BTW, great job!

I do get one failure locally:

```
  1) EventsController GET show assigns a event instance
     Failure/Error: expect(assigns(:recent_hangout)).to eq(event_instance)
       
       expected: #<EventInstance id: 100, event_id: 92, title: "Hangout_210", hangout_url: "http://hangout.test", created_at: "2016-03-03 08:05:58", updated_at: "2016-03-03 08:05:58", uid: "uid_224", category: "Category_186", project_id: 211, user_id: 587, yt_video_id: "yt_video_id_209", participants: [["216", {:person=>{:displayName=>"Broadcaster216", :id=>"youtube_id_216", :isBroadcaster=>"true"}}], ["216", {:person=>{:displayName=>"Participant_216", :id=>"youtube_id_216", :isBroadcaster=>"false"}}]], hoa_status: nil>
            got: nil
       
       (compared using ==)
     # ./spec/controllers/events_controller_spec.rb:32:in `block (3 levels) in <top (required)>'
```

interesting as @mtc2013 got this locally yesterday as an intermittent failure ... and I also didn't get it second time around, so this is another one for our #806 issue ...

**Comment by freeranger** [comment]
@tansaku I don't know what you mean about reviewing the site "manually"?
I am not making any application code changes, only test changes
It's all green for me locally and in my rspec build: https://semaphoreci.com/freeranger/websiteone/branches/749_rspec_junk
Could it be a random failure for you and goes away if you try again?

**Comment by tansaku** [comment]
by manually I mean running `rails s` and inspecting the site at localhost:3000, but actually now I reviewed  all the changes here there are only changes to tests so there shouldn't be any impact on how the site runs, although you never know :-) the Gemfile change shouldn't have an impact either ...

regarding that failure - yes - as I said in the comment immediately under the trace of the failure, it went away on the second run - and @mtc2013 had similar intermittent failures with that yesterday - I've added notes to #806 in that regard

**Comment by freeranger** [comment]
Sorry, I missed that little nugget at the end.
So hopefully this is good to go?

**Comment by tansaku** [comment]
yes, although I notice that you have some anonymous github commits in there:

http://stackoverflow.com/questions/8283915/git-author-unknown

That might be something to fix up, or we could take a stab at squashing the commits all down into one, which is something we were discussing in the kickoff yesterday:

https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

I don't want to generate too much additional work on this one for you, and it would be great to get it pulled in soon - so let's take a little time to reflect on both options ...

**Comment by freeranger** [comment]
@tansaku Not sure where you're seeing the anonymous commits?
This is what I see when I look at it:
image

The "freeranger" one is me doing it through github rather than from my mac (and yes I will make it more consistent) but none of them are anonymous??  

I was following the WSO guidelines on commits:

> Please ensure that each commit in your pull request makes a single coherent change and that the overall pull request only includes commits related to the specific GitHub issue that the pull request is addressing. This helps the project managers understand the PRs and merge them more quickly.

So each commit is for a single logical step.   I don't mind the additional work if I'm learning from it and doing it the preferred way.
So what do I need to do exactly to make this the ideal PR?

**Comment by tansaku** [comment]
oh sorry - not anonymous - just the icon is missing and although it says Tony Butler it's not linking to your github profile on most of them, possibly you have your name (but not your github email) set on your local machine

And you've followed the instructions to the letter so it's all good.  Squashing the commits is something we could get into if you are interested, or I could do for you.  As I said we were discussing in kick off if we wanted to do more of that in WSO.  Let's leave to reflect for a while ...

**Comment by freeranger** [comment]
Ok I'll have to check it out when I get home and can charge my laptop again :}
I'm interested in anything that improves the workflow experience.
If squashing is the way to go then happy to go through what you want done (is this something that happens to my local repo or my github repo?)
I can see value in both - keeping the separate logical commits means you could cherry pick the bits you want to keep..but at the same time the PR itself could be deemed one big logical commit and you don't want the repo to have the noise of all the intermediate commits.
I'm easy either way....

**Comment by tansaku** [comment]
some related reading: http://jamescooke.info/git-to-squash-or-not-to-squash.html

**Comment by tansaku** [comment]
even more reading: http://programmers.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests

**Comment by freeranger** [comment]
Ok that's doing my head in a little - I think I need to practice it rather than just read about it...
Do you want this as one single squashed commit or a couple of squashed commits?
Am I right in thinking I would need to:
- do all the squashing on my local repo branch
- push to a *new* branch on github
- submit a new PR for this new branch
- close this existing PR
- Delete the existing branches both local and on github?

**Comment by tansaku** [comment]
no new branch or PR required - can all be done here, but .... let's just not do anything for 24 hours ... I think we need to reflect on whether we want to be squashing or not.  Let's let this PR sit and allow some time for @diraulo and others to comment (if they want).

If we do decide to squash I will personally help you through the process :-)

**Comment by freeranger** [comment]
Sounds like a plan, stan :)

**Comment by diraulo** [comment]
@tansaku I'd be happy to have a go at squashing the commits on this in a PP session. I tried on my own PR not sure what I'm missing. Not getting the results I'm expecting when doing interactive rebasing :/

**Comment by diraulo** [comment]
@tansaku @freeranger are we merging this in like this or you want to have a go at squashing the commits?

**Comment by tansaku** [comment]
I think let's merge this as is  - do you want to get the other changes in develop onto staging first @diraulo so we don't end up with too much going out at once.   We should try and release as often as possible in smaller increments I think ...

**Comment by tansaku** [comment]
aha, I just saw the PR to staging - have merged that, so now I'll merge this ...

**Comment by diraulo** [comment]
:wink:

**Pull request merged**
