### PR TITLE
865 redundant cucumber step definitions

### LINKED ISSUE #865: redundant cucumber step definitions
I just ran the following which suggests that we have a number of redundant step definitions that could be removed:

```
$ be cucumber -f stepdefs

...


0.0000000 /^I visit sent newsletter$/                                                                     # features/step_definitions/newsletter_steps.rb:7
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should( not)? see Hangouts details section$/                                                # features/step_definitions/hangout_steps.rb:59
  NOT MATCHED BY ANY STEPS
0.0000000 /^save a screenshot of the page at "([^"]*)"$/                                                  # features/step_definitions/basic_steps.rb:272
  NOT MATCHED BY ANY STEPS
0.0000000 /^show me the page$/                                                                            # features/step_definitions/basic_steps.rb:268
  NOT MATCHED BY ANY STEPS
0.0000000 /^the page should include ([^"]*) for ([^"]*)$/                                                 # features/step_definitions/layout_steps.rb:29
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see the tracking code$/                                                              # features/step_definitions/layout_steps.rb:41
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see the editable field "([^"]*)"$/                                                   # features/step_definitions/mercury_steps.rb:31
  NOT MATCHED BY ANY STEPS
0.0000000 /^the hangout button should( not)? be visible$/                                                 # features/step_definitions/hangout_steps.rb:6
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see a list of guides$/                                                               # features/step_definitions/guides_steps.rb:1
  NOT MATCHED BY ANY STEPS
0.0000000 /^the following sub-pages exist:$/                                                              # features/step_definitions/pages_steps.rb:43
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should( not)? see buttons:$/                                                                # features/step_definitions/basic_steps.rb:221
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should( not)? see field "([^"]*)"$/                                                         # features/step_definitions/basic_steps.rb:213
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see column "([^"]*)"$/                                                               # features/step_definitions/projects_steps.rb:5
  NOT MATCHED BY ANY STEPS
0.0000000 /^There are projects in the database$/                                                          # features/step_definitions/projects_steps.rb:11
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see a form for "([^"]*)"$/                                                           # features/step_definitions/projects_steps.rb:32
  NOT MATCHED BY ANY STEPS
0.0000000 /^I am redirected to the "([^"]*)" page$/                                                       # features/step_definitions/basic_steps.rb:166
  NOT MATCHED BY ANY STEPS
0.0000000 /^I click the "([^"]*)" button for project "([^"]*)"$/                                          # features/step_definitions/projects_steps.rb:43
  NOT MATCHED BY ANY STEPS
0.0000000 /^(.*) in the project members list$/                                                            # features/step_definitions/projects_steps.rb:99
  NOT MATCHED BY ANY STEPS
0.0000000 /^I accept the warning popup$/                                                                  # features/step_definitions/basic_steps.rb:147
  NOT MATCHED BY ANY STEPS
0.0000000 /^following hangouts exist:$/                                                                   # features/step_definitions/event_steps.rb:31
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should be on the password reset page for "(.+)"$/                                           # features/step_definitions/email_steps.rb:27
  NOT MATCHED BY ANY STEPS
0.0000000 /^I go to the next page$/                                                                       # features/step_definitions/projects_steps.rb:105
  NOT MATCHED BY ANY STEPS
0.0000000 /^I click the "([^"]*)" button for document "([^"]*)"$/                                         # features/step_definitions/documents_steps.rb:29
  NOT MATCHED BY ANY STEPS
0.0000000 /^I (?:am on|go to) project "([^"]*)"$/                                                         # features/step_definitions/projects_steps.rb:109
  NOT MATCHED BY ANY STEPS
0.0000000 /^I click the (link|button) "([^"]*)"$/                                                         # features/step_definitions/basic_steps.rb:109
  NOT MATCHED BY ANY STEPS
0.0000000 /^I go to the path "(.*?)"$/                                                                    # features/step_definitions/basic_steps.rb:69
  NOT MATCHED BY ANY STEPS
0.0000000 /^I create a hangout named "([^"]*)"$/                                                          # features/step_definitions/activity_feed_steps.rb:40
  NOT MATCHED BY ANY STEPS
0.0000000 /^I wait up to (\d+) seconds for Disqus comments to load$/                                      # features/step_definitions/disqus_steps.rb:29
  NOT MATCHED BY ANY STEPS
0.0000000 /^I am allowed to edit pitch for project "([^"]*)"$/                                            # features/step_definitions/projects_steps.rb:163
  NOT MATCHED BY ANY STEPS
0.0000000 /^(.*) in Disqus section$/                                                                      # features/step_definitions/disqus_steps.rb:25
  NOT MATCHED BY ANY STEPS
0.0000000 /^Disqus is setup$/                                                                             # features/step_definitions/disqus_steps.rb:1
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see a selector with options$/                                                        # features/step_definitions/basic_steps.rb:281
  NOT MATCHED BY ANY STEPS
0.0000000 /^I play a video$/                                                                              # features/step_definitions/scrums_steps.rb:8
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see a modal$/                                                                        # features/step_definitions/scrums_steps.rb:40
  NOT MATCHED BY ANY STEPS
0.0000000 /^I exist as an unconfirmed user$/                                                              # features/step_definitions/user_steps.rb:33
  NOT MATCHED BY ANY STEPS
0.0000000 /user "([^"]*)" has joined on "([^"]*)"/                                                        # features/step_definitions/user_steps.rb:37
  NOT MATCHED BY ANY STEPS
0.0000000 /^today is "([^"]*)"$/                                                                          # features/step_definitions/user_steps.rb:43
  NOT MATCHED BY ANY STEPS
0.0000000 /^user with a bio$/                                                                             # features/step_definitions/user_steps.rb:48
  NOT MATCHED BY ANY STEPS
0.0000000 /^I edit my account details$/                                                                   # features/step_definitions/user_steps.rb:115
  NOT MATCHED BY ANY STEPS
0.0000000 /^I look at the list of users$/                                                                 # features/step_definitions/user_steps.rb:128
  NOT MATCHED BY ANY STEPS
0.0000000 /^I see an unconfirmed account message$/                                                        # features/step_definitions/user_steps.rb:150
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see an account edited message$/                                                      # features/step_definitions/user_steps.rb:186
  NOT MATCHED BY ANY STEPS
0.0000000 /^following events exist for project "([^"]*)" with active hangouts:$/                          # features/step_definitions/event_steps.rb:16
0.0000000 /^I should (not |)see my gravatar$/                                                             # features/step_definitions/user_steps.rb:200
  NOT MATCHED BY ANY STEPS
0.0000000 /^the sign in form is visible$/                                                                 # features/step_definitions/user_steps.rb:210
  NOT MATCHED BY ANY STEPS
0.0000000 /^my account should be deleted$/                                                                # features/step_definitions/user_steps.rb:216
  NOT MATCHED BY ANY STEPS
0.0000000 /^The database is clean$/                                                                       # features/step_definitions/user_steps.rb:220
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see a list of all users$/                                                            # features/step_definitions/user_steps.rb:254
  NOT MATCHED BY ANY STEPS
0.0000000 /^article "([^"]+)" has comment "([^"]+)"$/                                                     # features/step_definitions/disqus_steps.rb:19
  NOT MATCHED BY ANY STEPS
0.0000000 /^(.*) in the preview$/                                                                         # features/step_definitions/user_steps.rb:303
  NOT MATCHED BY ANY STEPS
0.0000000 /^My email should be public$/                                                                   # features/step_definitions/user_steps.rb:307
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see skills "(.*)" on my profile/                                                     # features/step_definitions/user_steps.rb:384
  NOT MATCHED BY ANY STEPS
0.0000000 /^document "([^"]+)" has comment "([^"]+)"$/                                                    # features/step_definitions/disqus_steps.rb:13
  NOT MATCHED BY ANY STEPS
0.0000000 /^the request should be to "(.*)"$/                                                             # features/step_definitions/user_steps.rb:397
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should see the user's bio$/                                                                 # features/step_definitions/user_steps.rb:401
  NOT MATCHED BY ANY STEPS
0.0000000 /^My email receivings is set to false$/                                                         # features/step_definitions/user_steps.rb:406
  NOT MATCHED BY ANY STEPS
0.0000000 /^my YouTube Channel is not connected/                                                          # features/step_definitions/youtube_steps.rb:5
  NOT MATCHED BY ANY STEPS
0.0000000 /^user "([^"]*)" has YouTube Channel not connected/                                             # features/step_definitions/youtube_steps.rb:26
  NOT MATCHED BY ANY STEPS
0.0000000 /^I should( not)? see "([^"]*)" under "([^"]*)"$/                                               # features/step_definitions/basic_steps.rb:356
  NOT MATCHED BY ANY STEPS
-30409118.5882955 /^the date is "([^"]*)"$/                                                                       # features/step_definitions/event_steps.rb:76
```

### PR DESCRIPTION
**Pull request by touchps**
Removed unused cucumber step definitions.
Fixes #865

### CODE REVIEW

**Comment by touchps** [comment]
Previous build failed perhaps due to intermittent js issues. I didn't change anything other than reopening the pull request.

**Comment by tansaku** [comment]
@touchps you've got some merge conflicts to fix up here - give myself and @diraulo commit access to your repo in the case that you won't have time or will have trouble getting to this

**Comment by touchps** [comment]
Both added as collab to my repo

**Comment by tansaku** [comment]
@touchps here's the steps I used to resolve the merge:


```
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (953_events_index_timezone_bug)]$ 
→ git checkout develop
Switched to branch 'develop'
Your branch is behind 'origin/develop' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (develop)]$ 
→ git pull origin develop
From http://github.com/AgileVentures/WebsiteOne
 * branch            develop    -> FETCH_HEAD
Updating 2d9849d..2a57ffb
Fast-forward
 app/views/events/index.html.erb               |  2 +-
 features/events/list_repeating_events.feature | 16 ++++++++++++++++
 features/step_definitions/event_steps.rb      | 11 +++++++++++
 3 files changed, 28 insertions(+), 1 deletion(-)
 create mode 100644 features/events/list_repeating_events.feature
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (develop)]$ 
→ git checkout touchps/865_redundant_cucumber_step_definitions 
Note: checking out 'touchps/865_redundant_cucumber_step_definitions'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at f8d6f99... removed all unused step defs
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne ((f8d6f99...))]$ 
→ git checkout -b 865_redundant_cucumber_step_definitions
Switched to a new branch '865_redundant_cucumber_step_definitions'
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (865_redundant_cucumber_step_definitions)]$ 
→ git merge develop
Auto-merging features/step_definitions/event_steps.rb
CONFLICT (content): Merge conflict in features/step_definitions/event_steps.rb
Automatic merge failed; fix conflicts and then commit the result.
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (865_redundant_cucumber_step_definitions|MERGING)]$ 
→ git add features/step_definitions/event_steps.rb
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (865_redundant_cucumber_step_definitions|MERGING)]$ 
→ git commit -am 'merges to develop for something that should have been handled automatically?'
[865_redundant_cucumber_step_definitions 9cd347a] merges to develop for something that should have been handled automatically?
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (865_redundant_cucumber_step_definitions)]$ 
→ bec features/events/*
Using the default profile...
........................................................................................................................................................................................

20 scenarios (20 passed)
184 steps (184 passed)
-1174032m0.843s
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (865_redundant_cucumber_step_definitions)]$ 
→ gst
On branch 865_redundant_cucumber_step_definitions
nothing to commit, working directory clean
[tansaku@Samuels-MBP:~/Documents/GitHub/AgileVentures/WebsiteOne (865_redundant_cucumber_step_definitions)]$ 
→ git push touchps 865_redundant_cucumber_step_definitions 
Counting objects: 68, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (68/68), done.
Writing objects: 100% (68/68), 9.41 KiB | 0 bytes/s, done.
Total 68 (delta 54), reused 0 (delta 0)
To http://github.com/touchps/WebsiteOne
   f8d6f99..9cd347a  865_redundant_cucumber_step_definitions -> 865_redundant_cucumber_step_definitions
```

**Comment by touchps** [comment]
Thanks @tansaku.

**Pull request merged**
