### PR TITLE
900 Fix Sponsor/Supporter alignment

### LINKED ISSUE #900: Fix alignment of RubyMine image and "Become a supporter" button
The Ruby Mine image is not centered:
image
It needs the `display:inline-block` removed from this:
```
    <div class="sponsorStandinMedal" style="display:inline-block">
        <img alt="RubyMine 8" src="<%= image_path('sponsors/RubyMine_sidebar.png') %>">
    </div>
```
in _sponsors.html.erb.
The button should either be centered also or be the full width of the sponsors column.

### PR DESCRIPTION
**Pull request by freeranger**
Fixes #900

### CODE REVIEW

**Comment by freeranger** [comment]
Now looks like this:
image
Ready to go if you're happy with it

**Comment by freeranger** [comment]
@diraulo, @tansaku - this is ready to go if you are happy with the above change

**Comment by tansaku** [comment]
looks good @freeranger - one idea might be to stage it on your own heroku instance and paste a link to that in the pull request - then we could review on multiple devices quickly - well actually we can pull out your branch and do the same.

Just a little learning challenge if you want to try it, i.e. deploy to heroku to make a shareable instance.  Feel free to ignore if that seems like too much of a challenge at this point ...

**Comment by diraulo** [comment]
Looks good @freeranger -  Let's :shipit:

**Comment by freeranger** [comment]
@tansaku I tried but it fails :/  https://semaphoreci.com/freeranger/websiteone/servers/freeranger-wso-develop/deploys/6
I haven't set up heroku before for a deployment from semaphore so I don't know what I'm doing wrong....
@diraulo Cool thanks

**Comment by diraulo** [comment]
@tansaku @freeranger I've configured heroku's "Review apps" feature for WSO, if all goes well every new PR will be deployed to heroku automatically and we'll be able to test them from there.

**Comment by freeranger** [comment]
@diraulo - that's sounds pretty cool.
What would be the url to a deployed PR?

**Comment by diraulo** [comment]
It would be referenced by Heroku on the PR after the app is deployed

**Comment by freeranger** [comment]
cool, thanks

**Pull request merged**
