### PR TITLE
[WIP] worked out how to pass hard coded user params along with omniauth ...

### LINKED ISSUE #2385: GDPR options for Github and Google Signups
At the moment the Github and Google Signups will ignore the email consent options.  They will default to false so that's okay in terms of not getting reported, but we'd like people who ask to receive emails (and sign up via a third party) to get those emails ...

### PR DESCRIPTION
**Pull request by tansaku**
fixes #2385

### CODE REVIEW

**Comment by mattwr18** [comment]
Failing this test:
`rspec ./spec/controllers/authentications_controller_spec.rb:87`
with this message:
```
NoMethodError:
       undefined method `merge' for nil:NilClass
```

**Comment by mattwr18** [comment]
@tansaku there is an open issue on omniauth related to this:
https://github.com/omniauth/omniauth/issues/937
Actually, there seem to be a lot of open issues related to testing its behaviour :(
https://github.com/omniauth/omniauth/issues/932
With no response from them... 
https://github.com/omniauth/omniauth/issues/934
There is this wiki, which I wonder if you have seen, but nothing about params particularly:
https://github.com/omniauth/omniauth/wiki/Integration-Testing
_wonder if you might get me caught up to what you have already tried_

**Comment by mattwr18** [comment]
Ahh, right so manually testing it seems like in fact the params do persist to the database, was that your experience @tansaku?

**Comment by tansaku** [comment]
@mattwr18 can't remember :-(  my vague sense is that this was "working" but couldn't get a way to test it automatically ...

**Pull request closed without merging**
