### PR TITLE
750 junk in cucumber log

### LINKED ISSUE #750: junk in the cucumber log
we get this junk in the cucumber log - want to clean this all out:

```
$ bundle exec cucumber --format progress
[Coveralls] Using SimpleCov's 'rails' settings.
Using the default profile...
...............................................................................................................................................................DEPRECATION WARNING: Passing string argument to #within_window is deprecated. Pass window object or lambda. (called from /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/features/step_definitions/articles_steps.rb:24)
........................................................................................................invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
...............................invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
.................................................................................................................................................................................................................................................................................................................F-    HTML screenshot: /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/tmp/capybara/screenshot_2014-02-03-07-10-06.348.html
    Image screenshot: /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/tmp/capybara/screenshot_2014-02-03-07-10-06.348.png
..............................................................................F    HTML screenshot: /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/tmp/capybara/screenshot_2016-02-03-15-07-05.190.html
    Image screenshot: /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/tmp/capybara/screenshot_2016-02-03-15-07-05.190.png
..................................................invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
..........invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
....................................................................................................................................................................................................................................F-    HTML screenshot: /Users/tansaku/Documents/Github/AgileVentures/WebSiteOne/tmp/capybara/screenshot_2014-07-15-13-00-07.000.html
.............................................................................................................................................................................................................................................................................................invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
.invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
.invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
.invalid keys :visible, should be one of :text, :visible, :between, :count, :maximum, :minimum, :exact, :match, :wait
...........................................................................................Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Bryan Yap stats are okay
.............Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Bryan Yap stats are okay
........Got what I came for from https://github.com/AgileVentures/WebsiteOne
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Something is Wrooong!
Bryan Yap stats are okay
...................................................................................................................................................................................................-----............................................................................................................................................................................................


```

### PR DESCRIPTION
**Pull request by freeranger**
closes #750

### CODE REVIEW

**Comment by freeranger** [comment]
@tansaku to review - as discussed last week, I don't know enough about the code to know what should make the Edit page button appear.
The captured output from this test doesn't show an edit button present for it to be selected.
The changes in this issue are changes to the selectors in the tests - no actual application code was harmed by the changes in this PR so I'm struggling to see what's happened here..

**Comment by tansaku** [comment]
thanks @freeranger - will try to look at today

**Comment by tansaku** [comment]
oops - didn't look at this yet - sorry - today!

**Comment by tansaku** [comment]
I think some of the failures in the CI are due to our intermittent js failures #806 but running on my local machine I see that documents.feature:47 is failing consistently, so that's where I'll investigate ...

**Comment by tansaku** [comment]
I just used `git bisect` to identify the specific commit that introduces this problem:

```
[tansaku@Samuels-MBP:~/Documents/GitHub/WebsiteOne (750_junk_in_cucumber_log)]$ 
→ git bisect
usage: git bisect [help|start|bad|good|skip|next|reset|visualize|replay|log|run]
[tansaku@Samuels-MBP:~/Documents/GitHub/WebsiteOne (750_junk_in_cucumber_log)]$ 
→ git bisect start
[tansaku@Samuels-MBP:~/Documents/GitHub/WebsiteOne (750_junk_in_cucumber_log|BISECTING)]$ 
→ git bisect bad
[tansaku@Samuels-MBP:~/Documents/GitHub/WebsiteOne (750_junk_in_cucumber_log|BISECTING)]$ 
→ git bisect good 645e487
Bisecting: 1 revision left to test after this (roughly 1 step)
[df6885de3fece7423b72a23e405571021f1470a2] Updated capybara and use new syntax to fix cucumber log errors
[tansaku@Samuels-MBP:~/Documents/GitHub/WebsiteOne ((df6885d...)|BISECTING)]$ 
```

https://git-scm.com/docs/git-bisect

**Comment by tansaku** [comment]
so we have a number of issues here.  If we look at the failing scenario we some higher level issues:

```cucumber
  Scenario: Show a document
    Given I am on the "Show" page for project "hello mars"
    When I click the sidebar link "Guides"
    Then I should be on the "Show" page for document "Guides"
    And I should see "Guides"
    And I should see "New content 0"
    And I should see a link to "Edit" page for document "Guides"
```

This is not your code - so none of this is a criticism of anything you have done.  I'm just analyzing the existing code.  The interesting thing to note here is how the scenario name contradicts what the scenario does at the end, specifically that it checks for the presence of an edit link.  The scenario is just checking that the document is shown, and notice that no user logs in, so in fact an edit link should not be present.

But so why was this passing originally?

Let's look at the original step definition:

```ruby
Then(/^I should( not be able to)? see a link to "([^"]*)" page for ([^"]*) "([^"]*)"$/) do |invisible, action, controller, title|
  page.has_link?(action, href: url_for_title(action: action, controller: controller, title: title))
  byebug
  unless invisible
    page.should have_text title, visible: false
  end
end
```

The step definition is actually a bit of a mess.  The has_link? method is just being called rather than having any expectation set around it, so it's not actually checking for the presence of a link.  The "page.should have_text title, visible: false" initially only checks for the presence of the text in the page, so we have two layers here of things "not doing what they say on the tin", so it's not surprising that this is a difficult thing to sort out.

So the simple fix for this pull request is to remove the `And I should see a link to "Edit" page for document "Guides"` from the end of the scenario since it just shouldn't be there - and we need an additional chore to fix up this step definition.

One comment that's specific to the code you submitted is that in your re-write of the step definition you have:

```
should have_selector ...
```
 
and not 

```
page.should have_selector ...
```

or even better you might prefer

```
expect(page).to have_selector ...
```

but of course you have a separate pull request going on that :-)

**Comment by tansaku** [comment]
Note that the edit functionality (and edit link) is tested more robustly in a later scenario in the same feature file:

```cucumber
  Scenario: Has a link to edit a document using the Mercury Editor
    Given the document "Guides" has a child document with title "Howto"
    Given I am logged in
    And I am on the "Show" page for document "Howto"
    When I click the very stylish "Edit" button
    Then I should be in the Mercury Editor
```

and the associated step definition shows the mechanism for clicking on this edit button which uses an icon rather than text as the link body:

```ruby
When(/^I click the very stylish "([^"]*)" button$/) do |button|
  find(:css, %Q{a[title="#{button.downcase}"]}).click()
end
```

**Comment by freeranger** [comment]
@tansaku Thanks for taking the time to look at this, and for the in-depth analysis!
I have removed the line from the test that is failing, made the expect change, and even rebased the PR so it is now one commit - Hopefully this is good to go now.

**Comment by tansaku** [comment]
@diraulo codewise this looks good to go - want to double check for me?

@freeranger I opened a chore for the related issue I notice: #903 - also I think your local github email config is not set.  Can you check and/or run the following on your local machine:

```
git config --global user.email "your_email@example.com"
```

with whatever email you use for git and then git amend and re-push so that your commit will link to your github user profile?  

Many thanks in advance

**Comment by freeranger** [comment]
@tansaku Ok if I use freeranger@users.noreply.github.com or would you prefer my real email address?
Trying to keep the liklihood of spam down to a minimum...

**Comment by tansaku** [comment]
whichever one links to your github id would be ideal, I have my email address public everywhere and rely on spam filters myself.

I don't know if setting your real one will make it show up anywhere in particular (github logs I guess) but I don't think GitHub makes those publicly browsable, so adding your github email to your git config shouldn't expose your email address anywhere that page crawlers can get it (except possibly in travis).

Personally I think it's well worth the risk

**Comment by freeranger** [comment]
@tansaku Ok, try again....

**Comment by tansaku** [comment]
@freeranger hang in there - you're making great progress!

**Comment by freeranger** [comment]
Thanks...hoping the next PR is more butter-like :)

**Pull request merged**
