### PR TITLE
Make interceptor work in all environments

### PR DESCRIPTION
**Pull request by maryam21**
#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tansaku** [comment]
thanks for this @maryam21 - we might even want to think about what we want the default behaviour to be - does it make more sense to have interceptors in place by default, and create an ALLOW_EMAILS flag that turns them off?

**Comment by maryam21** [comment]
Wouldn't having the interceptor by default impact production environment because emails won't be sent unless we explicitly set ALLOW_EMAILS.

**Comment by tansaku** [comment]
@maryam21 yes, but we can explicitly enable that setting in production and then it will always work there 

note that production is the only place where we want emails going out, so we want the default on any other server for them to be intercepted, and for local machines developers should all have letter-opener and then interceptor just in case ...

**Comment by maryam21** [comment]
yes makes sense. I will change it that way

**Pull request closed without merging**
