### PR TITLE
add tawkto

### LINKED ISSUE #1908: have live help chat in the site
I wish we had a slick integrated solution like odinproject has with gitter - tawkto is a free customer chat solution - we previously used chatlio ...

maybe we should just go with gitter as our place for people browsing the site - such a shame that slack doesn't provide the same appear in a subwindow of a browser integration

### PR DESCRIPTION
**Pull request by tansaku**
fixes #1908

### CODE REVIEW

**Comment by sigu** [comment]
@tansaku  what could be the effect of this warning that we are seeing on the CI ?

screenshot-2017-10-18 app assets javascripts tawkto js from agileventures websiteone - code climate

**Comment by tansaku** [comment]
@sigu I don't know ... there are details in the code climate issue:



you can click through on "read up"

**Comment by nisevi** [comment]
Hey @sigu I fiexd the issue you were having with codeclimate :+1:

**Comment by nisevi** [comment]
@sigu do you need help with this one :+1: ?

**Comment by tansaku** [comment]
this might be fun, but I don't have the bandwidth to pull this in and deal with lots of random chatter on the site - but if anyone wants to take it on, be my guest :-)

**Pull request closed without merging**
