### PR TITLE
Upgrade to rails 5.2

### LINKED ISSUE #2767: Upgrade to Rails 5.2
Uses Redis Caching, and it's cool to stay up-to-date

### PR DESCRIPTION
**Pull request by mattwr18**
There are cool features like built in Redis caching with Rails 5.2
Also, it's good to update, Rails 6 is already out.
Fixes #2767 
#### Description

Upgrading fun
#### Motivation and Context

To keep up with the Joneses
#### How Has This Been Tested?

Running all tests(some failures locally)
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Upgrade

#### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mattwr18** [comment]
Failing the build with these errors
```
Failing Scenarios:
cucumber -p first_try features/events/edit_future_event.feature:27 # Scenario: Check that edit page reflects initial settings
cucumber -p first_try features/events/private_events.feature:37 # Scenario: Edit hangout url for private event pings only appropriate private channels
cucumber -p first_try features/events/private_events.feature:45 # Scenario: Edit youtube url for private event pings only appropriate private channels
cucumber -p first_try features/hangouts/edit_hangout_url.feature:21 # Scenario: Edit Hangout URL and ensure event stays live
cucumber -p first_try features/hangouts/edit_hangout_url.feature:28 # Scenario: Edit Hangout URL on repeating event and ensure event stays live
cucumber -p first_try features/hangouts/edit_hangout_url.feature:35 # Scenario: Event doesn't go live before Hangout URL is updated
cucumber -p first_try features/hangouts/edit_hangout_url.feature:42 # Scenario: Event doesn't ping old youtube URL
cucumber -p first_try features/hangouts/edit_youtube_url.feature:22 # Scenario: Editing Youtube URL has no effect on Hangout URL
cucumber -p first_try features/hangouts/edit_youtube_url.feature:28 # Scenario: Editing Hangout URL has no effect on Youtube URL
cucumber -p first_try features/hangouts/edit_youtube_url.feature:44 # Scenario: Edit Youtube URL and ensure video appears on Project page
cucumber -p first_try features/hangouts/edit_youtube_url.feature:51 # Scenario: Edit Youtube URL when event is live and ensure a separate event instance is not created
cucumber -p first_try features/hangouts/edit_youtube_url.feature:72 # Scenario: Hangout URL is not posted in slack when Youtube URL is edited
cucumber -p first_try features/hangouts/hangout.feature:131 # Scenario: Infinite scroll on hangouts scroll down until no more hangouts
cucumber -p first_try features/users/profile_update_credit_card.feature:29
```

**Comment by mattwr18** [comment]
With the latest changes from develop merged in 
```
Failing Scenarios:
cucumber -p first_try features/events/private_events.feature:37 # Scenario: Edit hangout url for private event pings only appropriate private channels
cucumber -p first_try features/events/private_events.feature:45 # Scenario: Edit youtube url for private event pings only appropriate private channels
cucumber -p first_try features/hangouts/edit_hangout_url.feature:21 # Scenario: Edit Hangout URL and ensure event stays live
cucumber -p first_try features/hangouts/edit_hangout_url.feature:28 # Scenario: Edit Hangout URL on repeating event and ensure event stays live
cucumber -p first_try features/hangouts/edit_hangout_url.feature:35 # Scenario: Event doesn't go live before Hangout URL is updated
cucumber -p first_try features/hangouts/edit_hangout_url.feature:42 # Scenario: Event doesn't ping old youtube URL
cucumber -p first_try features/hangouts/edit_youtube_url.feature:22 # Scenario: Editing Youtube URL has no effect on Hangout URL
cucumber -p first_try features/hangouts/edit_youtube_url.feature:28 # Scenario: Editing Hangout URL has no effect on Youtube URL
cucumber -p first_try features/hangouts/edit_youtube_url.feature:44 # Scenario: Edit Youtube URL and ensure video appears on Project page
cucumber -p first_try features/hangouts/edit_youtube_url.feature:51 # Scenario: Edit Youtube URL when event is live and ensure a separate event instance is not created
cucumber -p first_try features/hangouts/edit_youtube_url.feature:72 # Scenario: Hangout URL is not posted in slack when Youtube URL is edited
cucumber -p first_try features/hangouts/hangout.feature:131 # Scenario: Infinite scroll on hangouts scroll down until no more hangouts
cucumber -p first_try features/users/profile_update_credit_card.feature:37
```

**Comment by mattwr18** [comment]
Still getting these failures on the build:
```
Failing Scenarios:
cucumber -p first_try features/events/edit_future_event.feature:46 # Scenario: Edit an existing event but cancel, and go back to show page for that event
cucumber -p first_try features/events/private_events.feature:45 # Scenario: Edit youtube url for private event pings only appropriate private channels
cucumber -p first_try features/hangouts/edit_youtube_url.feature:28 # Scenario: Editing Hangout URL has no effect on Youtube URL
cucumber -p first_try features/hangouts/edit_youtube_url.feature:44 # Scenario: Edit Youtube URL and ensure video appears on Project page
cucumber -p first_try features/hangouts/edit_youtube_url.feature:72 # Scenario: Hangout URL is not posted in slack when Youtube URL is edited
cucumber -p first_try features/hangouts/hangout.feature:131 
```
I guess the last one is a recurrent intermittent failing test.
edit_youtube_url.feature we maybe need to have a closer look @tansaku

**Comment by tansaku** [comment]
great progress @mattwr18 - fewer errors now:

```
cucumber -p first_try features/events/private_events.feature:63 # Scenario: Edit youtube url for private event pings only appropriate private channels
cucumber -p first_try features/hangouts/edit_youtube_url.feature:28 # Scenario: Editing Hangout URL has no effect on Youtube URL
cucumber -p first_try features/hangouts/edit_youtube_url.feature:44 # Scenario: Edit Youtube URL and ensure video appears on Project page
cucumber -p first_try features/hangouts/edit_youtube_url.feature:72 # Scenario: Hangout URL is not posted in slack when Youtube URL is edited
cucumber -p first_try features/hangouts/hangout.feature:131 # Scenario: Infinite scroll on hangouts scroll down until no more hangouts
```

**Comment by mattwr18** [comment]
It's passing @tansaku!!!!

**Pull request merged**
