### PR TITLE
Load README from GitHub

### PR DESCRIPTION
**Pull request by nisevi**
Issue associate to this PR: https://github.com/AgileVentures/WebsiteOne/issues/2300

### CODE REVIEW

**Comment by nisevi** [comment]
@tansaku the feature is already implemented and working if you wanna try locally :+1:

**Comment by tansaku** [comment]
great work getting started on this @nisevi - sorry I've not been able to review yet - will look at it ASAP

**Comment by nisevi** [comment]
I think VCR updated one of the cassettes that we are using and that is causing the error?

image

**Comment by nisevi** [comment]
@tansaku cucumber added :rocket:

**Pull request merged**
