### PR TITLE
Updating scrums defaulting to wrong projects

### LINKED ISSUE #2272: scrums being saved are defaulting to wrong project
Updating a scrum to change the time is causing the wrong project (e.g. AV setup scripts) to be assigned to the project - we need to respect scrums with no project affiliation ...

### PR DESCRIPTION
**Pull request by aonomike**
- Add test to check the event project dropdown defaults to existing event's project during edit
- Update step to downcase slugs

#### How Has This Been Tested?
The PR has new acceptance tests written and passing
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Fixes #2272

### CODE REVIEW

**Comment by aonomike** [comment]
@tansaku you did not paste your comments from the scrum especially about the declarative vs imperative approaches

**Comment by mattwr18** [comment]
hey @aonomike the notes from the scrum were posted on the #general channel this morning, but here they are:
https://github.com/AgileVentures/AgileVentures/wiki/2018-10-24-Scrum

**Comment by aonomike** [comment]
Yes @tansaku will update given the comments

**Comment by mattwr18** [comment]
Any way I can help you with this @aonomike?

**Comment by tansaku** [comment]
thanks for working on this @aonomike - is it passing locally for you?

On CI it is failing on `cucumber -p second_try features/events/edit_event.feature:23 # Scenario: Updating an event defaults to correct project`

```
  Scenario: Updating an event defaults to correct project          # features/events/edit_event.feature:23
    Given I visit the edit page for the event named "Scrum"        # features/step_definitions/event_steps.rb:1
    Then no project is selected in the event project dropdown      # features/step_definitions/event_steps.rb:471

      expected: value != "3"
           got: "3"

      (compared using ==)
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/event_steps.rb:473:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/event_steps.rb:472:in `each'
      ./features/step_definitions/event_steps.rb:472:in `/^no project is selected in the event project dropdown$/'
      features/events/edit_event.feature:25:in `Then no project is selected in the event project dropdown'
```

**Comment by tansaku** [comment]
great work @mattwr18 and @aonomike - is this ready to merge now?

**Comment by tansaku** [comment]
looks great @aonomike and @mattwr18 - this looks great! :-)

**Pull request merged**
