### PR TITLE
[WIP] 2893 integrate event_instances api pagination

### PR DESCRIPTION
**Pull request by dkuku**
#### Issue addressed
Initial commit. I push it here because the changes are not yet upstream.

#### Testing
Tested using rspec
Checked if pagination is working and for required fields in the response

### CODE REVIEW

**Comment by tansaku** [comment]
@dkuku how's this PR going? still active?

**Comment by tansaku** [comment]
@dkuku should we close this one for the time being?

**Comment by dkuku** [comment]
Hi @tansaku . I was busy for the last month. 
In this PR I got stuck with the grape gem, because there was no easy way to do a join tables request other than installing another gem and use their dsl which is a bit overkill for me because it all could be done without any gems in one line of code like in #2904  
I was waiting for someone to have the similiar problem with grape, but I can't see any updates to the grape api in the develop branch - is this still used ?

**Comment by tansaku** [comment]
@dkuku - I think @mattwr18 is deploying custom grape code to the dokku develop from his own branches maybe ...?  I thought some grape was merged into the main system too - @mattwr18 is the person to coordinate with

**Comment by dkuku** [comment]
@tansaku closing it for now

**Pull request closed without merging**
