### PR TITLE
Make tests work in docker

### PR DESCRIPTION
**Pull request by mtc2013**
This PR builds off the pr here https://github.com/AgileVentures/WebsiteOne/pull/3802

Before tests were falling on their face in the docker instance with various errors.  Now they work and pass.  Basically, OPENSSL_CONF wasn't working for phantomjs and the only thing that seemed to fix it was effectively allowing it to do its default thing by setting it to /dev/null.

I also was able to bump ruby to version 3.0.4 and deleted an errant rerun.txt file.

### CODE REVIEW

**Review by mattlindsey — COMMENTED** [review]
PR3803 (‘Make tests work in docker’) on my Mac with new Monterey 12.6.1 on older intel Mac is still failing 4 cucumbers:

Failing Scenarios:
cucumber features/dashboard/public_activity.feature:31 # Scenario: Navigate to activity feed
cucumber features/dashboard/public_activity.feature:43 # Scenario: Render activity feed even if user is deleted
cucumber features/project_documents.feature:121 # Scenario: Document should have a history of changes
cucumber features/users/github_commit_count.feature:19 # Scenario: Displays commit counts on user profile page
328 scenarios (4 failed, 324 passed)
2546 steps (4 failed, 13 skipped, 2529 passed)

Interesting that only 2 of the 4 errors occur when I’m NOT in docker:

Failing Scenarios:
cucumber features/project_documents.feature:181 # Scenario: A logged in user could change a document’s parent section
cucumber features/users/github_commit_count.feature:19 # Scenario: Displays commit counts on user profile page
328 scenarios (2 failed, 326 passed)
2546 steps (2 failed, 7 skipped, 2537 passed)

image
image2

**Comment by marianmosley** [comment]
I have got a different scenario failing outside of docker on my Monterey 12.0.1
features/users/profile_update_credit_card.feature:17

image

I will try fixing the screenshot thing so we can see what's going on.

**Comment by marianmosley** [comment]
@mtc2013 gave me the .env keys and I now have all cukes passing locally.

**Comment by marianmosley** [comment]
@mattlindsey I have all cukes and specs passing on docker on Monterey 12.0.1.  Maybe you have a config issue?
image
image

**Comment by mtc2013** [comment]
codeclimate seems highly picky about the ordering of gems.

**Review by mattlindsey — APPROVED** [review]
The few errors I'm getting seem to be specific to my setup, so I think it's good to approve.

**Pull request merged**
