### PR TITLE
Update specific gems

### PR DESCRIPTION
**Pull request by nisevi**
Relates to issue: https://github.com/AgileVentures/WebsiteOne/issues/2419

### CODE REVIEW

**Comment by nisevi** [comment]
`rack-timeout` issue: https://github.com/heroku/rack-timeout/issues/130

**Comment by nisevi** [comment]
Hi there guys @FedericoEsparza @tansaku @NickSchimek if you can take a look to this PR I will really appreciate it :rocket:

**Comment by NickSchimek** [comment]
@nisevi When I go to semaphore ci to view the failure details I'm getting a 404 page not found error.  Do you have the stack trace from the failures? Can we get these re-ran on semaphore?

**Comment by nisevi** [comment]
@NickSchimek `env` variable was added to the project setup.

**Pull request merged**
