### PR TITLE
Cookies Banner (fixes #3859)

### LINKED ISSUE #3859: Add cookies policy consent dialog
Options:
https://www.youtube.com/watch?v=CXe5WvheO48
https://blog.corsego.com/accept-cookies-banner
https://github.com/osano/cookieconsent
https://ninjadevel.com/implement-cookie-bar-ruby-on-rails/
https://github.com/infinum/cookies_eu

### PR DESCRIPTION
**Pull request by wordhouse66**
This PR adds a cookie banner
fixes #3859

### CODE REVIEW

**Comment by mattlindsey** [comment]
Looking good. I did a quick test and noticed a few things:
- Make 'Accept Cookies' and 'Reject Cookies' look like buttons
- Make wording a little friendlier. Something like 'We respect your privacy. Cookies are used to analyze traffic.'
- Add link 'Privacy statement.' like the one at the bottom of the Sign Up page (/users/sign_up).
- If you can, I think there is supposed to be an 'X' on the banner than lets the user close it without setting anything.

**Comment by wordhouse66** [comment]
I have worked on all those things.  Are they ok?

**Comment by mattlindsey** [comment]
Looking great, but noticed a couple of things
-When you click 'Accept' or 'Reject', the page goes blank
-I don't know a lot about cookies, but it appears the 'ga' (Google Analytics) cookie(s) are still getting set.
  I think maybe this line shouldn't happen if the user hasn't 'allowed' cookies:
https://github.com/AgileVentures/WebsiteOne/blob/178ee9fef07c22606b7e4f44d73d9d9f9bdf24b8/app/controllers/application_controller.rb#L92

I'll try to look into this more soon, and you can get an 'extension' for your browser (I got 'Cookie Manager' for Chrome) to delete and view cookies while visiting localhost:300 to see the google cookies ('_ga' and '_gid', I think) to figure out how not to set them unless allowed by user.

**Comment by wordhouse66** [comment]
Ok. I will work on fixing that.

**Comment by mattlindsey** [comment]
I get a few cucumber errors(below) due to the new cookie dialog.  They say something about "Cuprite detected another element."  Do you think they can be fixed?  Also, I sent a few possible improvements on Slack you can look at if you want.  Thanks!

```
Failing Scenarios:
cucumber features/events/create_events.feature:96 # Scenario: Creating a repeating event requires an end date
cucumber features/events/edit_future_event.feature:26 # Scenario: Check that edit page reflects initial settings
cucumber features/events/edit_future_event.feature:36 # Scenario: Edit an existing event to never end
cucumber features/events/edit_future_event.feature:45 # Scenario: Edit an existing event but cancel, and go back to show page for that event
cucumber features/events/edit_future_event.feature:50 # Scenario: User in non-UTC timezone edits and overrides the timezone of an existing event, and has expected side-effects for user in UTC timezone
cucumber features/events/edit_future_event.feature:59 # Scenario: User in non-UTC timezone edits but makes no changes to an existing event, and has no side-effects for user in UTC timezone
cucumber features/events/edit_future_event.feature:67 # Scenario: User in non-UTC timezone saves an existing event with no changes, during daylight savings

289 scenarios (7 failed, 282 passed)
2169 steps (7 failed, 44 skipped, 2118 passed)
1m38.448s
```

**Comment by wordhouse66** [comment]
I will work on it.

**Review by mattlindsey — APPROVED** [review]
We sometime get cucumber test errors that mention the new cookie dialog ("Firing a click at coordinates [xxx] failed. Cuprite detected another element with CSS selector ...") but we can try to fix that later.

**Pull request merged**
