### PR TITLE
The long awaited event show page update

### LINKED ISSUE #765: Update events show page
imported from https://www.pivotaltracker.com/n/projects/982890/stories/85232534

As site admin
In order to make the experience for a visitor better
I would like to display only the necessary information about the next upcoming event instance

### PR DESCRIPTION
**Pull request by yggie**
The commits were old so there were lots of things I had to clean up, it might not look exactly as it was on the wireframes but I believe this is where we settled on. Let me know if there is anything else that needs work.

closes #765

### CODE REVIEW

**Comment by diraulo** [comment]
Hey @yggie thanks for the PR, some of the test are currently failing on CI are they all passing locally? 
Would be cool if you have a few minutes to look them up so I can merge this :wink:

**Comment by yggie** [comment]
@diraulo ah good point, I forgot that the branch was still work in progress :grin:, will fix them when I have time

**Comment by diraulo** [comment]
@yggie did you have any chance to look at this again? :)

**Comment by yggie** [comment]
@diraulo sorry this slipped my mind, I will try to make some time again tonight :grin:

**Comment by diraulo** [comment]
@yggie awesome :wink:

**Comment by tansaku** [comment]
@yggie which ticket is this related to?  is there anything blocking you ATM?

**Comment by yggie** [comment]
@tansaku it is related to https://www.pivotaltracker.com/story/show/85232534, sorry I forgot to add the ticket link. Nothing blocking me, apart from the general lack of time :disappointed:

**Comment by tansaku** [comment]
no worries @yggie - will it help if we can set you up with a pair or other support?

**Comment by yggie** [comment]
@tansaku that would be nice, though it may be hard to organise a pairing time, are there any developers interested in helping in this story?

**Comment by tansaku** [comment]
@yggie possibly - what times are you free? or do you even just want to outline what remains to be done and I or another can take an asynchronous stab at it? :-)

**Comment by yggie** [comment]
won’t be free anytime this week, the only thing remaining is reintroducing the edit hangouts functionality which was removed during the implementation of the new page, and fixing the associated cucumber specs. The relevant markup should be somewhere in the diff :grinning: I can’t remember the exact details right now…

**Comment by tochman** [comment]
I made some touching up of this in https://github.com/AgileVentures/WebsiteOne/pull/784

**Comment by tansaku** [comment]
thanks @tochman !  

So @yggie I guess we can close this pull request and focus on  #784

**Comment by tansaku** [comment]
right, well I'm going to close this and focus on #784

**Pull request closed without merging**
