### PR TITLE
Resolving merge conflicts in Jeffs commit count pull request

### LINKED ISSUE #764: Github commit count on profile page
imported from https://www.pivotaltracker.com/story/show/64891298

As a member of AV
So that I can find out what projects others are contributing to
I should see the number of commits they have made to projects listed on their profile page.

### PR DESCRIPTION
**Pull request by tansaku**
closes #764

### CODE REVIEW

**Comment by tansaku** [comment]
@diraulo hmm - CI hasn't run on this ... is that a semaphore config perhaps ...

**Comment by diraulo** [comment]
@tansaku we've had cases like this before. Not sure why it does it or how to solve it. If i remember correctly, I would often pull the PR and run the tests locally then with someone else approval merge the PR.

**Comment by diraulo** [comment]
@tansaku I have some failing tests on this PR that need to be investigated

**Comment by tansaku** [comment]
@diraulo which ones are failing for you?

I'm going to pull the capycara/poltergeist upgrade into this to see if that helps ...

**Comment by tansaku** [comment]
I get:

```
  1) GithubCommitsJob.job stores total commit count only for projects that have a github_url
     Failure/Error: GithubCommitsJob.run
     NoMethodError:
       undefined method `auth_token' for nil:NilClass
```

as an example of these 6 failures:

```
rspec ./spec/jobs/github_commits_job_spec.rb:27 # GithubCommitsJob.job stores total commit count only for projects that have a github_url
rspec ./spec/jobs/github_commits_job_spec.rb:32 # GithubCommitsJob.job stores commit counts only for users that have a github_profile_url
rspec ./spec/jobs/github_commits_job_spec.rb:41 # GithubCommitsJob.job stores correct total commit count for projects
rspec ./spec/jobs/github_commits_job_spec.rb:36 # GithubCommitsJob.job stores correct commit counts by user and project
rspec ./spec/jobs/github_commits_job_spec.rb:22 # GithubCommitsJob.job stores commit counts only for projects that have a github_url
rspec ./spec/controllers/application_controller_spec.rb:43 # ApplicationController global user messages should set @@message_status to false at application l

```

hmm, I notice that semaphore didn't run on this branch .... mmmm

**Comment by tansaku** [comment]
I also note that as @tochman pointed out, that this pull request introduces a job that uses a rails logger for the github job, so that will clean up some of the issues referred to in #784

I also get these cucumber failures on this branch:

```
(::) failed steps (::)

expected to find css "h4" with text "Support our fundraising campaign on Pledgie.org" but there were no matches (RSpec::Expectations::ExpectationNotMetError)
./features/step_definitions/basic_steps.rb:373:in `block (2 levels) in <top (required)>'
./features/step_definitions/basic_steps.rb:369:in `/^I should( not)? see a flash with "([^"]*)"$/'
features/basic_layout.feature:13:in `Then I should see a flash with "Support our fundraising campaign on Pledgie.org"'

undefined method `auth_token' for nil:NilClass (NoMethodError)
./app/jobs/github_commits_job.rb:56:in `client'
./app/jobs/github_commits_job.rb:19:in `update_total_commit_count_for'
./app/jobs/github_commits_job.rb:8:in `block in run'
./app/jobs/github_commits_job.rb:7:in `run'
./features/step_definitions/user_steps.rb:411:in `/^I fetch the GitHub contribution statistics$/'
features/users/github_commit_count.feature:15:in `And I fetch the GitHub contribution statistics'

Failing Scenarios:
cucumber features/basic_layout.feature:12 # Scenario: Fundraising flash is displayed once
cucumber features/users/github_commit_count.feature:19 # Scenario: Displays commit counts on user profile page
```

I guess I'll re-open this from my own repo in order to get the CI to kick off ...

**Comment by diraulo** [comment]
@tansaku I remember having most failures (if not all) related to `undefined method `auth_token' for nil:NilClass`

**Comment by diraulo** [comment]
@tansaku  Weird ... As soon as you re-opened the PRs, this one was picked up too by semaphore

**Pull request closed without merging**
