### PR TITLE
Add email interceptor

### LINKED ISSUE #2342: project follow fails on develop and staging
I think it must be a mail config issue, but we are getting fails on develop and staging trying to do project joins - which I think is related to attempting to send emails on those boxes.

Some more details in https://github.com/AgileVentures/WebsiteOne/pull/2336#issuecomment-386273500

Our code should be more robust to this fail, and we should make sure we have sensible email dummies working on those boxes.

The functionality is all working fine on production ...

### PR DESCRIPTION
**Pull request by maryam21**
#### Description

Added functionality to intercept emails in development and staging environment using Action Mailer.
#### Motivation and Context

Fixes #2342 
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by maryam21** [comment]
I think it would be better to add them, I will add them. Also should I remove the letter_opener gem as it's no longer needed?

**Comment by tansaku** [comment]
@maryam21  thanks :-)

I think we can still use the letter-opener gem as that will help debugging emails on our personal developer machines, assuming it is configured correctly

**Comment by tansaku** [comment]
and great work on the tests - I'll get this out since we really need this on staging/develop servers, but something to think about is driving from cucumber in the devops features to make the high level goals of the tests clearer.  

If you've got a strong preference for rspec tests that's not a problem, but I always struggle to skim read them.  Some folks don't like cucumber much, how about you?  Have you looked through some of our devops cucumber tests?

**Comment by maryam21** [comment]
Actually I wasn't sure how, as this only works on staging and development environments. I was going to ask you about that.

**Pull request merged**
