### PR TITLE
Fix video link from http to https

### LINKED ISSUE #1655: embedded youtube playing not working due to https/http issue
embedded youtube playing not working due to https/http issue

### PR DESCRIPTION
**Pull request by mattlindsey**
fixes #1655 

Tested manually by comparing /projects/websiteone#video on live site to local.

### CODE REVIEW

**Comment by tansaku** [comment]
@mattlindsey I've just noticed that this change did not fix the issue

**Comment by tansaku** [comment]
I think the change we actually need is here: https://github.com/AgileVentures/WebsiteOne/blob/develop/app/assets/javascripts/scrums.js#L12

**Comment by mattlindsey** [comment]
I'll make the change, but things seem to work for me. Wierd.

**Comment by tansaku** [comment]
it maybe fixed it for individual users video pages, but not for project pages

**Pull request merged**
