### PR TITLE
adds in all cache files from green run and comments out one test that we need to review

### LINKED ISSUE #1754: develop failing on test that previously past
So develop was green, but this test starting failing recently:

```
cucumber features/hangouts/edit_youtube_url.feature:33
```

Here's part of the stack trace:

```
    When I am on the "Show" page for project "LS"                                          # features/step_definitions/basic_steps.rb:255
      One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

      pause@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:6480:34
      JV@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:3410:51
      uV@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:3383:182
      bra@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:4146:126
      r1@https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:4125:103
      https://www.youtube.com/yts/jsbin/player-vflrwQIQw/en_GB/base.js:7223:167
      https://www.youtube.com/yts/jsbin/www-embed-player-vfllwwkQI/www-embed-player.js:373:293

```

It looks to me like the caching files for VCR and puffing-billy were not checked in with the original test commit, which makes it seem like something has changed in the way that youtube is responding to the request to embed a video in a project page?

I notice I can remove the error if I remove the ytplayer iframe from the project page - I guess this might be to do with requesting something from a video that doesn't exist.  I say that because when I add that video id to an event associated with a project on the develop server, I get the following error in the js console:

that appears to be a request for the default youtube video image or https://i1.ytimg.com/vi/12341234111/hqdefault.jpg

and I'm not seeing that issue for general project videos on production ...

if I paste that URL into a browser I get: 
 

the ytplayer is updated by code in app/assets/javascripts/users.js:

```js
    function selectVideo(event) {
        event.preventDefault();
        player = $('#ytplayer');
        player.attr('src', 'https://www.youtube.com/embed/' + this.id + '?version=3&enablejsapi=1');
        $('#video_contents').text($(this).data('content'));

        $('html, body').animate({
            scrollTop: player.offset().top - 100
        }, 300);
    }
```

### PR DESCRIPTION
**Pull request by tansaku**
fixes #1754

in principle if this goes green we can merge and then develop will be something people can work off

it will still leave us needing to review two tests we had to comment out (maybe an @ignore_js_errors hook is called for ...)

these are the tests relating to viewing the video player - which all seems to work, but we get an error in the console log and that breaks the test - the error is from a google library and doesn't actually cause the functionality to fail in chrome ...

### CODE REVIEW

**Comment by tansaku** [comment]
urgh, getting some other errors in CI:

```
    And I click the first scrum in the timeline                                 # features/step_definitions/scrums_steps.rb:19
      One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

      pause@https://www.youtube.com/yts/jsbin/player_ias-vfltv_9aY/en_US/base.js:4333:34

...

features/scrums.feature:18:in `And I click the first scrum in the timeline'
```

looks like that js fail related to videos is also intermittent ...

**Comment by tansaku** [comment]
related? https://github.com/guardian/membership-frontend/issues/711

**Comment by tansaku** [comment]
So I added an ignore js error hook:

```rb
Before '@javascript_ignore_js_errors' do
  @current_javascript_driver = Capybara.javascript_driver
  Capybara.javascript_driver = :poltergeist
  Capybara.current_driver = Capybara.javascript_driver
end

After '@javascript_ignore_js_errors' do
  Capybara.javascript_driver = @current_javascript_driver
end
```

which also has a side effect of turning off puffing billy on those tests too ...

**Comment by tansaku** [comment]
urgh, and now I'm getting chatlio errors all over the place - maybe chatlio should be turned off if we're not in production mode ...

**Comment by tansaku** [comment]
I do want to remove all these "There was a problem registering visitor. Please contact Chatlio support at support@chatlio.com" comments from our test runs ...

**Comment by mattlindsey** [comment]
@tansaku Possibly just turn off Chatlio for all except Prod?  If that's easy to do.

**Pull request merged**
