### PR TITLE
1817 karma profile link opens activty tab

### LINKED ISSUE #1817: have karma on users account page be linked to activity tab
currently it is unlinked to anything - some js to make the activity tab open up would be a good way of helping people see the breakdown of their karma

### PR DESCRIPTION
**Pull request by Hess3000**
#### Description

Logged in user can click on their karma score and it will open their activity tab to display contributions, if they have contributed.

#### Motivation and Context

fixes #1817

#### How Has This Been Tested?

Cucumber tested

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tansaku** [comment]
@Hess3000 thanks - this looks great :-)

we do have a lot of other files committed, which we perhaps don't need - happy to look at that together with you at some point

**Comment by Hess3000** [comment]
Cool! Can I start another one?

**Comment by tansaku** [comment]
@Hess3000 in principle - would you like to look into this time failure we're just getting https://github.com/AgileVentures/WebsiteOne/issues/2330

Are you comfortable with sorting out the files for this PR?  There's a related rake task - https://github.com/AgileVentures/WebsiteOne/blob/develop/CONTRIBUTING.md#acceptance-tests-and-caching will you try yourself before we can look at it together?  were you hoping to book something with me later this week?

**Comment by Hess3000** [comment]
So I have just tried to sort the extra files out:

1. Delete files from features/support/fixtures/
2. Re-checking out ( via git checkout features/support/fixtures/) - ? this step
3. Rake vcr_billy_caches:reset
4. Re-run cucumber test and they pass green
5. Push up to github

So I now still have lots of new files gain and I'm not sure if thats correct.

Also a little confused about: 'git checkout features/support/fixtures/' actually means / does.

This maybe simple and I'm over complicating things in which case probable best left for our chat.
Regarding the chat - the only space on your calendar is for Thursday at 11 which I cannot do so I'll try the week after.

----

ISSUE 2330

Yes I'd like to start looking at this because I really need keep working on things in the meantime.

**Comment by tansaku** [comment]
So `rake vcr_billy_caches:reset` does two things:

1. Delete files from features/support/fixtures/
2. Re-checking out ( via git checkout features/support/fixtures/) <-- this puts the correct files back from the git repo so that you can see them locally again

so if you do `rake vcr_billy_caches:reset` then you don't need to do the two manual steps.

However these are all thing to do *before* committing.  Doing them now after you have already committed the files will not have any effect (as you experienced).

Apologies for not explaining that better before.  In this situation what we'll have to do is start again with a new pull request in order to clean things up.  I think this is a flaw in our documentation and process, which we need to improve.  Please don't feel you are doing anything wrong.  In the ideal world we'd get everything set up do we didn't have sharp edges like this ...

**Comment by tansaku** [comment]
btw, sounds like @nisevi fixed #2330 already - but other ones that you might look at include:

* https://github.com/AgileVentures/WebsiteOne/issues/2313
* https://github.com/AgileVentures/WebsiteOne/issues/2297
* https://github.com/AgileVentures/WebsiteOne/issues/2296

but ideally these should be voted on and discussed, fleshed out etc.

I've started votes in the #websiteone channel so can chat there ....

**Comment by Hess3000** [comment]
Erm.. I think I should not have merged.

What I was trying to do was update the pull request I originally sent with my updated branch

**Comment by tansaku** [comment]
@Hess3000 yes, ideally you wouldn't have done, but not the end of the world :-)

**Pull request merged**
