### PR TITLE
989 filter events by project ui

### LINKED ISSUE #989: UI for filtering by project
As a user
So that I can participate in events specific to the project I care about
I would like to filter the events list by project

### PR DESCRIPTION
**Pull request by mtc2013**
fixes #989

### CODE REVIEW

**Comment by diraulo** [comment]
thanks @mtc2013. A few comments

- Perhaps add an 'all' option in the select list to view all events again. Maybe this can be taken care of as part of a separate issue (if relevant at all)

- I think it would be better to make use of an inline form here:
screenshot 2016-04-18 11 32 24

see http://getbootstrap.com/css/#forms-inline

**Comment by diraulo** [comment]
screenshot 2016-04-19 10 27 31

@mtc2013 @tansaku how about having the button on the right? feels more practical

**Comment by tansaku** [comment]
maybe if we right align the text in the dropdown ... and thanks for those links to inline bootstrap forms - didn't see your comment until after we'd used the rows approach - the inline form look will probably be nicer ... I want to refactor some of the code as well.

**Comment by tansaku** [comment]
hi @diraulo - we tried putting the button on the other side, but then we felt it needed a label, but then we couldn't get the label to vertical align nicely, so we ended up switching back ...

We did pull in the form-inline stuff and refactored the controller code ...

**Comment by tansaku** [comment]
@diraulo updated based on input from kickoff meeting - hoping this is good to go now

**Pull request merged**
