### PR TITLE
Update gems for security alerts

### LINKED ISSUE #1651: Five Security Alerts Open
Gemnasium is reporting 5 vulnerabilities, so gems should be updated.

https://gemnasium.com/github.com/AgileVentures/WebsiteOne

### PR DESCRIPTION
**Pull request by mattlindsey**
fixes #1651

### CODE REVIEW

**Comment by tansaku** [comment]
I'm trying to check this locally, but hitting this error:

```Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.14.0
/Users/tansaku/.rvm/rubies/ruby-2.3.1/bin/ruby -r ./siteconf20170518-16412-1sg0pel.rb extconf.rb
sh: qmake: command not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/tansaku/.rvm/rubies/ruby-2.3.1/bin/$(RUBY_BASE_NAME)
	--with-gl-dir
	--without-gl-dir
	--with-gl-include
	--without-gl-include=${gl-dir}/include
	--with-gl-lib
	--without-gl-lib=${gl-dir}/lib
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
Command 'qmake LIBS\ \+\=\ -L/usr/local/opt/libyaml/lib\ -L/usr/local/opt/readline/lib\ -L/usr/local/opt/libksba/lib\ -L/usr/local/opt/openssl/lib' not
available

extconf failed, exit code 1

Gem files will remain installed in /Users/tansaku/.rvm/gems/ruby-2.3.1/gems/capybara-webkit-1.14.0 for inspection.
Results logged to /Users/tansaku/.rvm/gems/ruby-2.3.1/extensions/x86_64-darwin-15/2.3.0/capybara-webkit-1.14.0/gem_make.out

An error occurred while installing capybara-webkit (1.14.0), and Bundler cannot continue.
Make sure that `gem install capybara-webkit -v '1.14.0'` succeeds before bundling.
```

**Comment by tansaku** [comment]
I note this was the error that prompted the change of the slack service test:

```
 1) SlackService.post_hangout_notification sends a post request to the agile-bot with the proper data
     Failure/Error: expect(req.body).to eq "title=MockEvent&link=mock_url&type=PairProgramming&host_name=random&host_avatar=#{gravatar}&project=edx"
     
       expected: "title=MockEvent&link=mock_url&type=PairProgramming&host_name=random&host_avatar=https%3A%2F%2Fwww.gravatar.com%2Favatar%2F47548e7f026bc689ba743b2af2d391ee%3Fd%3Dretro&project=edx"
            got: "title=MockEvent&link=mock_url&type=PairProgramming&host_name=random&host_avatar=https%3A%2F%2Fwww.gravatar.com%2Favatar%2F47548e7f026bc689ba743b2af2d391ee%3Fd%3Dretro&project"
     ```

**Comment by tansaku** [comment]
using https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#macos-sierra-1012-el-capitan-1011-and-yosemite-1010 to fix my OSX issue ...

**Comment by tansaku** [comment]
okay, so @mattlindsey the test errors need to be fixed by adjusting the collaborating objects.

so, for example

```
hangout.project = Project.create( slug: 'edx')
```

needs to become 

```
hangout.project = Project.create( slug: 'edx', title: 'Edx', description: 'hmm', status: 'active')
```
on line 17 of slack_service_spec.rb

the problem is that the Project object wasn't being created due to validation issues.

the gem upgrade made the webmock tests tighter which exposed a problem in our collaboration objects - it's there that we need the fix - not just adjusting the expectation to match the  POST UR

**Comment by mattlindsey** [comment]
@tansaku I made the change to adjust the line 'hangout.project = Project.create...', so hopefully this PR is ready now.

**Pull request merged**
