### PR TITLE
Update 403.html

### PR DESCRIPTION
**Pull request by AdvaitT17**
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tansaku** [comment]
thanks @AdvaitT17 - can you post a screenshot of how this would change things?

**Comment by AdvaitT17** [comment]
@tansaku you can check that when you merge my request...

**Comment by tansaku** [comment]
@AdvaitT17 I can - but I am extraordinarily busy running an international charity and putting food on the table for my kids - I realise you that you might well be similarly busy (I guess no one has much spare time) - I was hoping to nudge you to check the change on a variety of screen sizes and post the screen shots here, but if you prefer to push the work onto me I guess I can get to it at some point ...

You haven't motivated the change by including anything about what you are fixing or sorting in the description, which would be helpful ...

**Comment by mattwr18** [comment]
I have pulled down this code to take screenshots, is there a specific path I can expect to get a 403 error @tansaku @AdvaitT17?

**Comment by tansaku** [comment]
@mattwr18 thanks for helping out here - 403 is a forbidden error, but I am not sure when we would get one in our app.  There's some more details on 403s here: https://airbrake.io/blog/http-errors/403-forbidden-error

maybe we would get it when the github oauth sign is failing or something?

@AdvaitT17 did you actually see the error at some point?

**Pull request merged**
