### PR TITLE
Trying to increase cucumber javascript test robustness

### PR DESCRIPTION
**Pull request by tansaku**
hmm CI not running on this kind of pull request ... ah it is now ...

### CODE REVIEW

**Comment by diraulo** [comment]
@tansaku I'm happy to merge this

**Comment by tochman** [comment]
I'd love to have this merged in. After the recent updates I'm getting a new kind of errors when running cucumber
```
  Scenario: User has complete profile not from home page                   # features/remind_complete_profile.feature:43
    Given I exist as a user                                                # features/step_definitions/user_steps.rb:24
    And I visit "projects"                                                 # features/step_definitions/basic_steps.rb:60
    When I sign in with valid credentials                                  # features/step_definitions/user_steps.rb:63
    Then I should not see "We've noticed that your profile is incomplete." # features/step_definitions/basic_steps.rb:185
      Address already in use - bind(2) for "127.0.0.1" port 3010 (Errno::EADDRINUSE)
      /Users/thomas/.rvm/gems/ruby-2.2.2/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:33:in `initialize'
      /Users/thomas/.rvm/gems/ruby-2.2.2/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:33:in `open'
      /Users/thomas/.rvm/gems/ruby-2.2.2/gems/poltergeist-1.5.1/lib/capybara/poltergeist/web_socket_server.rb:33:in `start_server'
...
```

**Comment by tochman** [comment]
Oh.. Am I missing something? Is this the same as #777 ?

**Comment by diraulo** [comment]
@tochman I will merge this. 

Do you have something running on port 3010? 
```shell
Address already in use - bind(2) for "127.0.0.1" port 3010
```

**Comment by tochman** [comment]
No, just the tests. I ran `bundle update poltergaist` to get the latest. Looks much better now...

**Comment by tochman** [comment]
What a mess! ;-)

**Pull request merged**
