### PR TITLE
Move to headless chromedriver

### LINKED ISSUE #2589: Use headless chromedriver
As a way to move on from capybara-webkit and phantom js

### PR DESCRIPTION
**Pull request by mattwr18**
Fixes #2589

### CODE REVIEW

**Comment by tansaku** [comment]
wonderful - thanks @mattwr18

**Comment by mattwr18** [comment]
hey @tansaku, I was still testing this to see if we can remove our reliance on phatomjs as well... should have put a [wip]

**Comment by tansaku** [comment]
@mattwr18 ah oops - all the tests passed ... what remains to be done?

**Comment by mattwr18** [comment]
well, I started another ticket to remove phantomjs and Poltergeist, and I realized that I hadn't actually configured the `Capybara.rb` file, so maybe Cucumber wasn't using Selenium even... I am playing around on another branch... Also, would need to update READMEs and stuff...

**Comment by tansaku** [comment]
we can emit an anti-PR to remove if necessary ...

**Pull request merged**
