### PR TITLE
Add create event link to navbar

### LINKED ISSUE #822: Creating an event needs to be more obvious
Having to navigate to the events page and then click the little button on the top right is not obvious.  I would include create event in the drop down menu, and also possibly add something somewhere that says like "Let's pair program now" or something.

### PR DESCRIPTION
**Pull request by marianmosley**
Fixes #822

### CODE REVIEW

**Comment by mtc2013** [comment]
@tansaku @diraulo ready for feedback

**Comment by diraulo** [comment]
@mtc2013 @marianmosley is the following test passing for you? Keeps failing on CI

```
cucumber -p semaphoreci features/newsletter_form.feature:49
```

**Comment by mtc2013** [comment]
@diraulo i think i got a fix locally.  will push if works out.

**Comment by mtc2013** [comment]
@diraulo fix is in

**Pull request merged**
