### PR TITLE
759 allow non pivotal links in project management

### LINKED ISSUE #759: Accept JIRA, waffle, and links in project attributes for project management tools
Imported from https://www.pivotaltracker.com/story/show/82015510

From Nick: " The OSRA project has recently transitioned to using JIRA rather than Pivotal Tracker for our project management. Since only Pivotal URIs are valid on AV, we cannot update the project page to reflect the change, and even if we could the page would remain hard-coded to display the text "OSRA on PivotalTracker". Is there any way to resolve this?"

**NOTE**
This does not include a separate JIRA tab similar to what we have for Pivotal Tracker

### PR DESCRIPTION
**Pull request by touchps**
Fixes #759 

Few notes:

- Existing pivotaltracker_url field is used for alternate project trackers. This will work for now, but will need schema change in future for semantic purpose.
- On Activity tab, message now displays `Stories are not supported for issue tracker type used by project` for non PT trackers
- Validation is a bit relaxed. There will be no validation for non PT URLs, but will work as usual for PT.
- One of the feature test for invalid PT links is removed.
- On create project page, label has been changed to `Issue tracker link`.

The plan is to eventually add validation after refactoring the code for non PT links, but the immediate emphasis is on delivering the solution (based on suggestions for @tansaku).

### CODE REVIEW

**Comment by touchps** [comment]
Need some more changes. Some view specs are failing, which i thought are not in consideration anymore.

**Comment by touchps** [comment]
All tests passing. Removing validations for pivotal tracker url was not very desirable experience. Need some suggestion on text change for `<Project> on Pivotal Tracker` in project show page.

**Comment by diraulo** [comment]
@touchps please take a look at the merge conflicts here 😉

**Comment by touchps** [comment]
@diraulo this merge conflict was a bit confusing. Spotting the changes from previous commits helped. Conflicts resolved.

**Comment by tansaku** [comment]
great work @touchps 

@diraulo this is looking good to me ...

**Pull request merged**
