### PR TITLE
remove links to youtube

### PR DESCRIPTION
**Pull request by alejandrobabio**
This PR is related to the task: https://www.pivotaltracker.com/story/show/80154166
Remove the connect/disconnect to youtube account at edit registration page, and its callback actions.

### CODE REVIEW

**Comment by tansaku** [comment]
awesome thanks @alejandrobabio - @diraulo can you take a look - I'm off today and won't be able to review till Monday ...

**Comment by diraulo** [comment]
@tansaku sure thing

**Comment by diraulo** [comment]
Thanks @alejandrobabio.
@tansaku looks good to me.

**Comment by tansaku** [comment]
yeah @diraulo looking pretty good - I guess we should just run it locally on our machines to rule out any unexpected side effects ...

**Comment by tansaku** [comment]
@diraulo @alejandrobabio I'm just trying to double check this locally, but I have no users in my local WSO database, and the seeds file doesn't appear to make any ... I guess I should take a dump of the live database perhaps ...?

**Comment by alejandrobabio** [comment]
I did try make it fail at `websiteone-develop.herokuapp.com`, but google is responding with: "The redirect URI in the request: http://websiteone-develop.herokuapp.com/auth/gplus/callback did not match a registered redirect URI."

With this callback in place, I think we can see the issue at develop, and check how is working the rm_obsolete_yt branch, after push it to heroku develop. And then, you can move the develop branch again to heroku.

**Comment by tansaku** [comment]
Fixes #756

**Comment by diraulo** [comment]
:+1: :shipit:

**Pull request merged**
