### PR TITLE
adds basic stripe setup

### LINKED ISSUE #754: Set up payment framework for premium membership
investigate use of stripe or gocardless for http://www.agileventures.org/pricing

TODO
* [x] pull in puffing billy 
* [x] sort out VCR
* [x] create an acceptance test
* [ ] can we filter sensitive data from puffing billy (https://github.com/oesmith/puffing-billy/issues/143)
* [ ] TDD changes to model for upgrading to premium

### PR DESCRIPTION
**Pull request by tansaku**
fixes #754

### CODE REVIEW

**Comment by diraulo** [comment]
@tansaku we now have this failing because the number of commits has changed from 394 to 396.

```shell
Failing Scenarios:
cucumber -p semaphoreci features/users/github_commit_count.feature:19 # Scenario: Displays commit counts on user profile page

Scenario: Displays commit counts on user profile page # features/users/github_commit_count.feature:19
    Given I am on "profile" page for user "Bryan"       # features/step_definitions/user_steps.rb:280
    Then I should see "Contributions"                   # features/step_definitions/basic_steps.rb:189
    And I should see "WebsiteOne - 394"                 # features/step_definitions/basic_steps.rb:189
      expected to find text "WebsiteOne - 394" in "Log in Sign up About Projects Members Articles Events Upcoming events Past scrums Past events Getting started Bryan Yap Member for less than a minute yggie About Skills Projects Activity About me Nam qui velit totam qui ut tenetur. Skills & Technologies molestiae quo saepe tempora Project Involvement WebsiteOne Contributions WebsiteOne - 396 commits Bryan Yap has no publicly viewable Youtube videos. × Contact Bryan Yap Close ×Close Set status Ready to pair Doing code review Plz, do not disturb Waiting for next scrum... Sleeping at my keyboard Close Learn More About Us Getting Started Dashboard Social Facebook Twitter Our Sponsors Makers Academy AirPair Becoming a sponsor AgileVentures - Crowdsourced Learning Contact us Send a traditional email to info@agileventures.org." (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:191:in `/^I should( not)? see "([^"]*)"$/'
      features/users/github_commit_count.feature:22:in `And I should see "WebsiteOne - 394"'
    HTML screenshot: /home/runner/WebsiteOne/tmp/capybara/screenshot_2016-03-23-17-46-05.659.html
```

I've now merged your PR with puffing billy config, perhaps that will fix this problem for good :)

**Comment by tansaku** [comment]
@diraulo aha - I think it might require some VCR related work for that particular case - do we have a ticket for that Bryan's commits issue?  I couldn't see one so I added #945

**Comment by tansaku** [comment]
hmm, stripe not as stable as we had hoped - running locally for me, but we got this error:

```
    And I fill in appropriate card details     # features/step_definitions/charge_steps.rb:1
      Unable to find field "cc-exp" (Capybara::ElementNotFound)
      ./features/step_definitions/charge_steps.rb:7:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/charge_steps.rb:3:in `/^I fill in appropriate card details$/'
      features/charge_activity.feature:9:in `And I fill in appropriate card details'
```

could be a js timing issue?

**Comment by tansaku** [comment]
@diraulo so this is a little more complicated - the stripe system detects the browser region encoding (e.g. en_gb or en_us etc.) and makes different requests on that basis - @mtc2013 just added an extra cached file to cope with en_us.

Also to run this test requires some keys to be set in the environment - so if you want this to pass locally for you you'll need those.  Am thinking to setup dotenv for that perhaps ... We'll also have to look at your locale settings - or we'll find a way to lock down the capybara locale ...

**Pull request merged**
