### PR TITLE
seeding premium users and events with current date

### LINKED ISSUE #2718: Improve our seed file
We can add more users, subscriptions, plans

### PR DESCRIPTION
**Pull request by dkuku**
In development there's no easy way to test premium user features
Also updated events to have current date - now we can see them in the calendar.

fixes #2718

#### Description

Updated seed file to generate 4 premium users all with password: premium123
and emails: 
 - premium@premi.um
 - premiummob@premi.um
 - premiumf2f@premi.um
 - premiumplus@premi.um

This might need adding to the docs

#### How Has This Been Tested?

I've run the file a couple of times when testing docker updates

#### Screenshots (if appropriate):
2018-10-18-025540_1920x2130_scrot

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tansaku** [comment]
hi @dkuku - this looks good - I never run the seeds file myself, so this should probably be checked by @mattwr18 or someone else who runs that locally

the failure in the semaphoreci looks like an intermittent one that we're tagging out so I think we can ignore that for the time being

**Comment by mattwr18** [comment]
This looks really good @dkuku everything is much improved... maybe run the static pages job to pull in the membership-plans like we discussed?

**Comment by tansaku** [comment]
@dkuku is this ready to merge?

**Comment by tansaku** [comment]
@dkuku is this ready to merge? - also are those changes to the gemfile intentional?

**Comment by dkuku** [comment]
You cak skip the Gemfile changes (last commit) - I don't know how to get rid of it, I added this because my branch was behind develop but it was a bad idea.

**Comment by dkuku** [comment]
I updated it using `git push --force` and for the first time it did not break anything

**Comment by mattwr18** [comment]
I guess this can be merged @tansaku, it is "falling" in total coverage due to these lines 
```
card = customer.sources.create(card: stripe_token(params))
card.save
customer.default_card = card.id
customer.save
```
not being covered by tests, but I think they are, just maybe network failure at that moment, as we have discussed on other `PR`s?

**Pull request merged**
