### PR TITLE
trying to clean out our acceptance tests

### LINKED ISSUE #806: intermittent js failure?
```
 Scenario: Insert media model rejects badly formatted youtube links                                      # features/documents.feature:170
    Given I am logged in                                                                                  # features/step_definitions/user_steps.rb:19
    And I am using the Mercury Editor to edit document "Guides"                                           # features/step_definitions/mercury_steps.rb:27
    And I am focused on the "document body" within the Mercury Editor                                     # features/step_definitions/contained_search_steps.rb:33
    And I click on the "Insert Media" button within the Mercury Toolbar                                   # features/step_definitions/contained_search_steps.rb:33
    And I fill in "YouTube URL" with "https://www.youtube.io/watch?v=foo" within the Mercury Editor Modal # features/step_definitions/contained_search_steps.rb:33
    And I click "Insert Media" within the Mercury Editor Modal                                            # features/step_definitions/contained_search_steps.rb:33
    Then I should see "is invalid" within the Mercury Modal                                               # features/step_definitions/contained_search_steps.rb:33
      expected to find text "is invalid" in "Insert Media (images and videos)× Images URL Videos YouTube URL Vimeo URL Options Alignment Float Width Height" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:167:in `/^I should( not)? see "([^"]*)"$/'
      ./features/step_definitions/contained_search_steps.rb:41:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/contained_search_steps.rb:41:in `/^(.*) within the (.*)$/'
      features/documents.feature:177:in `Then I should see "is invalid" within the Mercury Modal'
    And the Mercury Editor modal window should be visible                                                 # features/step_definitions/mercury_steps.rb:61
```
Failing Scenarios:
cucumber features/documents.feature:170 # Scenario: Insert media model rejects badly formatted youtube links

### PR DESCRIPTION
**Pull request by tansaku**
fixes #806

### CODE REVIEW

**Comment by tansaku** [comment]
hmm, so for some reason the jasmine tests are now completely hanging on this branch ... happening on CI and locally ...

```
→ rake jasmine:ci
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
Puma 2.11.3 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:52672
Waiting for jasmine server on 52672...
jasmine server started
```

are they relying on some part of the cucumber config perhaps?

**Comment by tansaku** [comment]
tests all pass in non-ci mode:

**Comment by yggie** [comment]
@tansaku continuing the our conversation on the cleanroom approach, I think it is a good idea to figure out what we really need, no doubt this will be very time consuming… It would be a great way to eliminate duplication and redundant code! However I am not sure if we can avoid switching JS drivers completely… Each driver has its own advantages and disadvantages, by switching JS drivers, we keep the best of both worlds. Although personally I don’t know how much `poltergeist` has advanced since the last time I used it, it may well be good enough for all the scenarios. So I think we should continue exploring this avenue, perhaps on top of the fixes I did for the [Ruby upgrade](https://github.com/AgileVentures/WebsiteOne/pull/970)? :grin:

**Comment by tansaku** [comment]
Poltergeist works for everything we have on LocalSupport, but there's more JS functionality in WSO, however to be honest I don't think we are actually using anything other than poltergeist in WSO - I think there's just some funny switching between it and the default and some debug settings.

We could pull your ruby upgrade in here, but it makes me a little nervous, in that we're trying to introduce the minimum changes ... recent Ruby upgrades do seem to be quite benign though ... and yet this is a tricky issue we're juggling ...

I probably can't put much more time into this until next week anyway - if you want to play with ruby upgrading a copy of this branch do be my guest, but I think the critical next experimental step (in my mental logic) is to pull in the documents.feature into this branch and see if it plays nicely with scrums.feature ... feel free to try that if you fancy :-)

**Comment by yggie** [comment]
@tansaku we could merge the Ruby upgrade as a separate thing, and build on top of that here, not sure why they have to go together… Obviously there will be some conflicts, but it is something we can manage…

**Comment by tansaku** [comment]
@yggie - yes that's an idea - I've just been experimenting with a merge of your ruby upgrader to the cleanroom locally.  It would be great to get the work you've done here merged in quickly.  

I note that this change introduces a lot of new deprecation messages such as:

```
DEPRECATION WARNING: Looking up factories by class is deprecated and will be removed in 5.0. Use symbols instead and set FactoryGirl.allow_class_lookup = false. (called from block (2 levels) in <top (required)> at /Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/spec/controllers/projects_controller_spec.rb:17)
DEPRECATION WARNING: Looking up factories by class is deprecated and will be removed in 5.0. Use symbols instead and set FactoryGirl.allow_class_lookup = false. (called from block (2 levels) in <top (required)> at /Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/spec/controllers/projects_controller_spec.rb:17)
```

and 

```
Unused parameters passed to Capybara::Queries::SelectorQuery : ["/pair"]
```

I've been through and cleaned these things up in LocalSupport before, so it's no big deal, but I do think it's important to keep the test output clear of these messages.  I have the following set in my bashrc so that I can quickly run all the tests in progress format like so:

```
alias ber="bundle exec rspec -fp"
alias bec="bundle exec cucumber --format progress"
```

which exposes the extra message output very heavily (as well as allowing the tests to run slightly faster).  And keeping those extra messages to a minimum makes it easier to notice if an important one pops up (and avoids confusing newcomers).

I also get three failures locally in the rspecs after the merge:

```
  1) User should reject email addresses identical up to case
     Failure/Error: expect(build_stubbed(:user, email: subject.email)).not_to be_valid
       expected #<User id: 1018, email: "adalberto@carter.io", encrypted_password: "$2a$04$iCebrh/GKudRN6H5DHzt2.UUrEtIW5ytBidlJ0bm9.4...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: nil, updated_at: nil, first_name: "Erling", last_name: "Jenkins", display_email: nil, youtube_id: nil, slug: "erling-jenkins", display_profile: true, latitude: nil, longitude: nil, country_name: nil, city: nil, region: nil, youtube_user_name: nil, github_profile_url: nil, display_hire_me: nil, bio: "Aliquid molestias sint quia.", receive_mailings: true, karma_points: 0, country_code: nil, timezone_offset: nil, status_count: 0> not to be valid
     # ./spec/models/user_spec.rb:33:in `block (2 levels) in <top (required)>'

  2) User should reject duplicate email addresses
     Failure/Error: expect(build_stubbed(:user, email: user.email)).not_to be_valid
       expected #<User id: 1019, email: "claudie.marvin@jerdeterry.name", encrypted_password: "$2a$04$dpfXhsdW3i/ICnJNBA1chuXZZGt6MHXrgZJU3ReEkgt...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: nil, updated_at: nil, first_name: "Nickolas", last_name: "Reynolds", display_email: nil, youtube_id: nil, slug: "nickolas-reynolds", display_profile: true, latitude: nil, longitude: nil, country_name: nil, city: nil, region: nil, youtube_user_name: nil, github_profile_url: nil, display_hire_me: nil, bio: "Maxime labore vel dolores eaque debitis.", receive_mailings: true, karma_points: 0, country_code: nil, timezone_offset: nil, status_count: 0> not to be valid
     # ./spec/models/user_spec.rb:27:in `block (2 levels) in <top (required)>'

  3) User should be invalid with an invalid email address
     Failure/Error: expect(build_stubbed(:user, email: 'user@foo,com')).to_not be_valid
       expected #<User id: 1026, email: "user@foo,com", encrypted_password: "$2a$04$ebmUHE758Topp4KiFJOWpOrs23SndqsVq4IvbFi8NSX...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: nil, updated_at: nil, first_name: "Cicero", last_name: "Brekke", display_email: nil, youtube_id: nil, slug: "cicero-brekke", display_profile: true, latitude: nil, longitude: nil, country_name: nil, city: nil, region: nil, youtube_user_name: nil, github_profile_url: nil, display_hire_me: nil, bio: "Repellat voluptas optio aspernatur.", receive_mailings: true, karma_points: 0, country_code: nil, timezone_offset: nil, status_count: 0> not to be valid
     # ./spec/models/user_spec.rb:18:in `block (2 levels) in <top (required)>'

Finished in 47.66 seconds (files took 9.62 seconds to load)
826 examples, 3 failures, 1 pending

rspec ./spec/models/user_spec.rb:30 # User should reject email addresses identical up to case
rspec ./spec/models/user_spec.rb:25 # User should reject duplicate email addresses
rspec ./spec/models/user_spec.rb:17 # User should be invalid with an invalid email address
```

did you ever see these on your branch?

I also got an error from one cucumber step definition that I think comes from the ruby upgrade ... but I fixed that up ...

My concern here is that fixing up these messages and these errors might be a distraction for @mtc2013 and I getting to the bottom of the intermittent JS failures.  Although perhaps we'll never get them 100% fixed and we risk burning too much time on something that ultimately can't be fixed.

That said - from @diraulo's assessment your branch seems more stable than where we were before ...

Anyway, if you have any insight on the rspec failures above that'd really help get your changes merged in quickly ...

**Comment by yggie** [comment]
@tansaku no I have not come across those errors… Running them locally doesn’t bring up those deprecation messages either… Very strange…

**Comment by tansaku** [comment]
I've pushed up into a branch and a PR in case you want to see more @yggie https://github.com/AgileVentures/WebsiteOne/pull/972

I note that there's also a fair amount of noise here related to caching (particularly billy) because we've deleted a lot of stuff, and your run isn't vcr sandboxed yet, so it might make more sense to merge your branch and then completely start our cleanroom operation again on top of yours ... or we leave the ruby 2.3 upgrade for the moment and focus on completing the cleanroom operation ...

**Comment by tansaku** [comment]
@yggie @mtc2013 @diraulo @freeranger would be great if any/all of you could run this branch on your local machines and see if it is stable.

It contains several of the regularly failing cucumber scenarios.  The env setup is completely redone here and they are fully sandboxed (or should be).  If any of you can get this branch to fail with an intermittent js failure that would be very good to know as it will help tell us whether to continue pushing in this direction to get a solution via the cleanroom approach.

Also, if when doing git status after cuke runs you see any changes in the vcr or billy fixtures that would be great to know as it would indicate the sandboxing is not yet complete.

**Comment by freeranger** [comment]
Apart from a bunch of deprecation warnings, all saying:
`[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.`
I have run the cucumber tests literally a dozen times and they have succeeded every time.
However with the current tests, I could run them that many times and they would pass too - it tends to be the CI build that fails rather than the local build IME, so all I can really say is they don't seem any worse at this stage.   I will run them a few more times over the next few hours and see if anything pops up.

git status is clean so the sandboxing would seem complete.

**Comment by freeranger** [comment]
Another dozen runs and it's still all good.
Also have run the rspec tests about a dozen times too and they also pass

**Comment by tansaku** [comment]
@freeranger awesome - that's really super helpful, and yes, absolutely it all means nothing if they don't also regularly pass on CI.   

That's an annoying aspect of semaphore that we can't seem to re-run the build if it's successful (unlike travis).  I'm tempted to pull in an intentional fail to allow for multiple runs on semaphore ...

The annoying thing here is that sandboxing each feature is a little time-consuming - although hopefully it should get faster and faster as we work through.  I really want to get this fixed.   We've got a combination of changes (often dangerous), i.e. sandboxing, gem updates, and simplified cucumber/poltergeist/phantomjs config.

Even if it's not a complete success the combination of these things should give an overall increase in stability, but we need to get it pulled in soon in order to get back to working on things that will support the MOOCers for the next run!

**Comment by mtc2013** [comment]
@tansaku to see the diff of deleted files on the command line, you can run:
git diff origin/develop --diff-filter=D --summary

**Pull request merged**
