### PR TITLE
Sunday event shows as a Saturday event

### PR DESCRIPTION
**Pull request by abdellani**
#### Issue addressed

https://github.com/AgileVentures/WebsiteOne/issues/3099
fixes #

### CODE REVIEW

**Comment by abdellani** [comment]
@NickSchimek 
I'm still getting the same error with timezone.
```bash
  @javascript
  Scenario: Creating a weekly event with a different time-zone # features/events/create_events.feature:154
    Given the date is "2019-05-19"                             # features/step_definitions/event_steps.rb:127
    Given the user is located in "Africa/Algeria"              # features/step_definitions/event_steps.rb:516
    Given I fill in event field:                               # features/step_definitions/basic_steps.rb:159
      | name        | value         |
      | Name        | Daily Standup |
      | Start Date  | 2019-05-19    |
      | Start Time  | 00:30         |
      | Description | we stand up   |
    And I select "Algiers" from the time zone dropdown         # features/step_definitions/event_steps.rb:164
    And I select "Repeats" to "weekly"                         # features/step_definitions/basic_steps.rb:278
    And I check "Sunday"                                       # features/step_definitions/basic_steps.rb:335
    Then the event is set to end sometime                      # features/step_definitions/event_steps.rb:25
    And I fill in event field:                                 # features/step_definitions/basic_steps.rb:159
      | name     | value      |
      | End Date | 2019-06-01 |
    And I click the "Save" button                              # features/step_definitions/basic_steps.rb:103
    Then I should see "Event Created"                          # features/step_definitions/basic_steps.rb:211
    Then I should see "Saturday"                               # features/step_definitions/basic_steps.rb:211
      expected to find text "Saturday" in "Anders Persson \nABOUT\nPROJECTS\nMEMBERS\nPREMIUM\nEVENTS \nGETTING STARTED\nDaily Standup\nwe stand up\nEvent type: PairProgramming\nEvent for: All\nEvent Actions \nNext scheduled event:\nSunday, May 19, 2019 \n23:30-00:00 (UTC) Africa/Abidjan\nOccurs weekly at the specified times\ncreated by:\nAnders Persson\n2019-05-19\nAttendCannot Attend\nNo previous instances of this event\nLearn more about Scrums\nLearn More\nAbout Us\nGetting Started\nDashboard\nOpportunities\nBlog\nPress Kit\nSocial\n Facebook\n Twitter\nOur Sponsors\nStandup Bot\nCraft Academy\nMooqita\nBecoming a sponsor\nAgileVentures - Crowdsourced Learning\nContact us\nSend a traditional email to info@agileventures.org.\nWe are a Charitable Incorporated Organisation (CIO) in the UK. Ref #1170963" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:213:in `/^I should( not)? see "([^"]*)"$/'
      features/events/create_events.feature:172:in `Then I should see "Saturday"'
    And reset timezone to UTC                                  # features/step_definitions/event_steps.rb:520
WARN: Screenshot could not be saved. `page.current_path` is empty.

Failing Scenarios:
cucumber features/events/create_events.feature:154 # Scenario: Creating a weekly event with a different time-zone

1 scenario (1 failed)
17 steps (1 failed, 1 skipped, 15 passed)
0m16.383s
```

**Comment by NickSchimek** [comment]
OK. I'm getting the test to work, but there are some other strange things happening.

I created a new test file and put this in it.

```
@javascript
Feature: Events with TimeZones
  As a user
  So that events are displayed with the correct date
  I would like to view events with correct time zone information

  Scenario: Creating a weekly event with a positive UTC time-zone difference
    Given I have logged in
    Given the user is located in "Africa/Algiers"
    And I am on Events index page
    When I click "New Event"
    And the date is "2019-05-19"
    When I fill in event field:
      | name        | value                |
      | Name        | Daily Standup Africa |
      | Start Date  | 2019-05-19           |
      | Start Time  | 00:30                |
      | Description | we stand up          |
    And I select "Africa/Algiers" from the time zone dropdown
    And I select "Repeats" to "weekly"
    And I check "Sunday"
    And I fill in event field:
      | name     | value      |
      | End Date | 2019-06-01 |
    And I click the "Save" button
    Then I should see "Event Created"
    And I should see "Sunday"
```

And it fails as it should saying that `Sunday` can't be found because `Monday` is being displayed.

Screenshot 2019-05-29 00 15 13

I thought great! It's working, and so I added the second test for a negative time zone.

```
  Scenario: Creating a weekly event with a negative UTC time-zone difference
    Given I have logged in
    Given the user is located in "America/Whitehorse"
    And I am on Events index page
    When I click "New Event"
    And the date is "2019-05-19"
    When I fill in event field:
      | name        | value         |
      | Name        | Daily Standup |
      | Start Date  | 2019-05-19    |
      | Start Time  | 22:30         |
      | Description | we stand up   |
    And I select "America/Whitehorse" from the time zone dropdown
    And I select "Repeats" to "weekly"
    And I check "Sunday"
    And I fill in event field:
      | name     | value      |
      | End Date | 2019-06-01 |
    And I click the "Save" button
    Then I should see "Event Created"
    And I should see "Sunday"
```

And it's failing as it should!!!! 

Screenshot 2019-05-29 00 18 01


Yeah!, but not so fast.

I run the whole test file, and the first test fails, but the second passes. I switch the order and it's the same the first one fails and the second passes. Run them individually and they both fail...

Setting the ENV['TZ'] is working when running tests individually, but failing when running tests consecutively. 
I tried resetting capybara session with: Capybara.current_session.driver.reset! before each test, but it didn't work. 

@tansaku do you have any ideas what might be happening here?

**Comment by NickSchimek** [comment]
Figured out what's happening. 
At initialization when Capybara starts Puma it loads the ENV['TZ']
Capybara doesn't restart it after it's been initialized so later changes to ENV['TZ'] has no affect.
Looks like we need a way to force restart it or a different solution.
Any suggestions @tansaku ?

**Comment by tansaku** [comment]
Hi @NickSchimek - tricky.  I seem to recall encountering something like this working with @mtc2013 when we initially sorted the timezones out - if I recall capybara ends up being locked to the timezone of the box that the tests are being run on, and ultimately I think we gave up trying to get the acceptance test to perfectly replicate what happens when the user does stuff.

It looks like you've got a bit further. Here's some of the posts I made at that time (which you may have already seen):

* https://github.com/teamcapybara/capybara/issues/1685
* https://stackoverflow.com/questions/19532425/how-to-stub-a-specific-timezone-for-capybara-testing
* https://groups.google.com/forum/#!topic/capybara-webkit/h5sG4SVEa7Y

but these may or may not be relevant now ...

Your suggestion of forcing puma to restart sounds like a good one.  I think the best approach might be to ask the question on the capybara ruby mailing list:

https://groups.google.com/forum/#!forum/ruby-capybara

Great work digging into this - sorry I haven't been following as closely as I might

**Comment by NickSchimek** [comment]
@abdellani Yes, I think we can proceed without the test case in place for now since we can run the test individually and verify. Do you have an implementation in mind to fix this?

**Comment by NickSchimek** [comment]
@abdellani I believe I now know what the root cause is that is causing the issue of the incorrect day.
I think it is an issue with persisting the incorrect day the repeating event occurs in the field `repeats_weekly_each_days_of_the_week_mask`. It seems we're persisting it according to the local timezone instead of the correct day for the UTC timezone, hence the time is correct, but the day is wrong.

**Comment by abdellani** [comment]
@NickSchimek 
Thanks for showing me how to write a correct scenario, I really thought that the additional step definitions for changing the timezone weren't doing their job.

As I mentioned [here](https://github.com/AgileVentures/WebsiteOne/issues/3099#issuecomment-477563912), to fix the problem we can work on `create_start_date_time` (or maybe on `transform_params`) to change a the day of the week before saving the new event.

**Comment by NickSchimek** [comment]
Ah cool. Looks like you were a step ahead of me. Thanks for working on this @abdellani

**Comment by abdellani** [comment]
I got the test passed using the following [method](https://github.com/AgileVentures/WebsiteOne/pull/3210/files#diff-3a4e95c1bc41d3110d2f9ac10064e79bR103) (sorry, the code is still dirty) which convert the days inside `transform_params` 

```ruby
  def check_days_of_week(event_params)
    # local timezone vs utc timezone
    offset= (DateTime.parse(params[:start_date]).wday - event_params[:start_datetime].wday)%7
    days=[]
    if offset==0
      return
    elsif offset==1 
      params["event"]["repeats_weekly_each_days_of_the_week"].each do |day|
        days<<Date::DAYNAMES[(Date.parse(day).wday-1)%7].downcase if day !=""
      end
    else
      params["event"]["repeats_weekly_each_days_of_the_week"].each do |day|
        days<<Date::DAYNAMES[(Date.parse(day).wday+1)%7].downcase if day !=""
      end
    end
    event_params["repeats_weekly_each_days_of_the_week"]=days
  end

```

**Comment by NickSchimek** [comment]
Nice work so far @abdellani - Let me know when this is ready for review and I will check it out at that time.

**Comment by abdellani** [comment]
@NickSchimek  
I think this will do the job, but in `semaphoreci` I see some errors that I'm not sure if they have a relationship with the new changes.

**Comment by NickSchimek** [comment]
Thanks @abdellani . This does look good and both tests are passing on my end, however let's revert the changes in the files `features/events/tmp_create_events.feature` and `features/step_definitions/event_steps.rb` , since it was shown that these tests can't be ran with other tests. It could be the `tmp_create_events.feature` is causing the other failing tests since it permanently alters the timezone, and it seems some tests depend on the timezone being UTC (Perhaps these need to be re-written in a future ticket so they're not dependent on the timezone).

**Comment by abdellani** [comment]
@NickSchimek  
There is only one test failing now.

**Comment by NickSchimek** [comment]
@abdellani That's great there is only one failure to deal with now. I just spun up the rails server, and sure enough the feature `Event creator can mention that they cannot attend` is no longer working. I'm not aware of how that feature was implemented, but took a quick look at it. 

It seems every time the `Attend` button is toggled it actually re-submits the event form, and on re-submit it's getting a validation error. I think it would be better to directly switch the boolean value of that field instead of re-submitting an entire event form. 

We'll need to get that failing test fixed before this can be merged.

**Comment by NickSchimek** [comment]
@abdellani @tansaku I figured out how to make the tests work. The `@javascript` should be removed. It's not required to run these tests and the tag is making the server initialize with the loaded env vars. Once that's removed we can manipulate the env vars without issue.

@abdellani Can you please put the two tests back in without the `@javascript` tag, and then add a hook to the config file to always revert the time back to UTC after each test is ran.

**Comment by NickSchimek** [comment]
@abdellani How is it going? I'm wondering if you are still interested in finishing this up?

**Comment by abdellani** [comment]
@NickSchimek  Sorry, I was busy with some personal projects.
I will dedicate some time for it this week.

**Comment by NickSchimek** [comment]
No worries, we all get busy. Just checking to see if you still wanted the ticket. Let me know if you'd like to pair on it at all.

**Comment by NickSchimek** [comment]
Hi @abdellani . I'd sure love to close this out. Where are we at with this?

**Comment by abdellani** [comment]
@NickSchimek  sure, let's work on it during the weekend.

**Comment by abdellani** [comment]
@NickSchimek  sure, can we work on it during the week-end ?

**Comment by NickSchimek** [comment]
FYI: Pushing up a refactoring to the tests. Currently all the tests are passing. The red x is due to two codeclimate failures.

**Comment by abdellani** [comment]
Hi @aonomike 
Can you please check if this branch is ready to be merged ?

**Comment by aonomike** [comment]
Hi @abdellani and @NickSchimek I was testing locally on your branch and seems that for me the Thursday event is displayed as Friday when I pick the America/Los Angeles Timezone 🤔 Not sure id this is what we were trying to fix?
Screen Shot 2020-01-02 at 4 47 17 PM

**Comment by abdellani** [comment]
Hi @aonomike 
Thanks for testing.
Can you please share with us the details of the input ?

**Comment by aonomike** [comment]
> Hi @aonomike
> Thanks for testing.
> Can you please share with us the details of the inputs ?

Hi @abdellani the time I used was `1840 HRS America/Los Angeles ` but in my eyes the behavior seems correct. Maybe @tansaku wants to have a look? otherwise I think I can merge tomorrow. Great job @abdellani and @NickSchimek.

**Pull request merged**
