### PR TITLE
link static pages to edit page

### LINKED ISSUE #2296: link static pages to place you need to go to edit them
i.e. the correct file on AgileVentures/AgileVentures repo

### PR DESCRIPTION
**Pull request by Hess3000**
#### Motivation and Context

fixes #2296 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Hess3000** [comment]
@tansaku I have tried to change some tab spacing on the static_pages_helper from but although I save them in my editor and push them up to here they do not change.

**Comment by Hess3000** [comment]
@tansaku sure I'll do a test for them tonight.

**Comment by tansaku** [comment]
great work getting the tests in @Hess3000 :-)

**Comment by tansaku** [comment]
I've edited the formatting a little - but this is all looking pretty solid - do you think it's ready to merge?

**Comment by Hess3000** [comment]
It looks like it should work but the cuke statement:   **Then 'Edit Page' should link to github edit page**,   doesn't seem to find the github target although it seems to confirm I'm on the required static page...

**Comment by Hess3000** [comment]
Ready from my end.
I can't seem to edit the indentation, if I edit it on my local branch and push it doesn't change here.

**Comment by tansaku** [comment]
@Hess3000 might be settings on your editor? which one are you using?

**Pull request merged**
