### PR TITLE
Install node dependencies, add docker instructions

### PR DESCRIPTION
**Pull request by mattwr18**
gets us a docker install process

### CODE REVIEW

**Comment by mtc2013** [comment]
@mattwr18 so I got this error about not finding the right javascript asset when firing up with the start script:

https://gist.github.com/mtc2013/7416c5cfe69c1c104692e100ce253303

Seems we're not compiling assets properly for the pipeline?

**Comment by mtc2013** [comment]
Btw, this is on my windows 10 machine.  I think it might be a windows specific issue with dos vs unix line endings.

**Comment by mtc2013** [comment]
@mattwr18 i just verified this as working on my macos

**Comment by mattwr18** [comment]
@mtc2013 I am all too familiar with that error you shared above!! I hadn't pinned it down to being Windows specific yet though. Need to scheduling a pairing session to work on this though and test it more with Windows cause I imagine it being extremely helpful for Windows developers.

**Comment by tansaku** [comment]
hi @mattwr18 did you want to amend the commit to include other authors:

https://help.github.com/articles/creating-a-commit-with-multiple-authors/
https://help.github.com/articles/changing-a-commit-message/

either way, just let me know when this is ready to be merged by removing the [WIP] from the title and requesting a review from me, then I can push it through ASAP

**Comment by mattwr18** [comment]
Hey @tansaku, yeah sorry I saw your message and definitely want to add a couple key people who commited to get this pushed through. I was traveling yesterday, but should be able to get to it today. 
Not sure if I should remove the WIP until we have it working on Windows... Gonna try to debug it today, don't have `Windows` though so maybe @mtc2013 can help me?

**Comment by tansaku** [comment]
@mattwr18 I think you can still remove the WIP before you get it working on windows, assuming that there is other stuff that needs merging in first that helps people who are not on windows

Work fixing things up for windows can always go in another PR :-)

**Comment by mtc2013** [comment]
@tansaku @mattwr18 i've opened a pr that fixes the windows issue to @mattwr18 repo.

**Comment by tansaku** [comment]
great work @mattwr18 @mtc2013 and everyone else involved - many thanks :-)

**Pull request merged**
