### PR TITLE
adjusts project main image sizes in listing and project page

### LINKED ISSUE #1709: project images too large?
project images are rather large on their main page:

and it looks particularly strange on the main projects page

Seems like a simple style setting of `width: 64px` or similar might improve this ...

### PR DESCRIPTION
**Pull request by tansaku**
fixes #1709

### CODE REVIEW

**Comment by tansaku** [comment]
So this might need further work but it now makes wikiedu look like this:



I should probably pull down the production data to check how all the projects look ...

**Comment by mattlindsey** [comment]
Rundfunk MITBESTIMMEN is rather large too

**Comment by mattlindsey** [comment]
New size might be too small for amount of detail in Rundfunk MITBESTIMMEN

**Comment by tansaku** [comment]
@mattlindsey yeah, I wonder if that image could go in a difference place like we have for LocalSupport

https://www.agileventures.org/projects/localsupport/documents/project-overview-localsupport

**Comment by roschaefer** [comment]
We can use a smaller image, I'll subscribe to this thread and have the image changed when this PR is merged.

**Comment by tansaku** [comment]
awesome - thanks @roschaefer ! :-)

**Comment by roschaefer** [comment]
I changed the image but I guess only `master` is deployed, right?

**Comment by tansaku** [comment]
@roschaefer it's on develop - moving slowly to master - hope to have it there later today

**Pull request merged**
