### PR TITLE
[WIP] admin rake tasks

### LINKED ISSUE #2814: rake tasks for premium admin actions
Each month the admin needs to review the Premium members and check that they are all in sync, i.e. the data on their plans etc. is all correct.

At the moment the Admin does this by using the rails console and some little notes on how to connect up accounts etc.  Ideally there would be an admin interface for this, but in the first instance a few rake tasks would allow us to get the ruby scripts in version control and could then be run on production from the command line a little more easily ...

### PR DESCRIPTION
**Pull request by tansaku**
Very early days for this one

#### Issue addressed

fixes #2814

### CODE REVIEW

**Comment by mattwr18** [comment]
Can help you with this @tansaku, if you want. I might need some context... would it be quicker for you to write tests that I can get passing? or would that take you longer than just implementing this?

**Comment by tansaku** [comment]
@mattwr18 I'd love to look at this together - maybe as part of next week?  we need sprint planning ...

**Comment by mattwr18** [comment]
hey @tansaku I know you are busy, but just wanting to know if we can make some headway on this?

**Comment by tansaku** [comment]
good question @mattwr18 - I'm going to try and document what I do now in the #mentors-devops channel on slack

**Pull request closed without merging**
