### PR TITLE
GitHub commit count

### LINKED ISSUE #764: Github commit count on profile page
imported from https://www.pivotaltracker.com/story/show/64891298

As a member of AV
So that I can find out what projects others are contributing to
I should see the number of commits they have made to projects listed on their profile page.

### PR DESCRIPTION
**Pull request by coloradobum**
Refactor current logic to use github api and auth token.

- Using authentication increases the rate limit from 60 to 5,000 requests an hour.
- auth_token needs to be created. See settings.local.yml.example. See https://help.github.com/articles/creating-an-access-token-for-command-line-use/ for creating auth token.

- https://www.pivotaltracker.com/story/show/78678240
- https://www.pivotaltracker.com/story/show/64891298
- https://www.pivotaltracker.com/story/show/80236842

Fixes #764

### CODE REVIEW

**Comment by tochman** [comment]
@coloradobum Yo, brother! Wanna pair up and make a push on this PR?

**Comment by coloradobum** [comment]
@tochman Yes, thanks for kicking me in the butt. I've attempted this multiple times and never seem to get anywhere.  I will share the details in Slack.

**Comment by tochman** [comment]
@coloradobum @yggie I submitted a PR concerning ordering projects by commit count. That PR involves a fix for the current state of `GithubCommitsJob`. Have a look at that and let me know what you guys think of it.

**Comment by coloradobum** [comment]
When I 

`git merge upstream/develop`

I'm getting the following error:
`fatal: Not possible to fast-forward, aborting.`

Any suggestions on how to proceed? Does this SO link apply to this situation?

http://stackoverflow.com/questions/13106179/fatal-not-possible-to-fast-forward-aborting

**Comment by tochman** [comment]
@coloradobum I created a PR on your branch that should fix the problem.

**Comment by coloradobum** [comment]
@tochman I merged your PR a few weeks ago- thank you.  Anything else I need to do on my end?

**Comment by diraulo** [comment]
@tochman @coloradobum what's the status on this PR, is this still relevant? If Yes what's currently blocking this?

**Comment by tansaku** [comment]
@tochman @coloradobum any follow up or should we close this?

**Comment by tansaku** [comment]
@coloradobum - I'm 100% on AgileVentures now so happy to pair with you on this if that helps ...

**Comment by coloradobum** [comment]
Hi @tansaku....it's been a long time, hope you're doing well.

I paired on this feature over a year ago. At the time, all was working and tests were passing.

The blocker was resolving merge conflicts into master.

Is this feature still of interest? It might be easier to close this and start over with a new PR?

**Comment by tansaku** [comment]
hi @coloradobum  - good to hear from you - hope you are well.  I think the feature is still of interest.  Merging conflicts to master may indeed be tricky due to project divergence ... you might be right that it'll be easier to start over.  Someone who knows the codebase a bit better than I should take a look over the conflict - I'll be happy to give my opinion too ...

**Comment by tansaku** [comment]
@tochman was saying that there is a fix for this in, but it's hacky, so we'd still like your code if possible @coloradobum 

This is the hacky scraping thing currently used: https://github.com/AgileVentures/WebsiteOne/blob/8f36a52cbe39c53e848bba1ad225b36feb891359/app/jobs/github_commits_job.rb

**Comment by tansaku** [comment]
@coloradobum only merge conflict is with Gemfile.lock which seems a relatively simple merge -  however these tests now fail:

rspec ./spec/controllers/application_controller_spec.rb:43 # ApplicationController global user messages should set @@message_status to false at application load
rspec ./spec/jobs/github_commits_job_spec.rb:22 # GithubCommitsJob.job stores commit counts only for projects that have a github_url
rspec ./spec/jobs/github_commits_job_spec.rb:27 # GithubCommitsJob.job stores total commit count only for projects that have a github_url
rspec ./spec/jobs/github_commits_job_spec.rb:32 # GithubCommitsJob.job stores commit counts only for users that have a github_profile_url
rspec ./spec/jobs/github_commits_job_spec.rb:36 # GithubCommitsJob.job stores correct commit counts by user and project
rspec ./spec/jobs/github_commits_job_spec.rb:41 # GithubCommitsJob.job stores correct total commit count for projects

and some cucumber failures ...

Also for a note, here is what the page currently looks like:

example github commit counts

**Comment by tansaku** [comment]
@coloradobum pushed up my Gemfile.lock fix and you can see it here: https://github.com/AgileVentures/WebsiteOne/pull/767

**Comment by tansaku** [comment]
closing this as we're working on it in #795

**Pull request closed without merging**
