### PR TITLE
Reset projects filter on events page after hit back

### LINKED ISSUE #1022: project dropdown on event page does not reset after you filter and then hit back button

### PR DESCRIPTION
**Pull request by cesswairimu**
Fixes #1022

### CODE REVIEW

**Comment by tansaku** [comment]
this is great @cesswairimu - would you be interested in adding tests for this?

**Comment by cesswairimu** [comment]
Sure @tansaku  am on it

**Comment by tansaku** [comment]
how's this one going @cesswairimu ?

**Comment by cesswairimu** [comment]
@tansaku  still trying to find a step-def for hit back without leaving the page. No luck yet

**Comment by cesswairimu** [comment]
Yeah I did try that doesn't work for this case. Let me push the code I have currently so you can take a look

**Comment by tansaku** [comment]
CI failure:

```
  Scenario: Project drop-down resets on hit back   # features/events/events_by_project.feature:53
    Given I am on the home page                    # features/step_definitions/projects_steps.rb:86
    When I dropdown the "Events" menu              # features/step_definitions/basic_steps.rb:139
    And I click "Upcoming events"                  # features/step_definitions/basic_steps.rb:95
    Then I should be on the Events index page      # features/step_definitions/event_steps.rb:450
    And I select "cs169" from the project dropdown # features/step_definitions/event_steps.rb:157
    And I click "Filter by Project" button         # features/step_definitions/basic_steps.rb:127
    Then I should see "Standup1"                   # features/step_definitions/basic_steps.rb:211
    Then I wait for 40 seconds                     # features/step_definitions/event_steps.rb:446
    And I hit back                                 # features/step_definitions/event_steps.rb:440
    Then "All" is selected in the project dropdown # features/step_definitions/event_steps.rb:190

      expected: ""
           got: "3"

      (compared using ==)
       (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/event_steps.rb:192:in `/^"([^"]*)" is selected in the project dropdown$/'
      features/events/events_by_project.feature:63:in `Then "All" is selected in the project dropdown'
```

is this the same error you're getting locally @cesswairimu ?

**Comment by cesswairimu** [comment]
@tansaku  Nope, :thinking: let me investigate more on this.

**Comment by tansaku** [comment]
great work here @cesswairimu ! :-)

**Pull request merged**
