### PR TITLE
WIP 1603 archive old projects 

### LINKED ISSUE #1603: archive old projects
```
As a new member
So that I can join a project
I would like an easily navigable uncluttered list
```

there are a load of totally inactive projects - we should hide on the left side bar them (and make the side list alphabetical) to make things easier to navigate (alphabetical)

### PR DESCRIPTION
**Pull request by Romusc**
fixes #1603 

I have changed the query in the current_projects method in the application helpers so that only active projects are displayed in the sidebar.

#### Motivation and Context
This links to issue 1603.
The idea is for the user to only see active projects in the sidebar, in alphabetical order.

#### How Has This Been Tested?
Cucumber tests have been amended so that inactive projects and inactive projects documents don't appear on the sidebar

No new test to check alphabetical order though.

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My code follows the code style of this project.

> I'm not sure about that, which is also why I tagged the PR as WIP.

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.

> Amended two tests.

- [x] All new and existing tests passed.

#### Comments

- I initially also amended the content and order of the projects in the projects index then realised it did not make sense and was not the point of this issue.

- I wonder if it would be good practice to add a test that checks that the projects are displayed in alphabetical order?

### CODE REVIEW

**Comment by Romusc** [comment]
Everything passed locally. I will try to find out what happened.

**Comment by tansaku** [comment]
hi @Romusc - how are we doing here? we need to sync to develop - do you want me to do it, or will you?

I know we talked about you doing some more on this, but if you can't get to it then we might want to try and work out what we can merge sooner rather than later ...

**Comment by Romusc** [comment]
Hi @tansaku , I think there might have been a misunderstanding my end. After we talked I added the tests and updated the branch (I think?) but kept the PR open so I thought I was waiting for your action. I just updated the branch and everything is passing. Hopefully this can be merged if you're happy with the changes.

**Comment by tansaku** [comment]
@Romusc at the moment the branch shows it is out of date (but then I just merged another PR into develop) - I can use my admin rights to update it, but then your local branch will be out of date again.

Apologies for the confusion - maybe I should just manage the updates my side ...

Will you be available for the Friday meeting to review?

**Comment by Romusc** [comment]
@tansaku No I won't be available today unfortunately. Isn't the issue the lapse of time between the moment I click "Update branch" and the moment you'd review it before merging? Then it might be easier if done your end? The two or three last times I clicked "Update branch" all the checks were passing.

**Comment by tansaku** [comment]
@Romusc I guess the question is also if there is more work to do on this PR to make it complete - do you think there is?

**Comment by tansaku** [comment]
I'm going to merge it and see :-)

**Pull request merged**
