### PR TITLE
[WIP] replace nearest_time_zone with timezone gem

### PR DESCRIPTION
**Pull request by dkuku**
#### Description

#1287 replaced nearest_time_zone with [timezone gem](https://github.com/panthomakos/timezone) which is activly maintained

#### Motivation and Context

nearest_time_zone had huge memory usage
#### How Has This Been Tested?

Checked all current rspec tests with live version of gem, when all was passing I used stubs to isolate tests from real api 
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by dkuku** [comment]
If we want to use it we definetly need a fallback google api key to use this because today my tests are not passing anymore:
`
Failures:

  1) User geocoding should change location if ip changes
     Failure/Error: self.timezone_offset = Timezone.lookup(self.latitude, self.longitude).utc_offset
     
     Timezone::Error::GeoNames:
       784: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
       <html><head>
       <title>503 Service Unavailable</title>
       </head><body>
       <h1>Service Unavailable</h1>
       <p>The server is temporarily unable to service your
       request due to maintenance downtime or capacity
       problems. Please try again later.</p>
       </body></html>
       '
     # ./app/models/user.rb:221:in `generate_timezone_offset'
     # ./spec/models/user_spec.rb:206:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # JSON::ParserError:
     #   784: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
     #   <html><head>
     #   <title>503 Service Unavailable</title>
     #   </head><body>
     #   <h1>Service Unavailable</h1>
     #   <p>The server is temporarily unable to service your
     #   request due to maintenance downtime or capacity
     #   problems. Please try again later.</p>
     #   </body></html>
     #   '
     #   ./app/models/user.rb:221:in `generate_timezone_offset'

Finished in 5.9 seconds (files took 5.48 seconds to load)
`

**Comment by dkuku** [comment]
Thanks @tansaku for the review.
This failing test was due to server overload, I will add locally my google api key configuration to this
What I need you to do is to create a free account on [geonames](http://www.geonames.org/login) and then enable [the free web service](http://www.geonames.org/enablefreewebservice) and add the username as an env variable.
For the vcr stuff - I don't have any clue how to even start with that, this gem has a nice stub helper for tests but we definetly need some using vcr as well.

**Comment by dkuku** [comment]
I had a stupid idea to create a microservice for this gem we were using - wrapping it with sinatra. This way we can skip google because its paid and keep this gem separate from WebsiteOne. 
[link](https://findtz.herokuapp.com/timezone/22/11)
[github](https://github.com/dkuku/timezone)

**Comment by tansaku** [comment]
thanks @dkuku so this is ready to merge in? or we need to have a session looking at the VCR together?

**Comment by dkuku** [comment]
I might need some suggestions where to place the method calls and maybe on vcr. The problem now is - when I want to find which tests are problematic I have to run th test suite offline, or probably I can filter out somehow the geonames address

**Comment by dkuku** [comment]
I moved the username to an env var and now it fails, You need to create and set the 
GEONAMES_USERNAME in env like I [instructed here](https://github.com/AgileVentures/WebsiteOne/pull/2758#issuecomment-432636384)
```rake aborted!
Timezone::Error::InvalidConfig: missing username
/home/runner/WebsiteOne/vendor/bundle/ruby/2.5.0/gems/timezone-1.3.0/lib/timezone/lookup/geonames.rb:20:in `initialize'
```

**Comment by tansaku** [comment]
thanks @dkuku - I've created a geonames account (username info@agileventures.org) and enabled it for free webservices as you suggested.  I've set the GEONAMES_USERNAME env var on semaphore for this project, so I'll restart the build and hopefully we'll be good :-)

**Comment by tansaku** [comment]
hi @dkuku seems to be still failing ...

**Comment by mattwr18** [comment]
Currently failing with these failures:
```
Failures:

  1) UserPresenter#timezone when no latitude and longitude present should display guessed timezone
     Failure/Error: expect(subject.timezone).to eq('UTC')
     
       expected: "UTC"
            got: "Europe/London"
     
       (compared using ==)
     # ./spec/presenters/users/user_presenter_spec.rb:57:in `block (4 levels) in <top (required)>'

  2) User.filter has filters filters users for timezone area filters user1 when choose In My Timezone
     Failure/Error: expect(results).to include(@user2)
     
       expected #<ActiveRecord::Relation [#<User id: 293, email: "christelkunde@pacochaherzog.name", created_at: "201...at: nil, event_participation_count: 0, can_see_dashboard: false, skill_list: nil, title_list: nil>]> to include #<User id: 291, email: "audrie@hartmannlebsack.info", created_at: "2018-10-29 11:02:29", updated_at: ...ount: 0, can_see_dashboard: false, skill_list: ["fugiat", "sit", "qui", "dolorem"], title_list: nil>
       Diff:
       @@ -1,2 +1,2 @@
       -[#<User id: 291, email: "audrie@hartmannlebsack.info", created_at: "2018-10-29 11:02:29", updated_at: "2018-10-29 11:02:29", first_name: "Nickolas", last_name: "Bednar", display_email: nil, youtube_id: nil, slug: "nickolas-bednar", display_profile: true, latitude: 44.33, longitude: 1.06, country_name: nil, city: nil, region: nil, youtube_user_name: nil, github_profile_url: nil, display_hire_me: nil, bio: "Sed laborum dolores ipsam.", receive_mailings: false, country_code: nil, timezone_offset: 3600, status_count: 2, deleted_at: nil, event_participation_count: 0, can_see_dashboard: false, skill_list: ["fugiat", "sit", "qui", "dolorem"], title_list: nil>]
       +[#<User id: 293, email: "christelkunde@pacochaherzog.name", created_at: "2018-10-29 11:02:29", updated_at: "2018-10-29 11:02:29", first_name: "Stacey", last_name: "Ankunding", display_email: nil, youtube_id: nil, slug: "stacey-ankunding", display_profile: true, latitude: nil, longitude: nil, country_name: nil, city: nil, region: nil, youtube_user_name: nil, github_profile_url: nil, display_hire_me: nil, bio: "Quasi aut omnis voluptas.", receive_mailings: false, country_code: nil, timezone_offset: 7200, status_count: 0, deleted_at: nil, event_participation_count: 0, can_see_dashboard: false, skill_list: nil, title_list: nil>]
       
     # ./spec/models/user_spec.rb:276:in `block (5 levels) in <top (required)>'

Finished in 41.82 seconds (files took 7.22 seconds to load)
659 examples, 2 failures

Failed examples:

rspec ./spec/presenters/users/user_presenter_spec.rb:53 # UserPresenter#timezone when no latitude and longitude present should display guessed timezone
rspec ./spec/models/user_spec.rb:271
```

**Pull request closed without merging**
