### PR TITLE
[WIP] - 2339 remove mercury

### PR DESCRIPTION
**Pull request by nisevi**
Fixes https://github.com/AgileVentures/WebsiteOne/issues/2339

### CODE REVIEW

**Comment by nisevi** [comment]
@tansaku we need to decide what to do with the documents `body` since by using mercury we were saving the html to the database and now when trying to edit we have the following:

image

**Comment by tansaku** [comment]
@nisevi we talked about this in a scrum I think - is the solution to switch all docs to pull from github?

**Comment by nisevi** [comment]
@tansaku I think the last time we talked about it the idea was to remove mercury, and add another editor (don't remember the name now) for handling documents. Since documents can have embedded videos/images.

**Comment by tansaku** [comment]
@nisevi it's the medium editor:

https://github.com/yabwe/medium-editor

and then a plugin for embeds:

https://github.com/anorudes/medium-editor-embed-plugin

but I worry slightly that would be a time sync (and something that we have to maintain) when we might be better served by just completely outsourcing almost all content editing to github ...

**Comment by nisevi** [comment]
I haven't had the time I thought to spend on this ticket. That is why I have added the `help-wanted` label in order to anyone to contribute if they want to. I can walk them through how to address the development of the things that need to be done in order to complete this story :rocket:

**Comment by mattwr18** [comment]
hey @nisevi I can work on this if you can walk me through what still needs to be done... I remember you mentioned it's not much...

**Comment by nisevi** [comment]
@mattwr18 I will resurrect ☠️ this PR. I need to install all over again since I'm from a new machine. I will keep you posted 👍

**Comment by tansaku** [comment]
@nisevi would be great to have you back on this.  We do need to be careful that there aren't places in the system that still rely on mercury, but hopefully the tests will tell us that maybe?

Might be an idea to start fresh from develop and just delete the mercury stuff and see what fails?

**Comment by nisevi** [comment]
@tansaku yup, good idea. I will close this PR and we will have only as reference 👍

**Pull request closed without merging**
