### PR TITLE
Added Registrations helper spec

### PR DESCRIPTION
**Pull request by MrO1**
I added tests for the registrations_helper.

registrations_helper_spec.rb is the file I created, and made tests for.

### CODE REVIEW

**Comment by yggie** [comment]
@MrO1 do you plan to continue work on this PR? This has been sitting here for a while so I would like to get this resolved.

**Comment by MrO1** [comment]
Sorry, will look at it this weekend.

**Comment by MrO1** [comment]
Alright, so what exactly do I need to do for this PR?

**Comment by yggie** [comment]
@MrO1 The issue is that the build is failing, I can’t merge this until it passes. Have you made sure all the tests are passing? Also there are a few changes in the `spec_helper` file not related to the story, could that be removed?

**Comment by tochman** [comment]
I'm doing some spring cleaning and will close this one for now. Feel free to reopen if/when you feel like making contributions again.

**Pull request closed without merging**
