### PR TITLE
Events page Projects dropdown

### LINKED ISSUE #1812: only show active projects on the events page dropdown
at the moment we are seeing every project that ever existed in the volunteers page dropdown:

screenshot 2017-09-06 12 18 14

we could make make this easier to navigate if we made it only active projects like we've done on the main project page ...

### LINKED ISSUE #2665: Make projects dropdown on the events page only have projects with future events
The projects dropdown in the [events index page](https://www.agileventures.org/events)  should only have projects with future scheduled events 
## Expected Behavior

The projects dropdown should only have a list of projects with events scheduled for the future

## Current Behavior

Currently, the projects dropdown contains a list of all the projects, even those for which the events have never been created
## Possible Solution
Filter the projects on the list to contain only projects which have future scheduled events.

## Context
I was trying to filter events by projects on the events page(https://www.agileventures.org/events) and got a huge list of projects in the dropdown, while not so many projects had future events
## Your Environment

* Version used:
* Chrome 69
* OS X version 10.11.6

### PR DESCRIPTION
**Pull request by aonomike**
fixes #2665 

- Filter by active projects

#### Description
Filter to display only active projects on projects dropdown

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

fixes #1812

### CODE REVIEW

**Comment by mattwr18** [comment]
Failing the build with this error 
```
Failures:

  1) Events allows prepopulation of form with project
     Failure/Error: expect(page).to have_select('Project', selected: 'edX')
       expected #has_select?("Project", {:selected=>"edX", :session_options=>#<Capybara::ReadOnlySessionConfig(#<Capybara::SessionConfig:0x00...ick=false, @enable_aria_label=false, @save_path=#<Pathname:/home/runner/WebsiteOne/tmp/capybara>>)>}) to return true, got false
     # ./spec/requests/events_spec.rb:22:in `block (2 levels) in <top (required)>'

Finished in 47.96 seconds (files took 9.79 seconds to load)
658 examples, 1 failure

Failed examples:

rspec ./spec/requests/events_spec.rb:19 
```
Is this failing locally as well @aonomike?

**Comment by aonomike** [comment]
Currently looks good on my local @mattwr18

**Comment by aonomike** [comment]
@tansaku @mattwr18 added acceptance tests to this PR

**Comment by tansaku** [comment]
wonderful! thanks @aonomike :-)

**Comment by tansaku** [comment]
wonderful! thanks @aonomike :-)

**Pull request merged**
