### PR TITLE
Appropriate defaults for creating events

### LINKED ISSUE #891: setting appropriate defaults (specifically default end for repeats) for event creation
We need appropriate defaults for event creation to avoid repeats hanging around indefinitely

repeat defaults to never ending

Currently as shown above, selecting a repeat leads to a never ending event ...

### PR DESCRIPTION
**Pull request by mtc2013**
fixes #891

### CODE REVIEW

**Comment by mtc2013** [comment]
@tansaku @diraulo This is ready for review.

**Comment by diraulo** [comment]
screenshot 2016-03-15 14 01 53

@tansaku @mtc2013 Why show `End Time in UTC` field if the event is set to never repeat? Also wouldn't it be preferable to have it say `End date`?

**Comment by diraulo** [comment]
@tansaku have you seen my previous comment? I see you've solved the issue with confusing field in #907

**Comment by tansaku** [comment]
@diraulo yeah - it has been like that for a long time - that was another long standing UI issue that as you noticed we addressed in #907, so perhaps this can be merged?

**Comment by diraulo** [comment]
@tansaku what about displaying the field when the event is set to never repeat? Shouldn't it be hidden in that case?

**Comment by tansaku** [comment]
@diraulo - yes, but that's what the other PR fixes.

I believe problems you are highlighting here were already problems before we started working on fixing the defaults.

I think this PR in combination with the other fix all the concerns - unless I'm missing something ...

**Comment by diraulo** [comment]
Okay then I'll review the other PRs and merge this one too

**Pull request merged**
