### PR TITLE
[WIP] - Background and the steps for private events feature.

### PR DESCRIPTION
**Pull request by nisevi**

### CODE REVIEW

**Comment by tansaku** [comment]
@nisevi @bcb37 - @marianmosley and I reviewed and we think the kind of scenario we'd want is maybe an outline like this:

```
  Scenario Outline: show mob hangout links to users with correct plans
    Given the I am logged in as a user with "<plan>"
    Given the Hangout for event "Mob" has been started with details:
      | EventInstance link | http://hangout.test |
      | Started at         | 10:25:00 UTC        |
    And the time now is "10:26:00 UTC"
    When I am on the show page for event "Mob"
    Then I <assertion> see link "Join now" with "http://hangout.test"
    Examples:
      | plan       | assertion  |
      | PremiumF2F | should     |
      | PremiumMob | should     |
      | Premium    | should not |
      | Associate  | should not |
      | Free       | should not |
```

although we can start with individual ones if that is easier:

```
  Scenario: Premium member cannot access live mob event
    Given the Hangout for event "Mob" has been started with details:
      | EventInstance link | http://hangout.test |
      | Started at         | 10:25:00 UTC        |
    And the time now is "10:26:00 UTC"
    When I am on the show page for event "Mob"
    Then I should not see link "Join now" with "http://hangout.test"
    And I should not see hangout button
```

the main problem in the feature you added was that there is no Free plan type - removing that allowed more of the feature to run, but we should all talk to get clarity on the precise feature definition here

**Comment by nisevi** [comment]
Closing this one @tansaku since @maryam21 is working on it in another PR :+1: .

**Comment by tansaku** [comment]
@nisevi not sure that @maryam21 is working on it - I was hoping to have discussion with @bcb37 here about our proposed cucumber scenarios - for anyone who works on this we really need to get those clear to avoid spinning out wheels

**Comment by maryam21** [comment]
Hi @nisevi , no I'am not working on this one.

**Pull request closed without merging**
