### PR TITLE
WIP 2286 allow payment premium crypto

### LINKED ISSUE #2286: allow payment of premium in crypto
@moddedgamer asked about this.  Looks like Stripe doesn't support bitcoin payments, but I wonder if we should integrate with something like https://www.coinpayments.net/

### PR DESCRIPTION
**Pull request by Hess3000**
fixes #2286 

#### Motivation and Context
Allow Premium subscriptions to pay subscrption with crypto

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [-] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Hess3000** [comment]
I'm having trouble logging a user in in cucumber. 
I need to log them in so they can view  subscriptions/new.

The step definition is set by this statement: **When I sign in with valid credentials**

Actual step definition I think it relates to: 

When /^I sign in with valid credentials$/ do
  create_visitor
  sign_in
end

**Comment by mattwr18** [comment]
Hey @Hess3000 have you seen these scenarios https://github.com/AgileVentures/WebsiteOne/blob/develop/features/premium/subscribe_self_to_premium.feature#L14? Maybe you could copy some of the relevant steps?

**Comment by Hess3000** [comment]
> Hey @Hess3000 have you seen these scenarios https://github.com/AgileVentures/WebsiteOne/blob/develop/features/premium/subscribe_self_to_premium.feature#L14? Maybe you could copy some of the relevant steps?

Great thanks Matt,
To get this working we ensured there were plans in the database.

**Comment by Hess3000** [comment]
Formatting issue.

When using sublime editor, the formatting changes when push, as you can see in the image below the formatting is OK but in the 'files changed' it shows as out of line

screen shot 2018-10-18 at 14 32 02

**Comment by mattwr18** [comment]
This is currently failing on these issues:
```
And I should not see a sign up link     # features/step_definitions/user_steps.rb:218
      expected not to find visible xpath "//a[@href = '/users/sign_up']", found 1 match: "Sign Up Now" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/user_steps.rb:219:in `/^I should not see a sign up link$/'
      features/users/sign_in.feature:20:in `And I should not see a sign up link'
    HTML screenshot: /home/runner/WebsiteOne/tmp/capybara/screenshot_2014-02-04-07-01-17.280.html

Failing Scenarios:
cucumber -p second_try features/hangouts/hangout.feature:131 # Scenario: Infinite scroll on hangouts scroll down until no more hangouts
cucumber -p second_try features/premium/crypto_payment.feature:17 # Scenario: User able to view addresses to send crypto to
cucumber -p second_try features/users/sign_in.feature:13 # Scenario: User signs in successfully
```
The hangout.feature is a recurring intermittent failure that I wouldn't worry too much about, the sign_in feature is a persistent intermittent failure that we have skipped in the latest merges to develop, and the other failure is related to the crypto payment stuff @Hess3000 
```
And I click "Subscribe with Crypto"                   # features/step_definitions/basic_steps.rb:95
      can't find record with friendly id: "N6RKQ9QN" (ActiveRecord::RecordNotFound)
      ./app/controllers/static_pages_controller.rb:14:in `show'
      ./features/step_definitions/basic_steps.rb:96:in `/^(?:when I|I) click "([^"]*)"$/'
      features/premium/crypto_payment.feature:21:in `And I click "Subscribe with Crypto"'
```
Is it failing in the same way locally?

**Comment by Hess3000** [comment]
> This is currently failing on these issues:
> 
> ```
> And I should not see a sign up link     # features/step_definitions/user_steps.rb:218
>       expected not to find visible xpath "//a[@href = '/users/sign_up']", found 1 match: "Sign Up Now" (RSpec::Expectations::ExpectationNotMetError)
>       ./features/step_definitions/user_steps.rb:219:in `/^I should not see a sign up link$/'
>       features/users/sign_in.feature:20:in `And I should not see a sign up link'
>     HTML screenshot: /home/runner/WebsiteOne/tmp/capybara/screenshot_2014-02-04-07-01-17.280.html
> 
> Failing Scenarios:
> cucumber -p second_try features/hangouts/hangout.feature:131 # Scenario: Infinite scroll on hangouts scroll down until no more hangouts
> cucumber -p second_try features/premium/crypto_payment.feature:17 # Scenario: User able to view addresses to send crypto to
> cucumber -p second_try features/users/sign_in.feature:13 # Scenario: User signs in successfully
> ```
> The hangout.feature is a recurring intermittent failure that I wouldn't worry too much about, the sign_in feature is a persistent intermittent failure that we have skipped in the latest merges to develop, and the other failure is related to the crypto payment stuff @Hess3000
> 
> ```
> And I click "Subscribe with Crypto"                   # features/step_definitions/basic_steps.rb:95
>       can't find record with friendly id: "N6RKQ9QN" (ActiveRecord::RecordNotFound)
>       ./app/controllers/static_pages_controller.rb:14:in `show'
>       ./features/step_definitions/basic_steps.rb:96:in `/^(?:when I|I) click "([^"]*)"$/'
>       features/premium/crypto_payment.feature:21:in `And I click "Subscribe with Crypto"'
> ```
> Is it failing in the same way locally?

Hey @mattwr18 yes this is failing locally, it's still a work in process.

**Comment by mattwr18** [comment]
Ok @Hess3000, no worries.... Just didn't know if it was just on the build or not, let us know if you want any support working through the failure :smile:

**Comment by tansaku** [comment]
hi @Hess3000 we've got the build passing here, but are we stuck in terms of crypto not supporting repeat payments?

**Comment by Hess3000** [comment]
Hey @tansaku I've got in touch with Puma pay to see if they could help, they have just released an API that might support what we need. Else I'm also thinking about how we could build our own smart contract

**Pull request closed without merging**
