### PR TITLE
[WIP] Upgrade to Rails 5 (depends on Issue #1756)

### LINKED ISSUE #1737: Update to Rails 5
Update to latest Rails5, currently 5.1.2: http://weblog.rubyonrails.org/2017/6/26/Rails-5-1-2-has-been-released/.

### PR DESCRIPTION
**Pull request by tansaku**
So we can't progress on this until we address #1756

### CODE REVIEW

**Comment by tansaku** [comment]
@mattlindsey are you working on this branch now?

You mentioned 

> I’m having a hard time with this error from Mercury in Rails 5 upgrade whenever the edit button is hit:

```
Missing template mercury/edit with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
        * "/Users/mattlindsey/Documents/github/WebsiteOne/app/views"
        * "/Users/mattlindsey/.rvm/gems/ruby-2.3.1/bundler/gems/mercury-0b404aa8f23e/app/views"
        * "/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/kaminari-core-1.0.1/app/views"
        * "/Users/mattlindsey/.rvm/gems/ruby-2.3.1/gems/devise-4.3.0/app/views"
       (ActionView::MissingTemplate)
```

> The route shows up when I do `rake routes`:

```
Routes for Mercury::Engine:
mercury_editor GET      /editor(/*requested_uri)(.:format)        mercury#edit
               GET      /mercury/:type/:resource(.:format)        mercury#resource
               GET|POST /mercury/snippets/:name/options(.:format) mercury#snippet_options
               GET|POST /mercury/snippets/:name/preview(.:format) mercury#snippet_preview
```

is that for this branch? can you specify the commit that gives you this issue?

**Comment by mattlindsey** [comment]
@tansaku I updated the branch 1737_rails_5_remove_polyamorous_server_start to use my fork of mercury, which has a couple of small fixes for rails 5.  You should see that error now if you run it.

**Comment by tansaku** [comment]
thanks @mattlindsey  - if this is the place that work is taking place now perhaps we could close the other PR and update the description here?

**Comment by tansaku** [comment]
@mattlindsey I'm replicating locally:
```
→ be rspec ./spec/controllers/application_controller_spec.rb:73
[Coveralls] Using SimpleCov's 'rails' settings.
Run options: include {:locations=>{"./spec/controllers/application_controller_spec.rb"=>[73]}}

Randomized with seed 34241
F

Failures:

  1) ApplicationController do not store a location if a blacklisted url doesn't accept sign in
     Failure/Error: render :text => ""
     
     ActionView::MissingTemplate:
       Missing template anonymous/signout, application/signout with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
         * "/Users/tansaku/Documents/GitHub/AgileVentures/WebsiteOne/app/views"
         * "/Users/tansaku/.rvm/gems/ruby-2.3.1/bundler/gems/mercury-0b404aa8f23e/app/views"
         * "/Users/tansaku/.rvm/gems/ruby-2.3.1/gems/kaminari-core-1.0.1/app/views"
         * "/Users/tansaku/.rvm/gems/ruby-2.3.1/gems/devise-4.3.0/app/views"
```

**Comment by tansaku** [comment]
this looks painful and non-trivial @mattlindsey - I wonder if it might be easier to switch editor?

http://berk.es/2015/02/03/selecting-a-good-wysiwyg-for-rails-its-all-about-usecases/

personally I've be happy to move to a markdown editor like github uses - I'm not sure that there's a clear choice for rails applications these days.

I don't know that we have the resources to keep maintaining mercury ...

**Comment by tansaku** [comment]
I can't seem to find any of the templates that mercury is looking for - I've been through the mercury source code and our own.

I imagine that the mercury rails engine is not compatible with Rails 5.  Perhaps we might try switching to a simple markdown editor like https://github.com/rderoldan1/md_simple_editor  - and maybe we should make that change in Rails 4 and then upgrade to Rails 5 separately ...?

**Comment by tansaku** [comment]
@mattlindsey so we should close this as well till we've got the mercury migration sorted - or keep this open and link the description to the relevant ticket?  I think probably close right?  but you know you can update the description right?

**Comment by nisevi** [comment]
Closing this PR due to inactivity and regarding last comment :+1: . In the future if we upgrade to rails 5 we will open a new PR.

**Pull request closed without merging**
