### PR TITLE
rough changes to PR template

### LINKED ISSUE #2793: Update the issue and pull request templates
## Expected Behavior

The issue and pull request templates should be shorter, easier to use and designed by us for how we actually work.

## Current Behavior

A lot of people ignore the templates at the moment - both on the submission and review sides

## Possible Solution

make templates shorter and add specifics to address some pain points, e.g. add fixes #<issue_number> to PRs 

## Steps to Reproduce (for bugs)

1. open a PR or issue and see the template

## Context

trying to make the project fix bugs and deliver features more efficiently - help people submit issues and PRs

### PR DESCRIPTION
**Pull request by tansaku**
#### Issue addressed

fixes #2793 

#### Screenshots (if appropriate):

PR template now looks like this

#### Testing

This doesn't require automated testing by us since part of github, but all devs should look over the new templates to agree on the new format.

Thanks so much to @diraulo for adding the originals, and apologies it has taken us (me!) so long to actually work on adjusting them to our particular project workflow :-(

### CODE REVIEW

**Comment by tansaku** [comment]
how does this look to you @aonomike ?

**Comment by tansaku** [comment]
@mattwr18 would love your input too :-)

**Comment by mattwr18** [comment]
hey sorry for the delayed reply... It looks good except that I would encourage adding the Fixes # as part of the actual template cause it might not be noticed otherwise.

See https://github.com/stevemao/github-issue-templates/blob/master/simple/PULL_REQUEST_TEMPLATE.md

**Comment by tansaku** [comment]
great idea @mattwr18 - have changed that - should we merge this and iterate?  get input from others like @dkuku @aonomike @Kachulio1 and others?

**Pull request merged**
