### PR TITLE
Update Rubymine image

### LINKED ISSUE #787: The Ruby Mine image is out of date
In the "Supporters" panel, it is an old RM7 logo, but Jetbrains have rebranded and are on v8 now.
New logo can be downloaded here: https://www.jetbrains.com/company/press/

### PR DESCRIPTION
**Pull request by freeranger**
Testing a new process to signal intent to work on an issue
But also to update the logo from RM 7 to RM 8 :)

closes #787

### CODE REVIEW

**Comment by tochman** [comment]
@freeranger We need an image with `width: 205px`  +- 5 px as the other ones in the Sponsor panel.

**Comment by freeranger** [comment]
@tochman The existing image is not that size, but also the T&C for jetbrains don't allow it.
This is from the readme.txt included with the image assets:
>
>DO’s
>----
>Do use the logos to link to JetBrains website
>Do use the logos to advertise that your product has built-in integration with a JetBrains product
>Do use the graphics in printed or online materials
>
>Don’ts
>------
>
>Don’t change the colors of the logos
>Don’t change the dimensions
>Don’t sell our logos
>
>If in doubt, please contact marketing@jetbrains.com

It's that size or nothing....

**Comment by sampritipanda** [comment]
I think you can scale the image to fit the required dimensions as closely as possible without modifying the width/height ratio.

**Comment by freeranger** [comment]
@sampritipanda that would constitute changing the dimensions of the logo, which is prohibited

**Comment by tochman** [comment]
@freeranger do you really not see a solution for this?

**Comment by tochman** [comment]
Please check the dimensions of this one. 

rm8_transparent_205

**Comment by freeranger** [comment]
I used the brand assets they make available here: https://www.jetbrains.com/company/press/ and followed their direction in not changing the size of the image.
I have emailed them to ask if it is okay to display it at a different size on screen - ie the physical dimensions remain the same but the displayed size is different

**Comment by tochman** [comment]
@freeranger In the example above I an NOT changing the dimensions of the RM logo. I am simply changing the canvas size of the image. Please, let's seek for simple solutions, okay?

**Comment by freeranger** [comment]
@tochman The english language is wonderfully ambiguous - dimension and size are very often used interchangably and my interpretation of jetbrains t&c is that they the logo cannot appear on screen at any other size than the dimensions supplied.
Emailing jetbrains for clarification on this seems to me to be the simplest solution rather than having a big debate on it and further speculating on what they mean and the semantics of the english language.
When they come back with a definitive answer on what we can or cannot do with their logo then we can display it in your preferred size if we are allowed, keep to the size === the dimensions because we are not allowed, or remove it completely if being a different size is a deal breaker...

**Comment by tochman** [comment]
Okay so you have the solution right in front of you. I attached a file that is both NOT modifying the RM Logo dimensions and has the right image size to be displayed on out site. Oven and out.

**Comment by freeranger** [comment]
Where has that image come from?
The RubyMine assets zip file which I used from here: https://resources.jetbrains.com/assets/products/rubymine/rubymine_logos.zip
contains the assets they want you to use if you are linking to them
It has three three images
- An "icon" image which is the one I used, which is 128x128
- An image of a box which is 600x600
- a log which is 900x400

the image you pasted is 205x143

Maybe I'm missing something here (entirely possible)?  Isn't it simpler just to wait until they come back to us and take it from there?

**Comment by tochman** [comment]
I made it.

**Comment by tansaku** [comment]
great work @tochman - so this is ready to merge now?

**Comment by freeranger** [comment]
@tansaku - I contacted jetbrains about this and they offered to create a bigger image.

I have sent them the image that @tochman created to see if that is acceptable to them.
They took a few days to respond to the original so watch this space...

**Comment by diraulo** [comment]
@freeranger any updates on this one?

**Comment by freeranger** [comment]
@diraulo I sent them a chasing email a couple of hours ago, nothing back yet...

**Comment by tansaku** [comment]
you know @freeranger I really can't imagine any universe where JetBrains would care about us making the image larger.  I feel like they don't want the dimension ratio changed, and even if they did feel strongly about the actual size I think it would be common sense to follow the Grace Hopper maxim:

http://www.brainyquote.com/quotes/quotes/g/gracehoppe170166.html

**Comment by freeranger** [comment]
Ok well it's your project so your decision really ;)
I was only following their T&C's as I understood them to mean.
I did ask them about it and after their initial response offered a bigger image, which was about a week ago - no response since, so either it is a more complex matter (unlikely) or they just don't care enough perhaps...
I will update the PR later tonight hopefully with the image Thomas supplied
But if they come round with the heavies later, I'm pointing them straight to you :^)

**Comment by freeranger** [comment]
...and you're off the hook now @tansaku because they just came back to me to say it's ok to use our own image with the actual logo the same size 😀

**Comment by tansaku** [comment]
@diraulo looks good to you?

**Comment by diraulo** [comment]
Just checked it locally and it's okay, below is a screenshot. 

screenshot 2016-02-24 11 20 40

Unless there are any other objections we can go ahead and merge this.

**Pull request merged**
