### PR TITLE
Change join event button styles

### PR DESCRIPTION
**Pull request by tbaraza**
Change what gets shown on the event page when an event is live
Solves [#810](https://github.com/AgileVentures/WebsiteOne/issues/810)

#### Description
Remove the border for the div surrounding the link to a live event
Change the color and text of the join button 
Update hangout and live event tests 

#### Screenshots:
Before
screen shot 2018-08-13 at 11 30 21 pm

After

screen shot 2018-08-13 at 11 10 22 pm

### CODE REVIEW

**Comment by diraulo** [comment]
@tbaraza The changes you made to this view are causing these failures in the tests. You should make sure the tests currently failing on [this build](https://semaphoreci.com/agileventures/websiteone/branches/pull-request-2543/builds/1) are all good locally and push up fixes for them.

**Comment by tansaku** [comment]
thanks for this @tbaraza  - great work.

one minor issue is that we have quite a few extra cache yml files from vcr in the PR.  Apologies from our side on this - it's a bit of a pain point that we haven't worked out any super fix, but maybe have a read of this on our acceptance tests and caching:

https://github.com/AgileVentures/WebsiteOne/blob/develop/CONTRIBUTING.md#acceptance-tests-and-caching

There's a rake task that allows  you to clear the cache locally before making commits.  In this case it might be a bit complicated to back out depending on how comfortable you are with git.  If you need help let us know and we can maybe cherry pick out what's essential in order to clean out the PR ...

**Comment by mattwr18** [comment]
hey @tansaku @tbaraza, we were pairing on this issue and it was getting to be a longer recorded session and I forgot to let her know about this. 
Also, it is a good idea, before creating a branch with a new contributor, to go to that part of the CONTRIBUTING.md and highlight it.

**Comment by tansaku** [comment]
no worries @mattwr18 - it's annoying we've got this sharp edge in the development flow - good little chat going on about how we can improve in #websiteone-devops ...

**Comment by tbaraza** [comment]
Thanks, tansaku @mattwr18 . My bad, I didn't go through the part of acceptance tests and caching. I'll go through it, try to clean up the PR and reach out and when I need assistance.

**Comment by tansaku** [comment]
great work @tbaraza - many thanks!

**Pull request merged**
