### PR TITLE
Patch - Change "Close To My Timezone Area" to "In My Timezone"

### PR DESCRIPTION
**Pull request by Sysqa**
As @tochman asked I change `Close To My Timezone Area` to `In my timezone`

### CODE REVIEW

**Comment by christophermlne** [comment]
should it be 'In or near my timezone'?

**Comment by tochman** [comment]
Well, is it 'in' or 'in and near'? What results is this search returning?  When I tried it it retured only members IN my timezone.

**Comment by tochman** [comment]
@Sysqa you need to merge with upstream. Your ruby version is not correct. We bumbed it up to 2.1.5

**Comment by christophermlne** [comment]
i believe it is near. if you live near the edge of your timezone you will get members from an adjacent timezone

**Comment by Sysqa** [comment]
After timezone offset modifications the In My Timezone should be the right...

**Pull request merged**
