### PR TITLE
1097 more verbose timezone names on event show page

### PR DESCRIPTION
**Pull request by SuperManEver**

### CODE REVIEW

**Comment by diraulo** [comment]
@SuperManEver It appears you might have created this new branch from your modified version of `develop` thus introducing the change to `Sign_up_for_premium_membership.yml`

I could be wrong in my assumption, but I really don't see why that file is part of this PR. 

You might want to consider deleting your `develop` branch (If you haven't already), then pull the one from `upstream` just to have a clean start and make sure you work from a new branch in future when implementing a feature.

**Comment by SuperManEver** [comment]
"It appears you might have created this new branch from your modified
version of develop thus introducing the change to
Sign_up_for_premium_membership.yml" - this what I had before, at my last
attempt I just forked main repo without introducing changes. The only thing
that I've changes is .env file that Sam gave me and run tests and while
tests was running this file was generated.

"You might want to consider deleting your develop branch (If you haven't
already), then pull the one from upstream just to have a clean start and
make sure you work from a new branch in future when implementing a feature."
- ok, I'm going to try this.

Thanks for helping me

**Comment by tansaku** [comment]
@SuperManEver this PR is somewhat confusing since the commits don't relate to the PR title: "1097 more verbose timezone names on event show page"

If you're making an experimental PR please label it correctly so that we don't get confused - thanks :-)

**Comment by tansaku** [comment]
@SuperManEver I'm going to close this for the moment - as I've confused myself a couple times thinking that our own PR is still open

**Pull request closed without merging**
