### PR TITLE
alternate events index/show page layout

### LINKED ISSUE #832: Events Index Page Revision
As a user
So that I can join a pair programming session or standup
I would like to see the upcoming events in as much clarity as possible

hoping to adjust to ensure all the helpers are working, and make best use of the screen real estate as possible

### PR DESCRIPTION
**Pull request by tansaku**
fixes #832

Revised version of events index page - CSS is not my strong point I'm going for a layout here that makes efficient use of screen real estate:

revised index page

### CODE REVIEW

**Comment by tansaku** [comment]
and this is what it looks like with the event live:

events gone live

**Comment by freeranger** [comment]
Looks much "cleaner" than the current page, and more in line with the "Past Events" page, both of which are good.  Personally I think the "Past Scrums" page is the cleanest and sort of gives a sense of "movement" but I'd rather they were all consistent than look like my personal preference...and you don't actually get any more events per page - it just looks like you do...but I digress...

Would it be possible to have a link to the related project (if there is one) in the same way that the "Past Events" page does?  I think that would be useful from a "discovery" point of view - you see a list of upcoming events and you can click on the project to find out what it's about...

Looks good though and code, as far as I can tell, looks good too.

**Comment by tansaku** [comment]
Thanks @freeranger - good point about being able to show the related project - I think we'll be able to support that when we fix #796 - please feel free to open a new ticket to remind us to do that - referencing #796 and this one if possible

**Comment by tansaku** [comment]
Note to @tansaku - check this on some smaller screen sizes

**Comment by freeranger** [comment]
Created https://github.com/AgileVentures/WebsiteOne/issues/842

**Comment by tansaku** [comment]
iPhone 6:

iPhone 6

iPad:

iPad

**Comment by freeranger** [comment]
*iPhone*
Seems to be a lot of wasted space here:
- big gap before the "burger" menu
- then an even bigger gap down to the "AgileVentures Events" title.

The title itself might look better in a smaller font so it fits on one line?
Can't really see an actual event but it looks like there is a lot of padding there too that could be reduced and maybe make the rounded corner boxes the same width as the container?
The focus of this page should be the list of events but all I can see is the title for one - the rest is all blurb and navigation!

*iPad*
Doesn't seem to be making best use of the space for the title - it looks to me like "Pure Awesomeness Pure Awesomeness Pure.." could fit on one line?
The rest of it looks pretty good though.

Appreciate some of this may not be that page per-se and coming from the overall site, so perhaps another issue is necessary to address some of those concerns....

**Comment by tansaku** [comment]
thanks @freeranger - as you note I think those gaps you mention are a general issue that should be addressed in another ticket

iPhone 6 event in list

I'm tempted to say that this is good enough for the time being, and that we merge and then resolve things in other tickets?

@diraulo if you're happy perhaps we can merge this?

**Comment by tansaku** [comment]
@freeranger note also that if you pull this branch you can investigate the site in this state using device mode in chrome:

https://developer.chrome.com/devtools/docs/device-mode

**Comment by freeranger** [comment]
@tansaku cool, thanks for the tip!

**Comment by freeranger** [comment]
https://github.com/AgileVentures/WebsiteOne/issues/849 to look at the whitespace generally on mobile

**Comment by diraulo** [comment]
@tansaku I'm happy with this one.

**Comment by tansaku** [comment]
@diraulo cool let's merge then - and we could start to get this out to staging for further testing ... I feel like we could also do a quick round of UX cleanup on the event show page  ...

**Comment by mtc2013** [comment]
@mercury_step @javascript
  Scenario: Editing Pitch content with Mercury Editor                                                    # features/projects.feature:182
    Given I am logged in                                                                                 # features/step_definitions/user_steps.rb:19
    And I am on the "Show" page for project "hello mars"                                                 # features/step_definitions/basic_steps.rb:256
    And I click the "Join Project" button                                                                # features/step_definitions/basic_steps.rb:77
    And I am using the Mercury Editor to edit project "hello mars"                                       # features/step_definitions/mercury_steps.rb:27
    When I fill in the editable field "Pitch" for "project" with "This is my exciting marketing content" # features/step_definitions/mercury_steps.rb:9
    And I click "Save" within Mercury Editor toolbar                                                     # features/step_definitions/mercury_steps.rb:1
    Then I should see a flash "The project has been successfully updated."                               # features/step_definitions/basic_steps.rb:193
      expected to find css ".alert" with text "The project has been successfully updated." but there were no matches (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/basic_steps.rb:195:in `/^I should( not)? see a flash "([^"]*)"$/'
      features/projects.feature:189:in `Then I should see a flash "The project has been successfully updated."'
    Then I should be on the "Show" page for project "hello mars"                                         # features/step_definitions/basic_steps.rb:252
    And I should see "This is my exciting marketing content"                                             # features/step_definitions/basic_steps.rb:185
    HTML screenshot: /Users/michael/Desktop/WebsiteOne/tmp/capybara/screenshot_2016-03-02-14-43-19.919.html
    Image screenshot: /Users/michael/Desktop/WebsiteOne/tmp/capybara/screenshot_2016-03-02-14-43-19.919.png

Failing Scenarios:
cucumber features/projects.feature:182 # Scenario: Editing Pitch content with Mercury Editor

**Comment by mtc2013** [comment]
When I run this with bundle exec per sam, this passes.

**Pull request merged**
