### PR TITLE
#1127 replace omniauth-gplus gem with omniauth-google-oauth2 and update the provider to google_oauth2

### LINKED ISSUE #1127: create request spec to check gplus redirect URL
the current gplus signup tests do not catch the bug from omniauth-oauth2 1.4.1 that creates a redirect URL that gplus can't handle - we've fixed that issue, but a request spec could provide additional cover against the possibility that someone changes the omnitauth-oauth2 gem again ...

### PR DESCRIPTION
**Pull request by theBoyMo**
I've replaced replaced the omniauth-gplus gem with omniauth-google-oauth2 and updated the strategy to access the Google Api.

#### Description

The reference to omniauth-gplus was removed from the Gemfile and omniauth-google-oauth2 added. Following running 'bundle install', the strategy was updated in 'config/initializers/omniauth.rb' to use 'google_omniauth2'. I renamed the 'name' of the strategy to 'gplus' as it was before so the references to the provider in the app and the callback url would not have to be changed assuming that this would be a simpler fix. 

#### Motivation and Context

The omniauth-gplus gem currently used by the project is not currently being updated. Due to a number of issues relating to this I've replaced it with the omniauth-google-oauth2 gem and updated the strategy to access the Google authentication API

#### How Has This Been Tested?

Current acceptance tests check that a user can login via Google, which still pass following the change.

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

fixes #1127

### CODE REVIEW

**Comment by nisevi** [comment]
Hi there @theBoyMo , I just updated the PR with develop, so maybe you wanna pull the changes first before doing a new commit :+1:

**Comment by theBoyMo** [comment]
Hi @nisevi, I did. The branch wasn't out of date when a I made the commit

**Comment by theBoyMo** [comment]
Correct me If I'm wrong, but hasn't coverage gone down because the develop branch has been updated since I submitted my PR? When I submitted the PR there was no warning of the branch being out of date. That appeared a few days later.

**Comment by nisevi** [comment]
Hey @theBoyMo you are interpreting it right, code coverage has been decreased. However we have seen this behavior in other couple PR's so I think the error comes from the way coveralls is working. We could contact the people on `coveralls` and ask them why the change on our coverage when things remain the same? before asking that we also could track the coverage on develop and analyze it locally, as well as the coverage on your PR and with that info ask them why is it happening? What do you think? If you need help just let me know  :+1:

**Comment by tansaku** [comment]
current semaphore error is:

```
[!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
You specified: paper_trail (= 4.0.0) and paper_trail (>= 8.1.2, ~> 8.1). Bundler cannot continue.

 #  from /home/runner/WebsiteOne/Gemfile:44
 #  -------------------------------------------
 #  gem 'paper_trail', '4.0.0'
 >  gem 'paper_trail', '~> 8.1', '>= 8.1.2'
 #  gem 'paranoia', '~> 2.4'
 #  -------------------------------------------

```

**Comment by tansaku** [comment]
thanks for this @theBoyMo - sorry for the delay in pulling it in - was sick for several weeks - will try and get this in as soon as dust settled from Rails 5 upgrade

**Comment by nisevi** [comment]
@tansaku can we merge this one? :+1:

**Pull request merged**
