### PR TITLE
Add validation for repeat_ends in event model

### PR DESCRIPTION
**Pull request by Danielshow**
#### Issue addressed
This PR fixes the issue below by validating repeat_ends field in Event model

fixes [#2926](https://github.com/AgileVentures/WebsiteOne/issues/2926)

#### Testing
Fix failing test by adding repeat_ends field to factories

### CODE REVIEW

**Comment by tansaku** [comment]
@Danielshow this looks great!

I guess my only question would be whether we need some new test to expose the issue being fixed?  what do you think?

**Comment by Danielshow** [comment]
Sure @tansaku, I will add a test to the models to make sure the field is always added. Will update soon

**Comment by NickSchimek** [comment]
Thanks @Danielshow for the work you put into this. It looks like great work to me!

@tansaku The issue #2926 probably should’ve been closed or redefined after fixing the Event query. I definitely overlooked that.

After I wrote the issue I had done more investigation and I realized the main issue was that the `repeat_ends_on` string is incorrect when an event is updated from a `recurring event with an end date` to a `recurring event that never ends`, because the `repeat_ends_on` field does not get changed in the front end and sends up the old information to the backend on update. It’s actually a front end issue, not a backend issue. Realizing this I was able to fix the Event query without having to change anything in the front end, but inadvertently left the ticket open without updating it.

It's actually not a validation issue, but an issue with the information coming from the front end. This can be seen if you open up the network tab and watch the params being sent. By creating an event that ends on 5/31, and then editing the event to never ends the front end and verifying it still sends up the ends on date 5/31 as seen here:

Screenshot 2019-05-29 12 09 19

Those two pieces of information in an event object contradicts each other.

Not sure what to do here. This is great work you put into this PR, but I would also like the repeat ends on string fixed. What do you think @Danielshow ? I guess I could update the old issue or create a new issue. Let me know how you feel about it.

**Comment by Danielshow** [comment]
Sure, @NickSchimek. You can update or create a new issue and assign it to me. I will love to work on it

**Comment by tansaku** [comment]
great work @NickSchimek and @Danielshow - I think if we have this green with a test let's merge and create a new issue for anything outstanding - the sooner we can get things into production the better I say :-)

I'll merge tomorrow unless anyone objects ...

**Comment by NickSchimek** [comment]
@Danielshow issue has been created #3215 if you'd like to work on it just make a comment stating that your working on it as I wasn't able to assign you to it. Thanks for all your help!

**Pull request merged**
