### PR TITLE
send users welcome emails when they join projects

### LINKED ISSUE #2537: automate emails to folks joining projects
@maryam21 previously created a great feature (suggested by @FedericoEsparza #1813 ) where project managers are alerted by email to folks joining their projects.  

It's been really interesting to see who is signing up for which projects, and I'd love to see this feature extended so that the folks joining would also get an email welcoming them to the project.  At the moment I am doing this manually for the projects that I am managing, sending emails like this:

> Hi,

> Thanks so much for joining the WebSiteOne project - as you might know, it's the Rails code that powers our main site - we coordinate via #websiteone on slack and there's a #websiteone-install channel for help to get set up.

> Just reach out if there's anything you need

> Best, Sam 

I've love to automate these emails and give all the project managers the ability to set a default greeting template for them to include whatever info, links, greeting they thought would be good for newcomers to get.

### PR DESCRIPTION
**Pull request by tansaku**
Setup welcome messages for when a user joins a project.

Also refactored the mailers for a project into its own mailer controller. This is the recommended way in the rails doc. 

The mail messages can be viewed by visiting `http://localhost:3000/rails/mailers/project_mailer`

fixes #2537

### CODE REVIEW

**Comment by tansaku** [comment]
@NickSchimek where did we get to with this one?

**Comment by NickSchimek** [comment]
we were going to take a look at building custom rspec matchers. Sorry I've been juggling to many things lately. If this is an urgent issue you can assign someone else to it or I will have more time for this at the end of the month.

**Comment by tansaku** [comment]
thanks @NickSchimek - I think the custom matchers should be a separate refactoring ticket - would be great to just get the functionality out with the existing tests, but no crazy rush ...

**Comment by tansaku** [comment]
@NickSchimek would love to get this one sorted - did you want to pair on it?  Or should we open it up for others to work on? (apologies if we already discussed - did we even talk about @aonomike working on it? I'm confused)

personally I'd love to get the functionality out and then work on the rspec refactoring in another ticket

**Comment by NickSchimek** [comment]
sorry I was busy chasing a white rabbit that I saw. I think @aonomike was wanting to work on this. I will ask him if he is and/or wants to pair on it; otherwise I can knock it out next week.

**Comment by NickSchimek** [comment]
@aonomike and I worked through this today and read through the Rails Mailer documentation together. 
Here is a list of items we noted down that need to be addressed to complete the issue.

Tasks needed to complete issue.

- [ ] Create fixture for unit testing Mailer controller.
- [ ] Update `config/settings.yml` so that [URL's can be generated](https://guides.rubyonrails.org/action_mailer_basics.html#generating-urls-in-action-mailer-views) within the mailer.
- [ ] May need to add other items...

Refactoring items:

- [ ] Extract Project mailers into it's own controller class.
- [ ] Call Projects mailer controller directly from the Project controller.
- [ ] Pass the Projects mailer a params object instead of arguments. (This allows for dryer code among other things)

Reference Links

- [Action Mailer Callbacks](https://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-callbacks)
- [Adding images in Action Mailer views](https://guides.rubyonrails.org/action_mailer_basics.html#adding-images-in-action-mailer-views)

**Comment by mattwr18** [comment]
Any news on this one @NickSchimek @aonomike? Can we help in some way?

**Comment by mattwr18** [comment]
Currently failing on this scenario/step... is it failing the same way locally?
```
 Scenario: when a person joins a project they get a welcome email                  # features/projects/notify_project_joinee.feature:17
    Given I am logged in as "John"                                                  # features/step_definitions/user_steps.rb:431
    And I go to the "show" page for project "hello world"                           # features/step_definitions/basic_steps.rb:266
    When I click "Join Project"                                                     # features/step_definitions/basic_steps.rb:95
    Then "john@doe.com" should receive a "Welcome to the hello world project" email # features/step_definitions/email_steps.rb:9
      expected "John Doe just joined hello world project" to include "Welcome to the hello world project" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/email_steps.rb:16:in `check_email'
      ./features/step_definitions/email_steps.rb:10:in `/^"(.*?)" should( not)? receive a "(.*?)" email(?: containing "(.*)")?$/'
      features/projects/notify_project_joinee.feature:21:in `Then "john@doe.com" should receive a "Welcome to the hello world project" email'
    HTML screenshot: /home/runner/WebsiteOne/tmp/capybara/screenshot_2018-12-24-19-14-27.982.html

Failing Scenarios:
cucumber -p second_try features/projects/notify_project_joinee.feature:17 # Scenario: when a person joins a project they get a welcome email
```

**Comment by NickSchimek** [comment]
@mattwr18 Yes, that failure is expected. I will get this ticket done soon.

**Comment by mattwr18** [comment]
ok, thanks... I don't know if it's helpful to post the failure from the build... just in case, I thought I might save you the trouble of scrolling down... would be nice if semaphore could post it automatically for us

**Comment by NickSchimek** [comment]
@tansaku @mattwr18 This is ready to review

**Comment by tansaku** [comment]
looks wonderful @NickSchimek - thanks so much! let's get this deployed :-)

**Pull request merged**
