### PR TITLE
Support more than one issue tracker

### LINKED ISSUE #2732: Add support for more than one issue tracker
Currently, I'm forced to add links to additional waffle boards into the repo links, because there is only one field for issue trackers.
phoenixone repos
 
This may be causing search filtering side effects.
 
Having extra fields for secondary issue trackers, and an `Add more issue trackers` button, would fix this.

### PR DESCRIPTION
**Pull request by aonomike**
Add tests around adding multiple issue trackers
#### Issue addressed

fixes #2732

### CODE REVIEW

**Comment by mattwr18** [comment]
would love to carve out some time for you to show me how this is going @aonomike!

**Comment by tansaku** [comment]
thanks for working on this @aonomike - is there something blocking you at the moment?

**Comment by mattwr18** [comment]
@aonomike I found this commit from @tansaku that sets up the `source_repositories`, have a look and see if you can spot any differences that might help you debug

**Comment by mattwr18** [comment]
Also, here is the documentation for the gem `cocoon`, which we are using to add and remove associations, and use javascript to add the fields https://github.com/nathanvda/cocoon

**Comment by aonomike** [comment]
All tests pass now, I am just not sure if there is any more rspec tests I should add? otherwise I will remove the WIP tag

**Comment by aonomike** [comment]
Screen Shot 2019-03-20 at 7 24 22 PM

**Comment by tansaku** [comment]
great work here @aonomike - really well done!

**Pull request merged**
