### PR TITLE
Fix future events query

### LINKED ISSUE #2118: improve events page performance
currently takes several seconds to load the events index page - from previous analysis my sense is that the time is spent in the ruby code generating the complete list of upcoming events from the recurring events.

We could improve performance by storing horizon of event data in the db up to six weeks and recalculating on edit, not on view ...

### PR DESCRIPTION
**Pull request by NickSchimek**
## Description
The future_events static method in the Events model is not querying the database correctly and returns non-repeating past events & recurring events that have ended.

I have added tests to that show this and once they run on the CI I will push up the fix and remove the caching that was implemented in #2824 

This fix is being implemented in order to improve the Events page load time without having to cache results. **With the 5k seed data I used I was able to reduce the load time from 4.5 seconds down to 0.3 seconds** That's **15x** faster!!!. 😲 

Fixes #2118 

### Testing
Here is a screen cap of the tests failing that should be passing. 
screenshot 2018-12-08 21 57 25

These tests show that the current implementation is returning events that are non-recurring past events and events with a repeat ends date in the past.

### When caching is implemented
When caching is implemented the upcoming events page does not list the current event at the top of the page as shown here: I think this can cause confusion, because `upcoming events` should mean events that have not occurred and/or are occurring, and shouldn't list events that are completed. One solution would be to remove the past results from the cached results before rendering the page or merging this PR 😄 

screenshot 2018-12-06 10 09 28

### Why this works - Ice cube
The ice cube gem is used to determine the events next recurring date (If I remember correctly I believe its using some sort of recursive algorithm that is very inefficient for large data sets). Currently we're passing in thousands of events to ice cube which is the cause for the slow down for the page load time. By handing off only active events to ice cube the page load time will be more efficient. This is why improving (correcting) the event query to only return events that are active significantly improves the page load time.

### CODE REVIEW

**Comment by NickSchimek** [comment]
All tests are passing except for this one: `features/events/list_repeating_events.feature:12` - I actually created an issue regarding this yesterday #2923 . This doesn't seem to be caused by this PR since I'm seeing it in production. @tansaku @mattwr18 you have any idea what caused this?

**Comment by NickSchimek** [comment]
whoops I did not take a close enough look at the failing test. The test is labeled saying that it checks timezone, but it's also checking if repeating events are displayed. This was failing because the Event wasn't being initialized with the `repeat_ends` field set. This field should be required when creating an Event, and I've created issue #2926 to fix this.

**Comment by NickSchimek** [comment]
All tests passing 🎉 , However `codeclimate/total-coverage` doesn't seem to like that I added more tests to the codebase 😆

**Comment by tansaku** [comment]
Looking at the production data I see that the Martin Fowler scrum has a non-nil `repeat_ends_on` even though the the `repeat_ends` is set to false

```
[2] pry(main)> Event.second
  Event Load (0.6ms)  SELECT  "events".* FROM "events" ORDER BY "events"."id" ASC LIMIT $1 OFFSET $2  [["LIMIT", 1], ["OFFSET", 1]]
=> #<Event:0x00007fd6a32a45c8
 id: 2,
 name:
  "\"Martin Fowler\" Scrum and Pair Hookup - All Welcome :-) Discuss Any Project, Ask Any Question, Or Just Listen In :-)",
 category: "Scrum",
 description:
  "\"Martin Fowler\" Scrum - for coordination of AgileVentures projects and PairProgramming hookups. This Scrum is named in honour of Martin Fowler, author of the book \"Refactoring\" and one of the original 17 signatories of the Agile Manifesto.<br/><br/>\r\n\r\nPlease join and discuss any project, ask any question!<br/><br/>\r\n\r\nCurrent Scrum masters: Sigu Magwa and Sam Joseph<br/><br/>",
 repeats: "weekly",
 repeats_every_n_weeks: 1,
 repeats_weekly_each_days_of_the_week_mask: 31,
 repeat_ends: false,
 repeat_ends_on: Sun, 23 Mar 2014,
 time_zone: "UTC",
 created_at: Tue, 11 Mar 2014 02:16:35 UTC +00:00,
 updated_at: Fri, 02 Mar 2018 12:24:30 UTC +00:00,
 url: "https://talkgadget.google.com/hangouts/_/gsas2mirbikwbdjmyhrxd5iwuma?hl=en",
 slug: "martin-fowler-scrum-and-pair-hookup",
 start_datetime: Tue, 11 Mar 2014 12:02:00 UTC +00:00,
 duration: 15,
 exclusions: nil,
 project_id: nil,
 creator_id: 3,
 for: nil,
 modifier_id: nil,
 creator_attendance: true>
```

**Comment by tansaku** [comment]
I adjusted the query to:

```
  def self.future_events
    Event.where('start_datetime > ? OR repeat_ends = false OR repeat_ends_on > ?', Time.current - 1.day, Time.current - 1.day)
  end
```
and this allows the scrums to appear, but the performance drops off again.

When I check the number of future events with your method I get 37, but removing the "repeat_ends_on IS NULL" clause I get 124 - here's a list - I think a lot of them are defunct ...

```
["Atlantic Scrum",
 "WebsiteOne pair programming",
 "OSRA - PP on Orphan model",
 "pair programming: events including hookups, scrums, hangouts -- Yaro, Jon, and more?",
 "WebsiteOne: Authentications Controller Refactoring",
 "websiteone: event_occurrences bug fix / refactor",
 "Pair Programming on OSRA",
 "websiteone: event and hangout refactor: user stories",
 "events features (and more?)... Jon & Amal, others welcome.",
 "websiteone: events & hangouts",
 "Event Scheduler",
 "OSRA Planning",
 "websiteone- event migration:: Jon, Amal, more?",
 "Codealia.org Reboot Meeting",
 "env",
 "websiteone- event migration:: Jon, Christian,more?",
 "one off meeting",
 "Local Support Client Meeting",
 "Test Scrum",
 "Test event",
 "OSRA Developer Meeting",
 "one off meeting",
 "WSO event management",
 "Test event",
 "Website one pairing ",
 "WebsiteOne",
 "WebsiteOne Client Meeting",
 "WebsiteOne - Hangouts flow feature",
 "Pacific Fun Scrum",
 "LocalSupport: edit volunteer opportunities",
 "WebsiteOne - Hangouts flow feature",
 "Events manager, Jon & Yaro",
 "WSO event management",
 "WSO event management",
 "ESAAS: Level 2 Certificates",
 "PP on WSO - Hangouts flow",
 "WebsiteOne pair programming",
 "WebsiteOne - Hangouts flow feature",
 "LocalSupport: edit volunteer opportunities",
 "WebsiteOne pair programming",
 "pair programming, hangouts",
 "WebsiteOne pair programming",
 "LocalSupport: edit volunteer opportunities",
 "websiteone- hookup manager",
 "LocalSupport: edit volunteer opportunities",
 "Remote Pair Programming sponsored by Makers Academy",
 "LocalSupport: edit volunteer opportunities",
 "websiteone- hookup manager",
 "WebsiteOne - Show current live sessions",
 "LocalSupport: edit volunteer opportunities",
 "LocalSupport pairing",
 "websiteone- hookup manager",
 "LocalSupport pairing",
 "websiteone- hookup manager, maybe more...",
 "more website one, hookup manager",
 "WebsiteOne PP: Event time zone",
 "Document Updates History",
 "WebsiteOne PP: Event time zone",
 "WebsiteOne - Redirect after login",
 "AmericasScrum and Pair Hookup",
 "WebsiteOne - Hangout button for Projects",
 "Test event",
 "WebsiteOne PP: Event time zone",
 "help with pull requests",
 "testing overnight times for scrum",
 "LocalSupport: edit volunteer opportunities",
 "websiteone- event migration:: Jon, Amal, more?",
 "LocalSupport: edit volunteer opportunities",
 "websiteone- event migration",
 "WebsiteOne Document Revisions",
 "LocalSupport: edit volunteer opportunities",
 "websiteone- event migration",
 "websiteone- event migration:: Jon, Amal, more?",
 "OSRA - PP on git issues",
 "websiteone- event migration:: Jon, Amal, more?",
 "OSRA PP: views for Partner model",
 "websiteone- hookup manager and event migration:: Jon, ++",
 "websiteone: event and hangout refactoring",
 "Test of Pair Programming using project filtering",
 "Pair programming on CS169 - Test  screen sharing",
 "CS169, HW1-Pair Programming",
 "CS169x Pair Programming - HW0 Ruby Intro",
 "cs169 pana16 Pair Programming Test - HW1",
 "HW-3 Rails Intro Pair Programming ",
 "Pairing on CS169 HW0 Ruby Intro",
 "SHF Project Scrum and Pairing Hookup",
 "AV Marketing Meeting",
 "Pairing on ADURoR:Ruby Intro",
 "AsyncVoter Retro/KickOff",
 "LocalSupport Kick Off/Retro",
 "AV Community Talk / New Members Meeting",
 "Americas \"Dave Thomas\" Scrum and Pair Hookup",
 "WebsiteOne Planning",
 "Wiki Ed Dashboard Project Checkin",
 "Elixir/Phoenix Mob",
 "React Mob",
 "Pairing on dda-pallet: Automated creation of your project IDE",
 "Pairing on CS169 HW0 Ruby Intro",
 "AutoGraders Client Meeting (BetaSaaSers)",
 "Rundfunk-Mitbestimmen Meeting",
 "Pairing on CS169 HW0 Ruby Intro",
 "SHF Client Meeting",
 "HW1 cs169.1x",
 "Hangperson game",
 "Pairing on CS169 HW0 Ruby Intro",
 "Pairing on CS169 HW0 Ruby Intro",
 "Pairing on CS169 HW0 Ruby Intro",
 "Thomas Zhang",
 "PhoenixOne biweekly Scrum or Retro/Kickoff",
 "NHS Healthy London Partnership (HLP) Wiki project",
 "Test Hangout Demo",
 "Pairing on CS169 HW0 Ruby Intro",
 "Agile Development Using Ruby on Rails \"MOOC\" Mob",
 "Local Support Pair Programming Session",
 "WebDev Mob",
 "#phoenix_one open pairing session",
 "\"Kent Beck\" Scrum and Pair Hookup - All Welcome :-) Discuss Any Project, Ask Any Question, Or Just Listen In :-)",
 "SHF Client Meeting",
 "Deep Learning Mob",
 "Ethereum mob programming",
 "Smart contract mob programming",
 "\"Martin Fowler\" Scrum and Pair Hookup - All Welcome :-) Discuss Any Project, Ask Any Question, Or Just Listen In :-)",
 "Rails 5 TDD Mob",
 "SHF Sprint review and planning"]
```

I think we may ave a fair number of junk old events in the system that are clogging us up - here's the old atlantic scrum:

```
=> #<Event:0x00007fd6a68fbea0
 id: 66,
 name: "Atlantic Scrum",
 category: "Scrum",
 description: "",
 repeats: "never",
 repeats_every_n_weeks: 1,
 repeats_weekly_each_days_of_the_week_mask: 0,
 repeat_ends: false,
 repeat_ends_on: Tue, 05 Aug 2014,
 time_zone: "UTC",
 created_at: Tue, 05 Aug 2014 14:20:01 UTC +00:00,
 updated_at: Tue, 05 Aug 2014 14:20:01 UTC +00:00,
 url: nil,
 slug: "atlantic-scrum",
 start_datetime: Tue, 05 Aug 2014 14:19:00 UTC +00:00,
 duration: 30,
 exclusions: nil,
 project_id: nil,
 creator_id: nil,
 for: nil,
 modifier_id: nil,
 creator_attendance: true>
```

looks like it's been removed by setting the days of the week mask to zero ...

you might need a copy of the production data to really get to the bottom of this ...

**Comment by NickSchimek** [comment]
Thanks for checking @tansaku and for the additional information. I will take another look at it.

**Comment by NickSchimek** [comment]
OK. @tansaku I figured out what's happening here. There is actually nothing wrong with the query string the way it is, however when a repeating event is updated from ending on a certain date to never ending the `repeat_ends_on` field is not updated correctly. It still lists the same (obsolete) `repeat_ends_on` date, however the `repeat_ends` flag is set correctly which assumes `ice cube` ignores the `repeat_ends_on` date if `repeat_ends` is set to `false`, which is why there hasn't been an issue listing upcoming events, however we should ensure its set properly so that we can query only active events. 
There is really only one way to fix this
- [ ] Fix the information coming from the frontend to properly set repeat_ends_on to the correct value. Issue #2932 
- [ ] Manually update active events (I think only the Scrum event) to set `repeat_ends_on` correctly

**Comment by NickSchimek** [comment]
OK I think I have a query string that will work without having to change the frontend. I will push it up in a bit.

**Comment by NickSchimek** [comment]
Okay @tansaku I'm fairly confident that this new query string will capture all active events and zero inactive events. We could close that related issue I created, but it might be good experience for someone to fix.

**Comment by tansaku** [comment]
thanks @NickSchimek - this seems to be running pretty slowly on my machine with prod data.  Should we get you set up with that data so you can test yourself?  if i have your heroku email I can give you access to production to pull down a clone ... assuming you've signed our AV data confidentiality agreement (GDPR and all that) http://bit.ly/AV-confidentiality

Also, probably nothing, but I wonder about the how the ANDs and ORs are being interpreted in your query - do we not need some additional parentheses to ensure that the we are constructing the correct query?

```sql
SELECT "events".* FROM "events" WHERE (start_datetime > '2018-12-10 14:41:06.265116' OR repeat_ends = false AND repeats != 'never' OR repeat_ends = false AND repeat_ends_on IS NULL OR repeat_ends_on > '2018-12-10 14:41:06.265439') AND NOT (repeats = 'never' AND start_datetime < '2018-12-10 14:41:06.266057')
```

looking at that early sequence of ANDs and ORs, I'd be hard pressed to say exactly how the postgresql is parsing that statement.  Apologies if I'm just forgetting the obvious binding order ...

in the meantime perhaps we can reduce the cache expiration on the current events caching ...

**Comment by NickSchimek** [comment]
I find that a bit surprising. I signed the agreement and will send you my email so that I can take one more look at it with real data.

**Comment by NickSchimek** [comment]
@tansaku Do you recall how many events was it pulling in with the latest query?

**Comment by tansaku** [comment]
```
Loading development environment (Rails 5.2.2)
[1] pry(main)> Event.future_events.count
   (3.8ms)  SELECT COUNT(*) FROM "events" WHERE (start_datetime > '2018-12-10 17:05:05.692454' OR repeat_ends = false AND repeats != 'never' OR repeat_ends = false AND repeat_ends_on IS NULL OR repeat_ends_on > '2018-12-10 17:05:05.692822') AND NOT (repeats = 'never' AND start_datetime < '2018-12-10 17:05:05.717455')
=> 25

```

**Comment by tansaku** [comment]
double checked and load times are still slow - might be something to do with the daily frequency of the scrums ...

**Comment by NickSchimek** [comment]
Yes, perhaps. The query count being 25 seems about right. Short of a complete refactor/rebuild of the Events scheduling the caching is probably the best way to solve this for now. And reducing the cache expiration should solve the main issue I had with caching. 

I will pull down production and perhaps write a simple program to analyze performance load times throughout the day/night. If I don't find anything that can be approved on in the short term I will close this PR. I may also dig into the ice cube gem to check out the algorithms they are using. 

Perhaps its no the ice_cube gem, because their tagline is this: `Allows easy creation of recurrence rules and fast querying`. 😄

**Comment by NickSchimek** [comment]
Well this is weird. I pulled down production and do not see a slow down, but when I pull down production using the method you provided I see the slowdown you mentioned, however the data from your method seems outdated which you can see by pulling up the `kent beck` scrum id `3` and look at `repeat_ends` is set to `false`, but in my pull its sent to `true`, which makes sense because that scrum is no longer occurring. This is weird cause with your method we get fewer events returned...
I'll send you the method I used.

**Comment by NickSchimek** [comment]
@tansaku I've got success! The slowdown only occurred when evaluating event id's 2 and 3. They each have been running everyday for the last four years and so there are a few thousand event_instances associated to each of them. 

Part of the logic in the events model is to grab the most recent event_instance and determine if its currently running (on air), however the logic was grabbing all event_instances and then checking each one.

**Comment by NickSchimek** [comment]
I discovered some faulty tests with the latest update. This is not done yet, but wanted to push up the latest changes.

**Comment by NickSchimek** [comment]
@tansaku This is fixed and working now. We were using one of ice_cubes methods improperly. The wording for that method is a bit confusing, and I think I will post an issue asking about it. I updated the method to grab the event_instances from the last month instead of grabbing all event_instances from the dawn of creation. All we're using the method for is to return the current event end/start_time, and so grabbing every single event is not necessary. 

Currently seeing 1 second page load time. Of course this isn't as fast as caching, however if someone creates an event then they will immediately see it on the calendar, where as with caching they wont see it until the next time it updates which can could cause confusion and panic to set it. 😄

**Comment by tansaku** [comment]
that's brilliant @NickSchimek - great work! :-)

Actually we have post-edit hooks with the caching so that the updates force the cache to update, but that has the downside that saves of updates take longer, and caching is something to be avoided if at all possible.

Really well done identifying the issue in ice-cube - this speed is a huge improvement for me locally, even better than caching - won't compete with react frontend caching, but this is a great piece of work @NickSchimek - huge thanks!

**Pull request merged**
