### PR TITLE
1577-fixing-broken-links-in-contributing

### PR DESCRIPTION
**Pull request by Romusc**
I fixed two links in CONTRIBUTING.md

#### Motivation and Context
When clicking this hyperlink:

image

We are currently redirected to: https://github.com/AgileVentures/WebsiteOne/pulls

When clicking this hyperlink:

image

We currently get a 404.

I have replaced both links with more appropriate redirections.

#### How Has This Been Tested?
No new tests have been added. All current tests pass

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by tansaku** [comment]
hi @Romusc - thanks for this - the first link fix much appreciated - the second link we do actually have our own pull request guidelines, but perhaps you think we should prefer to point to the github ones?

**Comment by Romusc** [comment]
@tansaku It probably makes more sense to link to the WSO pull request guidelines but I could not find this file (how_to_submit_a_pull_request_on_github.md) therefore I figured the github guidelines were a better placeholder than the current 404 error.

**Comment by tansaku** [comment]
@Romusc the file is here I think https://github.com/AgileVentures/WebsiteOne/blob/develop/docs/how_to_submit_a_pull_request_on_github.md

**Comment by Romusc** [comment]
@tansaku Thank you. I have now updated the link accordingly

**Pull request merged**
