### PR TITLE
824 Icons missing on time picker

### LINKED ISSUE #824: Icons missing on time picker

### PR DESCRIPTION
**Pull request by tochman**
Fixes #824 

* update bootstrap-timepicker to use the fontawsome classes

### CODE REVIEW

**Comment by diraulo** [comment]
@tochman this is strange ... didn't we merge this in already?

**Comment by diraulo** [comment]
@tochman this commit from @dalupus was already merged in #786
It was already pushed to production unless we missed another time picker on the site.
screenshot 2016-02-21 08 55 14

**Comment by tochman** [comment]
And it is on production. But not on develop... @dalupus made me aware that something must have happened on my PR with this commit.

**Comment by diraulo** [comment]
Okay. I see that now. I will merge this then

**Pull request merged**
