### PR TITLE
First brush at call to action improvement

### PR DESCRIPTION
**Pull request by mtc2013**
Here's a picture of the screen on desktop: 

screen shot 2017-01-24 at 12 19 45 pm

### CODE REVIEW

**Comment by tansaku** [comment]
@mtc2013 cool - we could even drop the "let's code"

or go with "Sign up to Starting Coding!" and perhaps it needs to look more like an actual link or button to emphasize it can be clicked?

**Comment by tansaku** [comment]
@mtc2013 from discussions today I wonder if getting people to add their email address for newsletter is even more important than getting them signed up?

**Comment by tansaku** [comment]
but simplest thing first I guess - simplest to add some "sign up" call to action

**Comment by mtc2013** [comment]
@tansaku updated with a better style and test:

screen shot 2017-01-25 at 12 21 56 pm

**Comment by tansaku** [comment]
great - what we were just talking about - I would be tempted to make text larger and reduce width of button - happy to do tweak myself if you'd like to move on to something else

**Comment by mtc2013** [comment]
@tansaku give it a go.  had a bit of trouble getting the text bigger.  I used a bootstrap class to style, and one of the things is it will expand to the containing width (block level) to get that larger size

**Comment by mtc2013** [comment]
Made text larger.  
screen shot 2017-01-25 at 1 15 40 pm

**Comment by mtc2013** [comment]
@tansaku tada

screen shot 2017-01-25 at 1 22 22 pm

**Comment by tansaku** [comment]
liking it @mtc2013 - tempted to start tweaking the color.  Is that our standard blue?  Should we make it lighter? make it change on mouse over?  Don't worry if you've had enough here.

Perhaps we can show to folks in scrums tomorrow and get some input from folks like @lollypop27

**Comment by mtc2013** [comment]
@tansaku perhaps we should push it out first? I mean it seems to be a clear win over what we currently have.  Subtle tweaks can be discussed in scrum and people can look at it on production?

**Comment by tansaku** [comment]
one reason to avoid too many tweaks on production is just for consistency of experience, but yes it could just be pushed.  It will take a little while to move it along the chain anyway, during which people can look at it on develop and staging

**Comment by mtc2013** [comment]
@tansaku on hover now the background of the button becomes that of the underlying containing div.. that kind off offwhite, and the text goes to the buttons former blue on hover.  can't really get a good screenshot of it but if you pull it down and run it you'll see.

**Comment by tansaku** [comment]
thanks @mtc2013 - doh, and I forgot to show in scrum - will get it onto develop to share or something ...

**Comment by tansaku** [comment]
great work on this @mtc2013 - I've got it running locally - one tiny thing was that I found that completely inverting on rollover was actually kind of painful, i.e the sudden white.  I just changed to:



with the roll over going to our deeper blue that's part of the nav bar:



but you're right we should get something out there, and then keep tweaking the color scheme ...

**Comment by tansaku** [comment]
that's with: 

```css
.call-to-action:hover {
    background: #34495e;
}
```

**Comment by mtc2013** [comment]
@tansaku unfortunately this doesn't play well on the mobile browsers

**Comment by mtc2013** [comment]
@tansaku updated with tweaks for various mobile browsers!

**Comment by tansaku** [comment]
@mtc2013 looks good in portrait:



landscape still has an issue:

**Comment by mtc2013** [comment]
@tansaku updated again

**Pull request merged**
