### PR TITLE
1878 - Upgrade 'sprockets-rails' gem.

### PR DESCRIPTION
**Pull request by nisevi**
https://waffle.io/AgileVentures/WebsiteOne/cards/59db2223a9bcd5007498da9e

### CODE REVIEW

**Comment by tansaku** [comment]
@nisevi is this passing for you locally?

**Comment by nisevi** [comment]
@tansaku this is passing on `rspec` and `cucumber` but when running `jasmin` is failing so I have to take a look at those, when I created the PR I only checked those two and I forgot to check `jasmin`. So maybe we can close this PR and open a new one when `jasmin` passes? what do you think?

**Comment by nisevi** [comment]
This is part of the error we are getting:

```The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /home/runner/WebsiteOne/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:238:in `block in load_dependency'
[3489] Puma starting in cluster mode...
[3489] * Version 3.11.0 (ruby 2.3.1-p112), codename: Love Song
[3489] * Min threads: 1, max threads: 16
[3489] * Environment: development
[3489] * Process workers: 3
[3489] * Preloading application
[3489] * Listening on tcp://0.0.0.0:37302
[3489] Use Ctrl-C to stop
[3489] - Worker 0 (pid: 3525) booted, phase: 0
[3489] - Worker 1 (pid: 3530) booted, phase: 0
[3489] - Worker 2 (pid: 3540) booted, phase: 0
Waiting for Jasmine on 37302...
jasmine server started
FF.FFFFFFFFFF..........FFF...FFFFFFFFFFFFFFFF.....FFF.....FFF.FFFF.FF.FFFFF
Failures:
          AccordionCollapse module should create a module called "AccordionCollapse"

          Expected undefined to be defined.
          stack@http://localhost:37302/__jasmine__/jasmine.js:2338:37
buildExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:2308:19
expectationResultFactory@http://localhost:37302/__jasmine__/jasmine.js:858:40
addExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:487:58
addExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:802:41
http://localhost:37302/__jasmine__/jasmine.js:2252:32
http://localhost:37302/__spec__/accordion_collapse_spec.js:11:53


          AccordionCollapse module should change class when clicked once

          Expected false to be truthy.
          stack@http://localhost:37302/__jasmine__/jasmine.js:2338:37
buildExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:2308:19
expectationResultFactory@http://localhost:37302/__jasmine__/jasmine.js:858:40
addExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:487:58
addExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:802:41
http://localhost:37302/__jasmine__/jasmine.js:2252:32
http://localhost:37302/__spec__/accordion_collapse_spec.js:16:85


          Affixed Navbar should define a new WebsiteOne module called "AffixedNavbar"

          Error: <spyOn> : could not find an object to spy upon for onScroll()
Usage: spyOn(<object>, <methodName>) in http://localhost:37302/__jasmine__/jasmine.js (line 4732)
          spyOn@http://localhost:37302/__jasmine__/jasmine.js:4732:102
spyOn@http://localhost:37302/__jasmine__/jasmine.js:1032:37
spyOn@http://localhost:37302/__jasmine__/jasmine.js:4571:23
http://localhost:37302/__spec__/affix_navbar_spec.js:22:28
attempt@http://localhost:37302/__jasmine__/jasmine.js:4289:50
run@http://localhost:37302/__jasmine__/jasmine.js:4217:27
execute@http://localhost:37302/__jasmine__/jasmine.js:4199:13

          Expected undefined to be defined.
          stack@http://localhost:37302/__jasmine__/jasmine.js:2338:37
buildExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:2308:19
expectationResultFactory@http://localhost:37302/__jasmine__/jasmine.js:858:40
addExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:487:58
addExpectationResult@http://localhost:37302/__jasmine__/jasmine.js:802:41
http://localhost:37302/__jasmine__/jasmine.js:2252:32
http://localhost:37302/__spec__/affix_navbar_spec.js:27:53
```

**Comment by tansaku** [comment]
ah, hmm, this looks like a tricky on @nisevi - we should maybe dig into it a little after a scrum - maybe tomorrow after Martin Fowler?

**Comment by nisevi** [comment]
@tansaku perfect, tomorrow then :+1:

**Comment by nisevi** [comment]
Closing this one since I'm gonna do the upgrade creating the PR from the original repository.

**Pull request closed without merging**
