### PR TITLE
Refactor GitHub languages job

### LINKED ISSUE #2586: Refactor GithubLanguagesJob
GithubLanguagesJob got a little long (only slightly) but a great opportunity to refactor the high level narrative out in the style of Avdi Grimm's confident coding!

### PR DESCRIPTION
**Pull request by ElisaRmz**
fixes #2586

### CODE REVIEW

**Comment by tansaku** [comment]
wonderful @ElisaRmz  - thanks so much

I do notice that there are some sensitive ids in the vcr yml file also committed.

we should probably filter these out.  VCR has some settings for this, see:

https://relishapp.com/vcr/vcr/v/3-0-3/docs/configuration/filter-sensitive-data

and

https://github.com/AgileVentures/WebsiteOne/blob/develop/features/support/vcr.rb#L13

I note that we should have checked this file in previously and sorted out the filtering ourselves, so if you don't want to work on this that's fine and we'll take care of it, but if you're interested, we'd love your help :-)

**Comment by ElisaRmz** [comment]
Could you show me exactly, what you like to filter?

**Comment by mattwr18** [comment]
Hey @ElisaRmz there are the client id and secret in the vcr cassette.. @tansaku has shared the link to the documentation of how to configure vcr to filter sensitive data and a link to where we are doing this in WebsiteOne.. let me know if you want to pair on this.

**Comment by tansaku** [comment]
thanks @ElisaRmz - all taken care of - really appreciate your help :-)

**Pull request merged**
