### PR TITLE
upgrades to ruby 2.3.1

### LINKED ISSUE #1310: upgrade to ruby 2.3.1
would be good

### PR DESCRIPTION
**Pull request by tansaku**
fixes #1310

### CODE REVIEW

**Comment by tansaku** [comment]
@diraulo I guess this won't deploy until we specify ruby 2.3.1 on the CI?

**Comment by diraulo** [comment]
@tansaku I think you need to run `bundle` to update the `Gemfile.lock` it still has the following in it. 
```ruby
RUBY VERSION
   ruby 2.3.0p0
```
That's probably the reason why Heroku is still trying to deploy using `2.3.0`

**Comment by tansaku** [comment]
@diraulo I did do that already - when I do it I'm not getting any changes to Gemfile.lock for some reason ...

**Comment by tansaku** [comment]
https://github.com/bundler/bundler/issues/4595

**Pull request merged**
