### PR TITLE
Update ruby version and clean up Dockerfile

### LINKED ISSUE #2887: Upgrade ruby for Dockerfile official image
We us ruby 2.5 official image in our Dockerfile, which means we need to update our ruby version as new minor versions are released.
## Expected Behavior

Keep our ruby up-to-date to continue to be able to take advantage of the official ruby 2.5 image
## Current Behavior

We are one 2.5.1, we can update to 2.5.3
## Possible Solution

Also, it is nice to clean up our Dockerfile
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39):
* Operating System and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by mattwr18**
#### Issue addressed

fixes #2887

### CODE REVIEW

**Comment by mattwr18** [comment]
@tansaku to get this to pass the build, we would need to change the ruby version in semaphore to ruby 2.5.3

**Comment by tansaku** [comment]
@mattwr18 I guess we're blocked on this till semaphore support 2.5.3 :-(

**Comment by mattwr18** [comment]
@tansaku I saw this page and tried out it's suggestion https://semaphoreci.com/docs/languages/ruby/ruby-support-on-semaphore.html but it was still failing... need to debug

**Comment by mattwr18** [comment]
this is still waiting for Semaphore to update their available Ruby versions...

**Comment by tansaku** [comment]
@mattwr18 is it worth putting in a support request to semaphore?

**Comment by nisevi** [comment]
@mattwr18 the configuration in the link you mentioned should work, since it will install the ruby version we need for this to work 👍 

```
cd ~/.rbenv/plugins/ruby-build && git pull && cd $SEMAPHORE_PROJECT_DIR
rbenv install 2.5.3
rbenv local 2.5.3
gem install bundler --no-ri --no-rdoc
```

**Comment by nisevi** [comment]
@mattwr18 I may be able to help you with this setup. If you want we can pair on it 👍

**Comment by mattwr18** [comment]
hey @nisevi sorry for not responding to you earlier! I was finishing up deliver a feature on another project.
I would love to pair with you!! This probably isn't high priority, but any excuse to pair with you would be great! 

What I will be working on that is of higher priority is getting this repo ready to serve the new React frontend that is almost ready to go into production, so if you are open to pairing on other tasks, it would be great to work on that together. :smile_cat: 

Let me know what days/times work well for you

**Pull request closed without merging**
